app/presenters/sector_presenter.rb
spec/presenters/sector_presenter_spec.rb

This change was already made in Panopticon to
support the /latest and /email-signup pages, but
not updated here.  Since Panopticon doesn't use
the URL arbiter for this, that means that
Collections Publisher can sometimes overwrite the
prefix route with an exact route, taking the sub-
pages offline (see https://govuk.zendesk.com/agent/tickets/936651).
The intention is for these to change to multiple
exact routes when topic creation is moved from
Panopticon into Collections Publisher.

Register prefix routes for curated content.

---

app/notifiers/publishing_api_notifier.rb
app/presenters/sector_presenter.rb
spec/notifiers/publishing_api_notifier_spec.rb
spec/presenters/sector_presenter_spec.rb

Publishing API currently ignores this field and is about to start rejecting it.
It uses the version in the request URL instead.
For more context: alphagov/content-store#104

Remove base_path from Publishing API request body

---

lib/tasks/load_tags_from_content_api.rake

Tags will be migrated from Panopticon into Collections Publisher. To
make this process smoother, create a Rake task to do most of the work
for us.
The task itself aims to only import `section` and `specialist_sector`
tags. It then creates any tags that don't already exist.

Load tags from Content API into local database

---

lib/tasks/load_tags_from_content_api.rake

Previously, this task would migrate all of the tags from Panopticon, but
wouldn't publish tags which were "live".
Make sure that all live tags are in the correct state when migrated.

Publish all "live" tags once migrated

---

lib/tasks/load_tags_from_content_api.rake

This makes the task easier to run again in the future and won't blow up
should someone attempt to migrate data again.

Only publish tags that aren't already published

---

app/controllers/concerns/tag_create_update_publish.rb
app/views/shared/tags/edit.html.erb
app/views/shared/tags/index.html.erb
app/views/shared/tags/new.html.erb
app/views/shared/tags/show.html.erb
spec/controllers/mainstream_browse_pages_controller_spec.rb

This pull request removes the use of the `decent_exposure` gem for the `Tag`-like objects in this application.
The reason for doing this is because upcoming features in the application require some feature diversion between `Topic` and `MainstreamBrowsePage` objects and will result in changes being made to the views.
**NOTE:** `decent_exposure` is still being used for the `ListItem` and `Sector` objects and they will be cleaned up in the near future.

Remove decent exposure from tags

---

app/models/tag.rb
spec/models/tag_spec.rb

This is currently joining the child slug with the parent slug.  This is
incorrect because the child slug actually includes the parent slug in
the database.
We should revisit this at some point because it probably makes sense for
the child slug to not include the parent slug.

Fix Tag#base_path for child tags.

---

jenkins.sh

Rails' automatic schema maintenance doesn't cope 100% with switching
between branches with different schemas.  Specifically, it doesn't
handle changes to a column's null state.
Explicitly dropping and re-creating the test database on each run
ensures that we're running with a clean state.
This should prevent test failures like https://ci-new.alphagov.co.uk/job/govuk_collections_publisher_branches/174/console

Reset the database on each CI run.

---

app/views/shared/tags/_metadata.html.erb
app/views/shared/tags/_table.html.erb

Where "urls" are displayed for topics or mainstream browse pages, they
are now clickable and open the corresponding URL on the live site when
clicked.
https://trello.com/c/4xrXljxX/61-make-tag-links-in-collections-publisher-clickable

Make tag links in collections publisher clickable

---

app/views/mainstream_browse_pages/edit.html.erb
spec/features/associating_topics_to_mainstream_browse_pages_spec.rb

When editing `MainstreamBrowsePage` items, show the already assigned
`Topic` values.
The response to this involved updating the use of
`options_from_collection_for_select` to provide the existing topics as
the fourth parameter (`selected`) in the form of an array of ids.
Also switched out the fields we're using to be symbols instead of
strings as that's what they're being converted to behind the scenes
anyway.

Existing topics appear when editing mainstream browse pages

---

db/schema.rb

This update is the results of running `rake db:migrate` and it causes a
change to the schema now that we've upgrade from 4.1.2 to 4.2.1.

Update schema for rails 4.2

---

app/models/mainstream_browse_page.rb
app/models/tag.rb
app/models/topic.rb
db/migrate/20150427094415_add_foreign_keys_for_lists_and_list_items.rb
db/migrate/20150427095118_add_foreign_keys_for_tags_and_tag_associations.rb
db/schema.rb
spec/models/list_spec.rb
spec/models/mainstream_browse_page_spec.rb
spec/models/tag_spec.rb
spec/models/topic_spec.rb

Where possible, we should get the database to enforce the schema in addition to our models.
This change add two migrations `AddForeignKeysForListsAndListItems` and `AddForeignKeysForTagsAndTagAssociations` as well as removing the equivalent `dependent` actions that exist on the respective models.
The initial work for this was done using the immigrant[1] gem, but it was pulled apart into separate commits and migrations to make it easier to understand. The `on_delete` actions were added to allow removal of the `dependent` actions on the models.
[1] https://github.com/jenseng/immigrant

Add missing foreign key constraints

---

app/models/mainstream_browse_page.rb
app/models/tag.rb
app/models/topic.rb
db/migrate/20150427135925_add_index_to_tag_content_id.rb
db/schema.rb
spec/models/mainstream_browse_page_spec.rb
spec/models/tag_spec.rb
spec/models/topic_spec.rb

Only enforced at DB level because we're unlikely to have collisions.
Most of the controllers look up tags by their content_id, so having an
index on this column is a good thing.

Add unique index on tag content_id.

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb

It's no longer being used anywhere in the app.

Remove decent_exposure.

---

app/models/mainstream_browse_page.rb
app/views/mainstream_browse_pages/edit.html.erb
spec/features/associating_topics_to_mainstream_browse_pages_spec.rb
spec/models/tag_association_spec.rb
spec/presenters/mainstream_browse_page_presenter_spec.rb

Top-level (parent) mainstream browse page records such as `/browse/driving` shouldn't have topics assigned to them. Only allow child `MainstreamBrowsePage` records to have topics assigned to them. Parents shouldn't have topics assigned to them.

MainstreamBrowsePage: only children can have topics associated

---

jenkins.sh

The gh-status API has an error result as well as a failure state.
Update jenkins.sh to set this when the script errors to be able to
distinguish errors from actual test failures.

Report build errors differently from failures.

---

spec/features/associating_topics_to_mainstream_browse_pages_spec.rb
spec/models/tag_association_spec.rb

These two `before` test blocks are no longer needed because we can do
the parent assignment as part of the `let!(..) {}` calls.

Remove `before` test blocks by assigning parents directly

---

jenkins.sh

To ensure that we start with a clean state for each build.  This also
prevents things like logfiles growing without bounds and filling up the
disks on the CI machines.

Include a git clean in jenkins.sh

---

lib/tasks/rspec.rake

This was causing errors on deploy because the rspec require errored
because rspec isn't installed.
Best viewed with `?w=1`

Don't load test tasks in production.

---

app/controllers/mainstream_browse_pages_controller.rb
app/models/tag.rb
app/views/mainstream_browse_pages/edit.html.erb
spec/features/associating_topics_to_mainstream_browse_pages_spec.rb

To make it easier to find topics to select.
Trello: https://trello.com/c/tUXtPH7a/91

Include parent title in topics dropdown and sort by both

---

app/views/lists/index.html.erb
spec/features/curating_topic_contents_spec.rb

The 'These will not be displayed to users' warning is only true for a
subtopic that has curated groups, so this hides it when there are no
groups.
Trello: https://trello.com/c/FyRu03Ux/96

Only show uncategorized warning when it applies.

---

app/controllers/application_controller.rb
app/controllers/list_items_controller.rb
app/controllers/lists_controller.rb
app/controllers/sectors_controller.rb
app/views/lists/edit.html.erb
app/views/lists/index.html.erb
app/views/sectors/index.html.erb
spec/controllers/sectors_controller_spec.rb

Previously, `panopticon_slug` was used in URLs. 
The only code that now uses `Topic#panopticon_slug` is https://github.com/alphagov/collections-publisher/blob/4c078e0259ea1d5742f23149e925b966ba28000b/app/models/topic.rb#L43, but that appears to be correct. @rboulton ?
In preparation for https://trello.com/c/u7tOFFXk/109-merge-sectors-and-topics-interfaces-in-collections-publisher
from :train:

Use content_id in URLs

---

app/assets/stylesheets/forms.scss
app/views/lists/edit.html.erb
app/views/lists/index.html.erb
app/views/mainstream_browse_pages/edit.html.erb
app/views/mainstream_browse_pages/new.html.erb
app/views/topics/edit.html.erb
app/views/topics/new.html.erb

Over-eager added CSS in 78ec9cc styled every button in the application as a submit-button. This is inappropriate for delete buttons. By using a explicit `btn-submit` class we stop inadvertent styling.

Fix layout of list delete-buttons

---

app/controllers/topics_controller.rb
app/helpers/status_helper.rb
app/models/mainstream_browse_page.rb
app/models/tag.rb
app/models/topic.rb
app/presenters/topic_presenter.rb
app/views/shared/tags/_table.html.erb
app/views/topics/edit.html.erb
app/views/topics/new.html.erb
app/views/topics/show.html.erb
db/migrate/20150527125401_add_beta_to_tags.rb
db/schema.rb
spec/features/curating_topic_contents_spec.rb
spec/features/topic_create_edit_spec.rb
spec/models/mainstream_browse_page_spec.rb
spec/models/tag_spec.rb
spec/models/topic_spec.rb
spec/presenters/topic_presenter_spec.rb

This PR adds a "Beta" checkbox to Topics. Users can check this box to add a beta-banner to the topic or subtopic page. This will be added to `collections` in a later PR.
Depends on a schema change in https://github.com/alphagov/govuk-content-schemas/pull/77. Be sure to pull `govuk-content-schemas` before running the tests. 
Trello: https://trello.com/c/H9UMp051/139

Topics can be in beta

---

app/models/topic.rb
spec/models/topic_spec.rb

`Topic#list_items_from_contentapi ` currently crashes on `GdsApi::HTTPNotFound` when the tag doesn't exist in the content api. We should return an empty array instead.
Trello: https://trello.com/c/C2ODigO4/142-collections-publisher-don-t-crash-when-tag-is-missing-in-content-api

Don't raise when tag is missing in content-api

---

lib/tasks/auto_annotate_models.rake
spec/models/list_spec.rb
spec/models/mainstream_browse_page_spec.rb
spec/models/tag_association_spec.rb
spec/models/tag_spec.rb
spec/models/topic_spec.rb
spec/models/user_spec.rb

Currently the `annotate` gem helpfully adds annotations to both the models in `app/models` and the specs in `spec/models`.
This is duplicate and makes for noisy commits.

Remove model annotations in specs

---

app/controllers/application_controller.rb
app/controllers/list_items_controller.rb
app/controllers/lists_controller.rb
app/controllers/tags_controller.rb
app/controllers/topics_controller.rb
app/models/mainstream_browse_page.rb
app/models/tag.rb
app/models/topic.rb
app/presenters/mainstream_browse_page_presenter.rb
app/presenters/tag_presenter.rb
app/presenters/topic_presenter.rb
app/views/lists/_list_editor.html.erb
app/views/lists/_new_list.html.erb
app/views/lists/_publish_button.html.erb
app/views/lists/_uncategorized_list_items.html.erb
app/views/lists/_untagged_list_items.html.erb
app/views/lists/edit.html.erb
app/views/lists/index.html.erb
app/views/mainstream_browse_pages/show.html.erb
app/views/topics/show.html.erb
config/routes.rb
spec/controllers/tags_controller.rb
spec/models/tag_spec.rb
spec/presenters/mainstream_browse_page_presenter_spec.rb
spec/presenters/tag_presenter_spec.rb
spec/presenters/topic_presenter_spec.rb
spec/spec_helper.rb

This PR adds the ability to group the links on mainstream browse pages into "curated lists".
This works identical to the current functionality for curating the list contents of a Topic:
https://www.gov.uk/browse/benefits/tax-credits
> Allow the content shown in 2nd level mainstream browse pages to be curated, in a similar way to that in which sub-topic page content can be curated. This curation should be limited to GDS editors (but viewing of mainstream browse pages is currently restricted in this way already, so this shouldn't be hard). Curated content should be able to be put into groups, with named headings, and have its order controlled. Content should be able to appear in more than one group.
https://trello.com/c/iy1tB6gU/124-add-curation-of-mainstream-browse-pages-to-collections-publ …

Curate lists for Mainstream Browse Pages

---

LICENSE.txt
README.md

The README is currently linking to a non-existing license file. This adds the default MIT / Crown Copyright license.
Part of https://trello.com/c/522sgjON/64-update-collections-publisher-readme

Add license to project

---

app/views/mainstream_browse_pages/edit.html.erb

This got lost in the refactoring somehow.

Restore page heading when editing browse page.

---

app/models/tag.rb
app/views/mainstream_browse_pages/edit.html.erb
app/views/topics/edit.html.erb
spec/controllers/mainstream_browse_pages_controller_spec.rb
spec/features/topic_create_edit_spec.rb
spec/models/tag_spec.rb

We previously allowed changing the slug for draft tags.  This doesn't
work properly because it's not possible to propogate the change to
Panopticon in this way (Panopticon returns a 404 when trying to update
the tag because it can't find a tag with the new slug - obviously).
Additionally, it's not really possible to support this because the
tag_id (containing the slug) is used as the foreign key when tagging
content, and therefore updating the tag's slug would break anything
tagged with it.
We therefore can't allow editing the slugs for tags until everything has
moved over to the 'new world', and is using content_ids to link
everything.

Prevent changing the slug for all tags

---

app/controllers/application_controller.rb
app/controllers/lists_controller.rb
app/views/layouts/application.html.erb

Lists used to only belong to Topics, so whenever we were on a page rendered by `ListsController` we highlighted the Topics entry in the navigation.
We now support lists for mainstream browse pages too (#71), so we need another way to determine in which section we currently are. By adding a helper method we can let the controllers decide which navigation item to highlight.
Trello: https://trello.com/c/iy1tB6gU/124-add-curation-of-mainstream-browse-pages-to-collections-publisher

Highlight the correct navigation item

---

jenkins.sh

This was reporting that the run errored instead of failed.  This is
because the error handler was being invoked any time a command exited
non-zero.
Changing this to run the tests as part of an if statement prevents the
error handler being triggered, and allows us to handle the outcome
apropriately.

Fix test failure github reporting.

---

app/helpers/header_helper.rb
app/helpers/status_helper.rb
app/models/tag.rb
app/views/lists/edit.html.erb
app/views/lists/index.html.erb
app/views/mainstream_browse_pages/edit.html.erb
app/views/mainstream_browse_pages/index.html.erb
app/views/mainstream_browse_pages/new.html.erb
app/views/mainstream_browse_pages/show.html.erb
app/views/shared/_header.html.erb
app/views/shared/tags/_table.html.erb
app/views/topics/edit.html.erb
app/views/topics/index.html.erb
app/views/topics/new.html.erb
app/views/topics/show.html.erb
spec/features/associating_topics_to_mainstream_browse_pages_spec.rb
spec/features/curating_topic_contents_spec.rb

Currently page headers are defined per page and differ. This PR:
- Adds a consistent `<h1>` header
- Adds a breadcrumb to let the user see the structure and navigate back
- Uses the page title as browser `<title>`
Part of an effort to improve the curated links editor. Trello: https://trello.com/c/VXdUyg2g/149-collections-publisher-improve-the-curated-links-editor
Best reviewed in Split view.

Make headings consistent across pages

---

app/assets/stylesheets/topics.scss
app/helpers/header_helper.rb
app/helpers/status_helper.rb
app/views/shared/tags/_table.html.erb
spec/features/viewing_topics_spec.rb

When a list is updated the tag is marked as "dirty", which means it has changes that have not been published to the content store and aren't shown on the site.
Adding a label will help users to see which tags have unpublished changes - currently only the appearance of the "Publish" button would indicate the published state.

Add "Unpublished changes" label for tags

---

app/assets/stylesheets/views/mainstream_browse_pages.scss
app/helpers/header_helper.rb
app/helpers/icon_helper.rb
app/models/tag.rb
app/views/mainstream_browse_pages/show.html.erb
app/views/shared/tags/_children.html.erb
app/views/shared/tags/_curated_links_preview.html.erb
app/views/shared/tags/_lists_of_links_preview.html.erb
app/views/shared/tags/_table.html.erb
app/views/shared/tags/_uncurated_links_preview.html.erb
app/views/topics/show.html.erb
spec/features/associating_topics_to_mainstream_browse_pages_spec.rb
spec/features/curating_topic_contents_spec.rb
spec/features/listing_browse_pages_spec.rb
spec/features/mainstream_browse_pages_spec.rb
spec/features/topic_create_edit_spec.rb
spec/features/viewing_topics_spec.rb
spec/helpers/icon_helper_spec.rb
spec/support/content_api_helpers.rb

This PR:
- Adds previews for lists on the show pages of `MainstreamBrowsePage` and `Topic`.
- Adds a little icon to all relevant pages to show wether the tag is alphabetical or curated.
Hopefully this will it easier to grasp the different "sort modes" for a tag.
Needs some wordsmithery.
(curated)
(alphabetized)

Show previews and sort mode for tags

---

app/presenters/mainstream_browse_page_presenter.rb
spec/presenters/mainstream_browse_page_presenter_spec.rb

[Trello Ticket](https://trello.com/c/D2vjglFv/110-store-full-information-needed-to-render-first-two-columns-of-a-mainstream-browse-page-in-content-store)
- removing use of `contentapi` by collections frontend.
- Making collections frontend simpler so we can more easily experiment with putting childcare content into it in a new way.
When collections-publisher sends a mainstream browse page document to the content store, it should include the full details needed to render the first two columns of the page, so that the collections frontend doesn't need to make a call to content-api to render these columns of a mainstream browse page.
This information consists of:
- For `/browse`, the titles, descriptions and base_paths of all the top level mainstream browse pages.
- For `/browse/foo`, the …

Send top and second-level pages to content-store

---

app/presenters/mainstream_browse_page_presenter.rb
spec/presenters/mainstream_browse_page_presenter_spec.rb

The method should never return an empty array. When @tag
is the active_top_level_browse_page, it should return its
own id.

Edit #active_top_level_browse_page_id

---

app/presenters/root_browse_page_presenter.rb
lib/tasks/publishing_api.rake
spec/presenters/mainstream_browse_page_presenter_spec.rb
spec/presenters/root_browse_page_presenter_spec.rb

- the work started in this PR: https://github.com/alphagov/collections-publisher/pull/86
- this [ticket](https://trello.com/c/D2vjglFv/110-store-full-information-needed-to-render-first-two-columns-of-a-mainstream-browse-page-in-content-store)
- removing use of `contentapi` by collections frontend.
- Making collections frontend simpler so we can more easily experiment with putting childcare content into it in a new way.
When collections-publisher sends a mainstream browse page document to the content store, it should include the full details needed to render the first two columns of the page, so that the collections frontend doesn't need to make a call to content-api to render these columns of a mainstream browse page.
This information is stored in entries in the "links" field, and …

Send root `browse` page data to content store

---

app/presenters/topic_presenter.rb
spec/presenters/topic_presenter_spec.rb

The `/topic/emails-signups` (plural) route has been deprecated in `collections` and [currently returns a 404](https://www.gov.uk/oil-and-gas/environment-reporting-and-regulation/email-signups).
Removing the route here will make cause the router to return 404, saving a request to collections app.

Remove deprecated route from topics

---

app/presenters/mainstream_browse_page_presenter.rb
lib/tasks/publishing_api.rake
spec/presenters/mainstream_browse_page_presenter_spec.rb

Now that /browse is being registered as an exact route, these routes
started returning 404s because they weren't registered here.  This adds
them back to allow the AJAX version of /browse to work again

Register .json route for mainstream browse pages.

---

app/presenters/root_browse_page_presenter.rb

This is redirected to the corresponding api location by the collections
app.

Include route for /browse.json

---

app/presenters/topic_presenter.rb
spec/presenters/topic_presenter_spec.rb

So that we can render the topic pages entirely from the content-store.

Include topic children in links

---

lib/tasks/populate_published_groups.rake

This hasn't shown any problems on preview, but the test itself was
messed up in a rebase.

Remove sanity test for dirty-checking

---

lib/tasks/publishing_api.rake

Some of the draft tags currently have paths that conflict with live
content, and therefore get rejected by the publishing-api.  This allows
up to push all published tags without running into the errors from these
problematic draft tags

Rake task to send published tags to publishing-api

---

app/helpers/application_helper.rb
app/models/mainstream_browse_page.rb
app/models/redirect.rb
app/models/tag.rb
app/models/topic.rb
app/notifiers/publishing_api_notifier.rb
app/presenters/redirect_presenter.rb
app/presenters/tag_presenter.rb
app/views/topics/_redirects.html.erb
app/views/topics/show.html.erb
db/migrate/20150622073111_create_redirects.rb
db/migrate/20150622073727_add_redirects_for_topics_namespace.rb
db/schema.rb
spec/factories.rb
spec/features/curating_topic_contents_spec.rb
spec/features/topic_create_edit_spec.rb
spec/migrations/add_redirects_for_topics_spec.rb
spec/models/redirect_spec.rb
spec/models/tag_spec.rb
spec/models/topic_spec.rb
spec/notifiers/publishing_api_notifier_spec.rb
spec/presenters/tag_presenter_spec.rb
spec/presenters/topic_presenter_spec.rb
spec/support/content_store_helpers.rb

This PR makes collections-publisher publish Topics to the `/topic` namespace.
- Publish Topics under `/topic`. Done by prepending `/topic` to the base path of Topics.
- Sets up redirects for the old URLs. This is done by publishing "redirect" content items for the version without `/topic`.
Best reviewed per-commit and in split view.
Trello: https://trello.com/c/EoWPp4qZ/187-move-topics-to-topic
After this is deployed, we need to republish all the items.
To help understand what is going on, we show the redirects for a topic if it has any:

Move topics to /topic namespace

---

Gemfile
Gemfile.lock
config/routes.rb
spec/features/sidekiq_monitoring_spec.rb

This commit exposes the sidekiq-web monitoring app on `/sidekiq`.
Sidekiq was added in https://github.com/alphagov/collections-publisher/pull/96. Users are authenticated via the normal GDS::SSO mechanism. They need the `Sidekiq Monitoring` permission to see the app.
Related to Trello: https://trello.com/c/v1B0aJxW/185
Note that `/sidekiq` is currently blocked by nginx.

Add Sidekiq monitoring

---

app/models/mainstream_browse_page.rb
app/models/tag.rb
app/notifiers/publishing_api_notifier.rb
spec/notifiers/publishing_api_notifier_spec.rb

When a top level mainstream browse page is added/published the root level browse page also needs to be updated.
https://trello.com/c/v1B0aJxW/185-update-content-store-when-list-of-browse-pages-change

Send root level browse page to content store

---

lib/tasks/publishing_api.rake

The rake task currently publishes all tags, *and* their dependent tags, doing a lot of duplicate work. This commit restricts the rake task to only publish a single tag.

Send single tags to content store in rake task

---

README.md
app/controllers/topics_controller.rb
app/notifiers/rummager_notifier.rb
config/initializers/services.rb
lib/tasks/rummager.rake
spec/controllers/topics_controller_spec.rb
spec/features/topic_create_edit_spec.rb
spec/notifiers/rummager_notifier_spec.rb

Send topics to rummager after update. Currently, the panopticon app sends data to Rummager for indexing.
Collections publisher owns the documents, so is the natural place to do this.
_This is a re-commit of 6dc69bc, which was reverted in 28c4d08 because it was committed straight to master._

Send topics to rummager after update

---

app/models/topic.rb
spec/features/topic_create_edit_spec.rb

The parent now includes a list of its children, so it's necessary to
re-send the parent when a child is created.
This data will then be used to render the top-level topic pages.

Send subtopic parents when creating subtopic

---

Gemfile
Gemfile.lock

They're present in other our repositories, they make debugging easier.

Add better_errors and binding_of_callers gems

---

app/controllers/mainstream_browse_pages_controller.rb
app/models/mainstream_browse_page.rb
app/models/tag.rb
app/models/topic.rb
app/views/mainstream_browse_pages/manage_child_ordering.html.erb
app/views/mainstream_browse_pages/show.html.erb
app/views/shared/tags/_children.html.erb
app/views/shared/tags/_metadata.html.erb
config/routes.rb
db/migrate/20150702143916_add_child_ordering_and_index_to_tags.rb
db/schema.rb
spec/features/mainstream_browse_pages_spec.rb
spec/models/tag_spec.rb

This PR is the first step towards allowing publishers to re-order mainstream pages.
Added a page where publishers can select the type of child ordering of a page (alphabetical or curated).
In the same page, the user will be able to input the order in which s/he wants to display them (in case of curated list).
Next step: When updating the child ordering, collections-publisher should send to content-store the parent page and the children in the publisher's wanted order.
NB: Cosmetic work will follow. This is absolutely not what it should and will look like.
Ticket: https://trello.com/c/Tpgjz0HI/167-collections-publisher-can-control-order-of-mainstream-browse-columns

Allow publishers to reorder mainstream pages

---

spec/presenters/mainstream_browse_page_presenter_spec.rb

Review by commit advised.
Adds tests around this work:
https://github.com/alphagov/collections-publisher/pull/115
Completes:
https://trello.com/c/Tpgjz0HI/167-collections-publisher-can-control-order-of-mainstream-browse-columns

Test the order in which child pages are rendered

---

app/presenters/mainstream_browse_page_presenter.rb
spec/presenters/mainstream_browse_page_presenter_spec.rb

We are going to allow publishers to re-order mainstream browse pages. But currently, these pages are displayed along with an "A to Z".
These changes are necessary for letting know `collections` when to display the above mentioned label and when not to.
Part of this ticket:
https://trello.com/c/bcTrheDZ/244-don-t-show-a-to-z-on-mainstream-browse-columns-which-aren-t-in-alphabetical-order

Send second_level_ordering to content-store

---

app/models/redirect.rb
db/migrate/20150713123425_add_redirect_uniqueness.rb
db/migrate/20150713124417_import_router_data_browse_redirects.rb
db/migrate/20150714140302_import_router_data_topic_redirects.rb
db/schema.rb

Now that we can model these here it makes sense to do so and reduce the volume of redirects in router-data.
This PR also adds a uniqueness constraint to the Redirects table to help avoid duplicates.

Import router-data redirects for browse pages and topics

---

app/models/tag.rb
app/views/shared/tags/_children.html.erb
app/views/shared/tags/_metadata.html.erb

A N+1 query was introduced recently because for each topic/browse page on the index page, we are making a query for the subtopics with either alphabetical or curated ordering. This caused a fair amount of extra database traffic.
To remedy this, this commit moves the sorting of the parents to ruby-land by using `sort_by`. This way all `children` for all tags are eager-loaded and we just have to execute one query.
Before: ActiveRecord: 159.5ms
After: ActiveRecord: 7.5ms
Not that [removing the .includes in _children.html.erb](https://github.com/alphagov/collections-publisher/commit/815dedf70821073f21a5902e36d29f34f4a38161#diff-21926eabfcc0366fe8005ef12ca6d26eL17) introduces a new N+1 query when loading the show page for mainstream browse pages with associated topics. These pages are less …

Fix N+1 on topic and browse page index pages

---

db/migrate/20150716103715_remove_unused_mainstream_browse_pages.rb
db/schema.rb

Two childcare mainstream browse pages were created,
but then the content was updated and they're no longer needed.
They were never published, and never should be,
but need deleting to tidy things up.
Ticket:
https://trello.com/c/drh7LqiI/249-delete-two-unused-childcare-mainstream-browse-page-tags

Delete unused mainstream browse pages

---

app/notifiers/publishing_api_notifier.rb
app/presenters/root_topic_presenter.rb
app/services/tag_republisher.rb
lib/tasks/publishing_api.rake
spec/notifiers/publishing_api_notifier_spec.rb
spec/presenters/root_topic_presenter_spec.rb
spec/services/tag_republisher_spec.rb
spec/support/content_store_helpers.rb

We are adding a new `/topic` page that displays all parent topics. This PR makes sure we create and update the `/topic` page in the content-store every time a parent topic is changed.
Best reviewed one-by-one.
Trello: https://trello.com/c/L84pTDgJ/233-create-page-at-topic
https://github.com/alphagov/collections/pull/145 will take care of the front-end.

Send `/topic` main page to content store

---

app/assets/javascripts/curated_lists.js
app/assets/stylesheets/curated_lists.scss
app/controllers/list_items_controller.rb
app/models/list.rb
app/models/list_item.rb
app/models/tag.rb
app/presenters/groups_presenter.rb
app/views/lists/_all_list_items.html.erb
app/views/lists/_list_editor.html.erb
db/migrate/20150723112749_change_list_item_api_url_to_base_path.rb
db/migrate/20150723134305_update_serialised_curated_lists.rb
db/schema.rb
spec/features/curating_topic_contents_spec.rb
spec/models/list_spec.rb
spec/models/tag_spec.rb
spec/presenters/groups_presenter_spec.rb
spec/presenters/tag_presenter_spec.rb
spec/support/content_api_helpers.rb

We want to update the frontend so that it can request tagged content
from rummager instead of contentapi. Rummager doesn't contain the
api_urls, so we'd have to fudge them from the base_path. This seems
wrong, and it would be better to send the base_paths in the curated
data. then we can match up the items by base_paths (both rummager and
contentapi have the base_path of the item).
This depends on alphagov/collections#148 being merged and deployed first.
This may be easier to review commit at a time.

Send base_path instead of api_url to content-store

---

app/views/topics/edit.html.erb
app/views/topics/new.html.erb
db/migrate/20150723161808_add_description_to_topics.rb
db/schema.rb

The frontend app is [currently generating fallback descriptions for topics](https://github.com/alphagov/frontend/blob/2b64f4989fcb7089d8e2c7255c78170ee7c624da/app/presenters/search_result.rb#L65). This migration adds the same description to the database, so that we don't need special code in `frontend` or `rummager`.
We need to run `rake rummager:index_topics` after deploying this change.
Trello: https://trello.com/c/AM4LQ2i3

Set descriptions for topics

---

app/controllers/mainstream_browse_pages_controller.rb
app/notifiers/rummager_notifier.rb
app/presenters/mainstream_browse_page_presenter.rb
app/presenters/tag_presenter.rb
app/presenters/topic_presenter.rb
lib/tasks/rummager.rake
spec/controllers/mainstream_browse_pages_controller_spec.rb
spec/features/mainstream_browse_pages_spec.rb
spec/notifiers/rummager_notifier_spec.rb

We'd like to use the mainstream browse pages in rummager. This PR makes collections-publisher send the content of browse pages to rummager in the same way as happened with topics.
Trello: https://trello.com/c/6vXKBd5d
PR on rummager to then hide the browse pages from search results: https://github.com/alphagov/rummager/pull/471

Send browse pages to Rummager

---

db/migrate/20150806142025_add_redirect_for_euro_case_work_topic.rb
db/schema.rb

This redirect was first created in PR #80 (fd69069).
However, the original owner wants a new location for the URL.
Trello: https://trello.com/c/Bw0pk6dI/277-add-redirect-for-european-casework-instructions
Zendesk: https://govuk.zendesk.com/agent/tickets/972973

Redirect old topic to new location

---

db/migrate/20150806150340_fix_typo_in_topic_redirect.rb
db/schema.rb

Previous commit https://github.com/alphagov/collections-publisher/pull/130 had a typo in the destination address. The topic should've redirected to
/government/collections/eea-swiss-nationals-and-ec-association-agreements-modernised-guidance.

Fix typo in topic redirect

---

db/migrate/20150811131142_fix_list_item_base_paths.rb
db/schema.rb

The contentapi URLs contained % encoded slashes. This wasn't accounted
for by the migration that replced these with base_paths, causing several
list items to show up as untagged.

Fix list item base_paths

---

app/presenters/tag_presenter.rb
spec/features/topic_create_edit_spec.rb

`phase` indicates whether the content item is in alpha or beta. By sending this attribute to the contents-store we can start to retire the `details.beta` field.

Send `phase` to content-store

---

lib/tasks/compare.rake

The task for comparing the results from rummager and content_api for
listing documents by tag was broken, because the content_api service has
been removed from the app everywhere.
It's still needed by the comparison task, so import and configure it
locally.

Fix the comparison task

---

app/controllers/mainstream_browse_pages_controller.rb
app/controllers/topics_controller.rb
app/services/tag_publisher.rb
spec/services/tag_publisher_spec.rb

During the publishing of a tag, we currently update the database and then try to send the document to the external services. When a downstream service like whitehall fails this will result in the item being `published?`, but the item will not have be sent to external services.
Calling `publish` on a published item will then result in `AASM:​:Inva​lidTr​ansit​ion: ​Event​ 'pub​lish'​ cann​ot tr​ansit​ion f​rom '​publi​shed'` exceptions. This has happened in production a couple of times, and happens often in development because a dependent app isn't running.

Wrap publishing in a transaction

---

app/presenters/tag_presenter.rb
lib/tasks/panopticon.rake
spec/presenters/mainstream_browse_page_presenter_spec.rb
spec/presenters/tag_presenter_spec.rb
spec/support/panopticon_helpers.rb

We need the `content_id` in panopticon for the new tagging infrastructure.
To make this change nice I've refactored the tests a little bit. More info in individual commits.
Trello: https://trello.com/c/IgYwT6yM

Send `content_id` to panopticon

---

lib/tasks/panopticon.rake

The current rake task only republishes published tags. Tags that are `draft` (but not `archived`) have entries in panopticon too, so there's no reason for this behaviour. It was added here: https://github.com/alphagov/collections-publisher/commit/d7db8d31d0fc3f5c4a5c5b7b1df6e0697966c76e
Trello: https://trello.com/c/IgYwT6yM

Republish all tags to panopticon

---

config/application.rb

By default, code in `/lib` isn't loaded by Sidekiq in production, because Sidekiq has disabled autoloading for reasons of thread-safety. This means we have to explicitly tell Rails to eager load things in the `/lib` directory when booting up.
https://github.com/mperham/sidekiq/wiki/FAQ#why-doesnt-sidekiq-autoload-my-rails-application-code
This fix was also made in https://github.com/alphagov/whitehall/pull/2303. It was reverted in https://github.com/alphagov/whitehall/pull/2318 because there were files in `/lib` that couldn't be eager loaded because it depended on ActiveRecord::Migration code, which Rails won't load when booting up normally. 
We don't have that problem so eager loading everything in `/lib` is safe here.
This PR supersedes …

Fix loading of `Services` module in production

---

app/services/tag_archiver.rb
spec/services/tag_archiver_spec.rb

Topics might not be present in Panopticon but we still might want to archive them.
Rescuing `GdsApi::HTTPNotFound` will allow us to continue the archiving process.

Fix bug that doesn't allow to archive topics when they're not in panopticon

---

app/models/redirect.rb
app/presenters/redirect_presenter.rb
db/migrate/20151110150858_add_content_id_to_redirect.rb
db/migrate/20151110152255_make_tag_id_not_null.rb
db/schema.rb

Redirects need their own `content_id` so that they can live in the publishing-api.
We also add `replaced_content_item` to the item. This was added in alphagov/govuk-content-schemas#142. It allows publishing-api to add special behaviour for putting back redirects.
This change was made easy by https://github.com/alphagov/collections-publisher/pull/157.
Trello: https://trello.com/c/0pcDOcMd
/cc @elliotcm

Add content_id to redirects

---

app/presenters/redirect_presenter.rb

This fits better with the actual purpose of the
field and also is more flexible for different types
of substitute items.
Also adds base paths as that has now become a requirement.

Rename `replaced_content_item` to `can_be_replaced_by`

---

app/presenters/root_browse_page_presenter.rb
app/presenters/root_topic_presenter.rb
app/presenters/tag_presenter.rb
spec/features/curating_topic_contents_spec.rb
spec/features/topic_workflow_spec.rb

This field contains the parent topic/browse page, so that we can display a sorted list of tags in tagging interfaces.
The field is added in https://github.com/alphagov/govuk-content-schemas/pull/156.
This is needed to create the tagging interface: https://trello.com/c/XwVC0IM8

Send a internal_name to the content-store

---

app/models/redirect_item.rb
app/presenters/redirect_item_presenter.rb
app/services/redirect_publisher.rb
db/migrate/20151204133010_create_redirect_items.rb
db/migrate/20151204140913_add_redirect_items.rb
db/schema.rb
lib/tasks/publishing_api.rake
spec/factories.rb
spec/presenters/redirect_item_presenter_spec.rb
spec/services/redirect_publisher_spec.rb

Collections-publisher currently sends invalid content-items to the publishing-api. This is because some tags have redirect-routes that don't "belong" to the tag. Eg, they have a path that doesn't start with the tag's `base_path`:
For example:
https://collections-publisher.preview.alphagov.co.uk/topics/4505d908-89f2-4322-956b-29ac243c608b
Has a redirect for `/benefits-credits`
This is illegal because `/benefits-credits` is not under the tag's base path, `/topic/benefits-credits`.
`/topic/benefits-credits/yolo` would still be legal.
This PR adds a table that we can populate with these redirects. When running the rake task, they will be sent independently, as full redirect content-items to the publishing-api.
Note:
- The functionality introduced in …

Solve content-items having invalid redirects

---

Gemfile
Gemfile.lock
app/controllers/taxons_controller.rb
app/forms/create_taxon.rb
app/services/taxonomy/taxon_fetcher.rb
app/views/layouts/application.html.erb
app/views/taxons/edit.html.erb
app/views/taxons/index.html.erb
app/views/taxons/new.html.erb
config/routes.rb
spec/features/taxonomy_manager_spec.rb

This PR adds a section to this app where users can manage the "alpha taxonomy". Basically it is editor to create and update content items with format "taxon". It allows users to select a `parent` (also a "taxon") that will be used to construct a hierarchy of taxons.
Because the publishing-api doesn't return the `links` hash for content-items, it is currently not performant to show the hierarchy on the index page. This might be added later.
There is also no validation yet on the position of the `parent` - a taxon can be its own parent, or be the parent of a descendent (a loop). We are assuming that we don't need this currently, as access to this
taxonomy will be restricted (GDS editors only).
List taxons:
Create a new one:
Trello: https://trello.com/c/bsZAwZ35

Allow users to edit alpha taxonomy

---

app/controllers/application_controller.rb
app/controllers/taxons_controller.rb
app/views/layouts/application.html.erb
spec/features/taxonomy_manager_spec.rb

Only people with the `Edit Taxonomy` permission should be able to edit the taxonomy. This will prevent regular GDS Editors from seeing it.
https://trello.com/c/1Sp00cFo

Restrict editing taxons

---

app/forms/create_taxon.rb
spec/features/taxonomy_manager_spec.rb

Previously we thought we could build the prototype from the draft content-store. We didn't think about that not being available outside the GOV.UK network. Therefore we will be publishing the taxons automatically.
The collections app will start serving 404's for these pages.
Trello: https://trello.com/c/bsZAwZ35/450-improve-alpha-taxonomy-tagging

Publish taxons on create and update

---

Gemfile
Gemfile.lock
app/presenters/root_browse_page_presenter.rb
app/presenters/root_topic_presenter.rb
app/presenters/tag_presenter.rb
spec/presenters/archived_tag_presenter_spec.rb
spec/presenters/mainstream_browse_page_presenter_spec.rb
spec/presenters/root_browse_page_presenter_spec.rb
spec/presenters/topic_presenter_spec.rb
spec/support/govuk_content_schemas.rb

The V2 content schemas differ a little bit from V1 (no content_id, update_type). This commit makes the examples validate against `publisher_v2`.
https://trello.com/c/catWOsWC

Use V2 content schemas

---

Gemfile
Gemfile.lock
spec/controllers/topics_controller_spec.rb
spec/features/archiving_tags_spec.rb
spec/features/browse_hierarchy_spec.rb
spec/features/curating_topic_contents_spec.rb
spec/features/managing_browse_pages_spec.rb
spec/features/managing_topic_pages_spec.rb
spec/features/tagging_browse_with_topics_spec.rb
spec/services/tag_archiver_spec.rb
spec/support/common_feature_steps.rb
spec/support/publishing_api_helpers.rb

Many stubs used here are not necessary anymore since gds-api-adapters has learned new methods:
https://github.com/alphagov/gds-api-adapters/blob/master/lib/gds_api/test_helpers/publishing_api_v2.rb
This will make it easier for developers to switch between projects.

Use stubbing from gds-api-adapters

---

app/controllers/taxons_controller.rb
app/forms/taxon_form.rb
app/services/taxonomy/taxon_fetcher.rb
spec/features/curating_topic_contents_spec.rb
spec/features/taxonomy_manager_spec.rb

- Check if a links>parent value is available before attempting to assign
the attribute in the form object.
- Move all logic around instantiating the taxon form object into a
factory method on TaxonForm.
Fixes bug decribed in: https://trello.com/c/biyzQj52

Update taxon form object to gracefully handle taxons with blank links

---

spec/features/curating_topic_contents_spec.rb
spec/support/wait_for_ajax.rb

There's a race condition in the curation JS. When an item is dragged to
a list, it is 'reindexed' - if the item is newly placed, a ListItem is
created. If the item is reordered, the ListItem is updated.
When two drag and drops happen in quick succession (like they do in the
specs), a given item can be 'created' twice resulting in duplicate
entries in the list.
Until we solve this definitively in the client, this change is a band aid to
ensure that, when executing a drag and drop, the spec waits for the ajax
request to complete before continuing.

Add wait_for_ajax helpers to prevent intermittently breaking topic curation feature

---

Gemfile
Gemfile.lock

This commit upgrades Sidekiq to 3.5.4, the latest version in the 3.X series (4.0 has come out a few months ago). It is necessary to upgrade because there are a couple of vulnerabilities reported in 2.X.
These issues were found by [bundler-audit](https://github.com/alphagov/govuk_security_audit):
```
~/govuk/ft-audit  ᐅ bundle exec govuk_security_audit github alphagov collections-publisher master         
Updating ruby-advisory-db ...
From https://github.com/rubysec/ruby-advisory-db
* branch            master     -> FETCH_HEAD
Current branch master is up to date.
ruby-advisory-db: 262 advisories
Name: sidekiq
Version: 2.17.8
Advisory: 125675
Criticality: Unknown
URL: https://github.com/mperham/sidekiq/pull/2422
Title: Sidekiq Gem for Ruby Multiple Unspecified CSRF
Solution: upgrade to >= …
```

Upgrade Sidekiq to 3.X

---

docs/adr-001-defer-merging-of-taxonomy-apps.md

Add an ADR that clarifies the roles of the two apps chiefly responsible
for handling taxonomy data, and summarises a decision to defer any
attempt at merging/co-locating this functionality.
Trello: https://trello.com/c/GpUgdlgL

Architecture Decision Record - Defer Merging of Taxonomy Apps

---

Gemfile
Gemfile.lock

4.3.5 looks compatible with Sidekiq 3.0. We can't yet upgrade to Airbrake 5.X, because it requires a `project_id` to be set, which errbit doesn't seem to provide.
@mobaig

Downgrade Airbrake

---

app/forms/taxon_form.rb
app/notifiers/publishing_api_notifier.rb
app/presenters/archived_tag_presenter.rb
app/presenters/redirect_item_presenter.rb
app/presenters/root_browse_page_presenter.rb
app/presenters/root_topic_presenter.rb
app/presenters/tag_presenter.rb
app/services/draft_tag_remover.rb
spec/presenters/archived_tag_presenter_spec.rb

Setting the update type to minor means we won't send email alerts for changes to a topic title or description. This will become relevant if topics will be tagged to other topics (we have no plans to do this, but we need to be careful).
Since there is only ever one update type, all methods have been replaced by a constant.
The only change is in the `RedirectItemPresenter` which previously was sent with a "republish" update type. This was incorrect, as the app is publishing new data, [not republishing old data](https://github.com/alphagov/publishing-api/blob/d5f63c13497147d7f366ef3c02e0439c4cf18300/doc/semantics-of-the-publishing-api.md#update_type).
Related: https://github.com/alphagov/content-tagger/pull/25
Trello: https://trello.com/c/GRt7NSbL

Use "minor" update type for tag publishing

---

Gemfile
Gemfile.lock
app/forms/taxon_form.rb
app/notifiers/publishing_api_notifier.rb
app/services/taxonomy/taxon_fetcher.rb
spec/features/browse_hierarchy_spec.rb
spec/features/curating_topic_contents_spec.rb
spec/features/managing_browse_pages_spec.rb
spec/features/managing_topic_pages_spec.rb
spec/features/taxonomy_manager_spec.rb
spec/services/taxonomy/taxon_fetcher_spec.rb
spec/support/content_store_helpers.rb

Paired with @steventux on this! 
Switches the datasource for populating drop downs to the v2 linkable endpoint. Further description can be found [here on Trello](https://trello.com/c/2kHBXfOd/618-modify-collections-publisher-to-use-linkables-endpoint).

Use linkables endpoint

---

lib/services.rb

This caching is almost never wanted because this is a publishing application and we want to most up-to-date information possible.
@mobaig

Stop gds-api-adapters caching

---

app/controllers/taxons_controller.rb

When I edit a taxon, :back sends me back to the form itself, so
its not obvious whether anything happened. This change makes
create and update do the same thing, i.e. redirect back to the list.
This also makes it easier to edit multiple taxons at once.

Redirect to taxon list after updating a taxon

---

app/presenters/tag_presenter.rb
spec/notifiers/rummager_notifier_spec.rb

Rummager needs to have a `content_id` for easier lookups.
Trello: https://trello.com/c/ppe8Upar

Send `content_id` to Rummager

---

Gemfile
Gemfile.lock
app/workers/dependent_tag_publish_worker.rb
app/workers/worker_base.rb
config/application.rb
spec/notifiers/publishing_api_notifier_spec.rb

https://trello.com/c/Eddv2AiS/688-for-migrated-formats-update-for-request-tracing
This change makes it so that a request_id is passed into Sidekiq jobs so that we can send this as a header downstream, via GdsApi::GovukHeaders. Currently, this header is lost when the Sidekiq jobs run because they run in a separate process to the one in which the request was processed.
This is based on this pull request: alphagov/whitehall#2567

Request tracing

---

app/models/tagged_documents.rb
lib/tasks/compare.rake
spec/models/tagged_documents_spec.rb

Rummager will refuse to return more than 1000 documents since https://github.com/alphagov/rummager/pull/634. This makes collections-publisher respect that limit.
Fixes:
https://errbit.integration.publishing.service.gov.uk/apps/53da383a0da11520d8004bb3/problems/572232616578637430910000

Request less documents from rummager

---

app/models/list_item.rb
app/models/tag.rb
app/views/lists/_all_list_items.html.erb
app/views/lists/_list_editor.html.erb
app/views/shared/tags/_curated_links_preview.html.erb
spec/features/curating_topic_contents_spec.rb
spec/features/tagging_browse_with_topics_spec.rb
spec/models/list_item_spec.rb
spec/support/common_feature_steps.rb
spec/support/rummager_helper.rb

Item titles for display in collections-publisher are currently looked up from data
persisted to the mysql db at list curation time.
This is not consistent with the collections frontend, which looks up titles from rummager.
It is possible for an item to appear in a curated list but to since have had its tag removed
or been deleted. In this case the collections frontend doesn't display the item.
Also, it is possible for a content item to have been renamed since it was included in a
curated list. It can then be added again under its new title.
In this case, collections-publisher will display two items which, while pointing to the
same base_path, appear different becase the persisted titles are different.
Collections frontend will display both items using the most recent title from rummager, …

Fix curated list item titles

---

app/forms/taxon_form.rb
app/presenters/root_browse_page_presenter.rb
app/presenters/root_topic_presenter.rb
app/presenters/tag_presenter.rb
app/presenters/taxon_presenter.rb
spec/features/managing_browse_pages_spec.rb
spec/features/managing_topic_pages_spec.rb
spec/presenters/mainstream_browse_page_presenter_spec.rb
spec/presenters/taxon_presenter_spec.rb
spec/presenters/topic_presenter_spec.rb

The `format` field is deprecated and should not be used anymore.
Includes some new schema testing for the taxons.

Use `document_type` and `schema_name`

---

app/presenters/root_topic_presenter.rb

The `phase` attribute was added after this content item code was written, so it used a older `details.beta` attribute. If we start using `phase` here, we can convert collections to use this attribute and remove some data duplication.

Properly send document state to publishing-api

---

app/presenters/root_browse_page_presenter.rb
app/presenters/taxon_presenter.rb
jenkins-schema.sh
lib/tasks/rspec.rake
spec/notifiers/publishing_api_notifier_spec.rb
spec/presenters/mainstream_browse_page_presenter_spec.rb
spec/presenters/tag_presenter_spec.rb
spec/presenters/topic_presenter_spec.rb

When a new PR is made on govuk-content-schemas, the Jenkins task runs `./jenkins-schema.sh`. This test task's purpose is to run a subset of all tests that interact with the schemas. This is done so that govuk-content-schema tests run faster.
The problem is that for this to happen, the developer needs to tag schema tests with `schema_test: true`. This is error prone, and we currently have multiple schema tests that aren't triggered by jenkins.
This causes an annoying thing where a govuk-content-schemas PR is merged that makes the tests (on master) for this repo fail.
To prevent this from happening again, we choose here to run _all_ the tests. This causes wasted CPU cycles, but I'm of the opinion that that's an acceptable loss compared to potential bugs not being caught
by CI. Especially …

Fix schema tests 

---

app/controllers/application_controller.rb
app/workers/worker_base.rb
spec/workers/worker_base_spec.rb

https://trello.com/c/6nDCqZXi/729-user-id-into-event-log
Events logged in the publishing API should contain the uid present in the x_govuk_authenticated_user header. So ensure that the header is populated for each request and that the header is repopulated in any Sidekiq worker processes.

Set authenticated user header in sidekiq work

---

app/presenters/mainstream_browse_page_presenter.rb
spec/presenters/mainstream_browse_page_presenter_spec.rb

content-store does not retain the order of the items that are sent in the links
hash, therefore in order to allow custom 2nd level browse pages ordering we
have to read the links order from the details hash.
Deploy and run rake task to republish all items pages/tags before merging and deploy:
https://github.com/alphagov/collections/compare/sort-2nd-level-browse-pages
Depends on: https://github.com/alphagov/govuk-content-schemas/pull/343
paired on it with @rubenarakelyan

Send 2nd level browse pages in the details hash

---

app/services/tag_republisher.rb

This is so that I do not have to ssh into a machine to read the logs, the change will allow me to read them on Jenkins or via the console from which I am running the rake task

Print rake task logs

---

config/initializers/airbrake.rb
config/initializers/gds-sso.rb

Currently alphagov-deployment overwrites the airbrake.rb initializer ([here](https://github.gds/gds/alphagov-deployment/blob/18873afa146b334326b5804
3b758bff84a906b96/collections-publisher/initializers_by_organisation/pro
duction/airbrake.rb)).
We're moving to a 12 factor model, using environment variables to set configuration. This commit adds a default airbrake initializer (taken from [govuk-rails-app-template](https://github.com/alphagov/govuk-rails-app-template/blob/master/templates/config/initializers/airbrake.rb)).
Next we'll update govuk-puppet and alphagov-deployment.
Trello: https://trello.com/c/dKfYzDNx

Add 12-factor Airbrake & gds-sso config

---

config/secrets.yml

We will use this later, so that we don't have to overwrite secrets.yml from the alphagov-deployment repo.
https://trello.com/c/dKfYzDNx

Add SECRET_KEY_BASE for production

---

app/assets/stylesheets/forms.scss
app/assets/stylesheets/topics.scss
app/controllers/mainstream_browse_pages_controller.rb
app/controllers/topics_controller.rb
app/forms/mainstream_browse_page_archival_form.rb
app/forms/topic_archival_form.rb
app/presenters/tag_presenter.rb
app/services/tag_archiver.rb
app/views/mainstream_browse_pages/_redirects.html.erb
app/views/mainstream_browse_pages/archived_browse_page.html.erb
app/views/mainstream_browse_pages/propose_archive.html.erb
app/views/mainstream_browse_pages/show.html.erb
config/routes.rb
spec/features/archiving_mainstream_browse_page_tags_spec.rb
spec/features/archiving_topic_tags_spec.rb
spec/forms/mainstream_browse_page_archival_form_spec.rb
spec/forms/topic_archival_form_spec.rb

Currently, Collections Publisher allows users to archive or delete topics that are no longer required, but does not allow the same functionality with mainstream browse pages. The underlying functionality to do this exists in the Publishing API but is not exposed here.
This commit adds the user-facing functionality to allow mainstream browse pages to be deleted (if they have not yet been published) or archived and redirected (if they have already been published). The user experience is identical to archiving/deleting topics.
Paired with @jackscotti 
Trello: https://trello.com/c/olZEBaef/67-make-it-possible-to-redirect-browse-pages-in-collections-publisher
Unpublished mainstream browse page has a "remove" button:
Published mainstream browse page has an "archive" button:
Archiving a …

Add browse page archiving

---

app/helpers/application_helper.rb
app/models/list_item.rb
app/models/tagged_documents.rb
app/views/shared/tags/_curated_links_preview.html.erb
app/views/shared/tags/_uncurated_links_preview.html.erb
spec/features/curating_topic_contents_spec.rb
spec/features/navigating_browse_pages_spec.rb
spec/features/navigating_topics_spec.rb

To make it easier to remove the tags from the content.
Feel free to highlight how bad my HTML is, might learn something new!
https://trello.com/c/j0AgxRd5/74-collections-publisher-should-link-to-content-tagger-for-topic-links

Link tagged documents to Content Tagger

---

app/presenters/tag_presenter.rb
app/presenters/topic_presenter.rb
spec/presenters/mainstream_browse_page_presenter_spec.rb

This application currently does not send the `parent` in the links for browse pages, but it does for topics. This commit moves the parent (or children) code up to the superclass so topic and browse pages act the same.
Having the parent in the links will allow us to render the breadcrumb from the content-store in collections.
https://trello.com/c/xvM9vb5L
After this is deployed we need to run the rake task that re-sends all content to the publishing-api.

Send browse page parent tag to publishing-api

---

app/views/layouts/application.html.erb

I believe it is now common knowledge that Taxons are managed in
`content-tagger`, so there is no need to keep this link here.

Remove link to Taxons

---

spec/features/browse_hierarchy_spec.rb
spec/features/curating_topic_contents_spec.rb
spec/features/managing_browse_pages_spec.rb
spec/features/managing_topic_pages_spec.rb

In https://github.com/alphagov/collections-publisher/pull/173 I refactored the tests to use test helpers from gds-api-adapters. In doing that I replaced the `assert_publishing_api_put_item` method calls with `stub_publishing_api_put_content ` which doesn't assert anything.
https://trello.com/c/C8A9bnuO/344-work-on-making-the-document-type-concept-clearer

Fix test assertions in integration test

---

app/presenters/archived_tag_presenter.rb
app/presenters/redirect_item_presenter.rb
spec/presenters/archived_tag_presenter_spec.rb

`format` has been deprecated.
https://trello.com/c/C8A9bnuO/344-work-on-making-the-document-type-concept-clearer

Use document_type & schema_name

---

app/controllers/list_items_controller.rb
app/controllers/lists_controller.rb
app/controllers/mainstream_browse_pages_controller.rb
app/helpers/icon_helper.rb
app/models/tag.rb
app/notifiers/content_item_publisher.rb
app/presenters/mainstream_browse_page_presenter.rb
app/presenters/redirect_item_presenter.rb
app/presenters/root_browse_page_presenter.rb
app/presenters/topic_presenter.rb
app/services/tag_archiver.rb
app/workers/dependent_tag_publish_worker.rb
bin/rails
config.ru
config/application.rb
db/migrate/20150623122832_add_published_groups_to_tags.rb
db/migrate/20150713124417_import_router_data_browse_redirects.rb
db/migrate/20150714140302_import_router_data_topic_redirects.rb
db/migrate/20150716103715_remove_unused_mainstream_browse_pages.rb
db/migrate/20151124153356_add_tag_id_to_redirect_routes.rb
spec/factories.rb
spec/features/curating_topic_contents_spec.rb
spec/features/order_browse_pages_spec.rb
spec/notifiers/rummager_notifier_spec.rb
spec/presenters/groups_presenter_spec.rb
spec/presenters/mainstream_browse_page_presenter_spec.rb
spec/presenters/tag_presenter_spec.rb
spec/presenters/topic_presenter_spec.rb
spec/services/list_publisher_spec.rb
spec/support/wait_for_ajax.rb

This is in preparation for migrating the build to Jenkins 2. Jenkins 2 will require us to add new build scripts which could optionally include Rubocop linting, so this seems like a convenient point to add linting to this project.
All the Rubocop errors were trivial, and most could be fixed automatically.
I'll comment on the two manual fixes in case you want to look at those in more detail.

Fix all Rubocop linter warnings

---

Jenkinsfile

Unlike dev branches, the 'released-to-production' branch should not be built when the branch is updated. The only reason to build it is to test it against changes to the content schemas.
This change adds Jenkins configuration which distinguish between updates to 'released-to-production' (in which case Jenkins should do nothing) and builds triggered by the content schema build (in which case, run the build as normal, but check out the correct content schema branch.
The govuk-content-schemas Jenkins config will be updated to trigger this build, and it will provide an 'IS_SCHEMA_TEST' parameter to identify it as a schema test.

Only build 'released-to-production' branch to test content schemas

---

Jenkinsfile

The branch check for distinguishing between regular branch builds and schema test builds has been extracted to the shared helper file, so replace these checks with a call to the shared function.
https://trello.com/c/S4DZbsPa/285-jenkins-2-migration

Simplify Jenkins schema build check using helper functions

---

Jenkinsfile

This is a work-around for Jenkins bug JENKINS-40574, where parameters are not set on the very first build of a pipeline job.
https://trello.com/c/S4DZbsPa/285-jenkins-2-migration

Ensure Jenkins build parameters are set

---

jenkins-schema.sh
jenkins.sh

The contents of these scripts have been migrated to the Jenkinsfile.
These were not safe to delete until now because they were still used to test the content schemas on Jenkins 1, but those tests have now also been migrated to Jenkins 2.
https://trello.com/c/S4DZbsPa/285-jenkins-2-migration

Delete old Jenkins shell scripts

---

app/controllers/topics_controller.rb
app/helpers/status_helper.rb
app/presenters/root_topic_presenter.rb
app/presenters/tag_presenter.rb
app/presenters/topic_presenter.rb
app/views/shared/tags/_table.html.erb
app/views/topics/edit.html.erb
app/views/topics/new.html.erb
spec/features/curating_topic_contents_spec.rb

Topic pages are no longer in beta, and they will be deprecated soon when the new taxonomy-based navigation is added. This means that the 'beta' tag is out-of-date, and can be deleted.
The 'beta' tag is not relevant to browse pages either, so all references have been removed from the code.
New topics will be created with default values for properties related to 'beta' content. This currently means that they will be created in the 'live' phase, and with no 'beta' property in 'details'.
https://trello.com/c/oW7gSMoB/328-remove-beta-tags-from-topics-in-collections
A few things I'm not sure of:
- Is it OK that if you update an existing beta topic, it removes the `beta` property in the `details` section? Or do we need to preserve those for existing topics?
- There's still a `beta` column in the …

Delete all 'beta' messages from topics

---

db/migrate/20170117160733_remove_beta_from_tags.rb
db/schema.rb

The 'beta' flag was removed from the rest of the codebase in a previous commit. This cleans up the now-unused field from the DB.
The only kinds of content edited in collections-publisher are topics and browse pages. Topics are no longer in beta and browse pages never were, so it's safe to remove the beta flag data entirely.
https://trello.com/c/oW7gSMoB/328-remove-beta-tags-from-topics-in-collections

Delete 'beta' flag from tags in DB

---

Jenkinsfile

- Explicitly check that the branch is `master` before tagging the build and deploying to Integration. This is already done by the Jenkinsfile helper, but this makes it more obvious that deployment only happens on `master`.
- Wrap the Integration deployment in a pipeline stage, since this definition has been removed from the `deployIntegration` helper since this project's Jenkinsfile was created.

Fix CI deployment pipeline stages

---

app/presenters/tag_presenter.rb
spec/notifiers/rummager_notifier_spec.rb
spec/services/tag_republisher_spec.rb

Finding Things has been working into adding a new field in rummager
called `content_store_document_type`.
This commit addds that field into rummager and also updates the spec to
test the output to stdout and avoid having it displayed when tests run.
Trello:
https://trello.com/c/iMotNdUv/461-add-more-document-type-to-search

Add content_store_document_type to be sent to rummager.

---

app/models/tag.rb
app/views/mainstream_browse_pages/manage_child_ordering.html.erb

This commit excludes archived mainstream browse pages from being shown on the “manage child ordering” page, since ordering them does not make sense.
It also adds the name of the child pages above each text box, along with the existing slug.
Trello: https://trello.com/c/D3TtciUU/227-withdrawn-child-pages-showing-in-ordering-view-in-collections-publisher
Before:
After:

Exclude archived child pages from child ordering page

---

.gitignore

This prevents errors like "No such file or directory @ rb_sysopen - ./log/sidekiq.json.log" when you start collections-publisher.

Add log directory

---

Gemfile
Gemfile.lock
app/notifiers/content_item_publisher.rb
app/presenters/archived_tag_presenter.rb
app/presenters/redirect_item_presenter.rb
app/presenters/root_browse_page_presenter.rb
app/presenters/root_topic_presenter.rb
app/presenters/tag_presenter.rb
spec/presenters/archived_tag_presenter_spec.rb

Sending it on publish has been deprecated in favour of including it when sending a put content.
[Trello Card](https://trello.com/c/LnJlkb9e/987-5-deprecate-the-usage-of-updatetype-in-publish-for-publishing-api-and-update-usage-across-govuk)

Send update type with put content

---

README.md

The task to run just the schema specs was removed in:
https://github.com/alphagov/collections-publisher/commit/322deafd0a9214dd73968abc3c9b81beebb4b4f7

Remove schema specs info from README

---

app/presenters/archived_tag_presenter.rb
app/presenters/redirect_item_presenter.rb
spec/presenters/archived_tag_presenter_spec.rb

This removes legacy content_ids from the payloads to Publishing API.
These do not currently throw a schema error because the schema is
incorrect:
https://github.com/alphagov/govuk-content-schemas/blob/04ce3f8bbba0f205f65354f8173718e67fa18834/formats/redirect/publisher_v2/schema.json#L16-L18
This is being fixed to try help merge in correct schemas.

Remove content_ids from redirect presenters

---

lib/tasks/publishing_api.rake

This commit aims to publish the route /learn-to-drive-a-car into
publishing-api.
This will be where the `task list` page for `learning to drive a car` will live within GOV.UK.
We talked with the search team and this seems to be the best way to
integrate this page with search later on.
Trello:
https://trello.com/c/WOhDbn9e/208-publish-route-for-the-task-list-page

Publish route for learn to drive task list page

---

lib/tasks/publishing_api.rake

We've specified a meta description on the [task list page](https://github.com/alphagov/collections/blob/d2e95a7c052be9982b8d07eff0ea7de6384f1510/app/views/tasklist/show.html.erb#L4), so we want to make this consistent.
https://trello.com/c/wAMac6Dz/282-update-task-list-description-in-publishing-api

Update task list page description

---

Jenkinsfile

This will allow us to run the tests defined in the [E2E project](https://github.com/alphagov/publishing-e2e-tests) for collections publishing to ensure that publishing between applications still works when changes are made to this repo

Enable the end-to-end tests for collections publisher

---

lib/tasks/publishing_api.rake

This rake task publishes the route /end-a-civil-partnership into the publishing-api.
This is where the `task_list` page for `End a civil partnership: step by step` will live within GOV.UK.
Trello card: [Set up base path for /end-a-civil-partnership](https://trello.com/c/tSICJj1j)

Publish route for end a civil partnership task list page

---

lib/tasks/publishing_api.rake

This rake task publishes the route `/get-a-divorce` into the publishing-api.
This is where the `task_list` page for `Get a divorce: step by step` will live within GOV.UK.
Trello card: [Set up base path for /get-a-divorce task list page](https://trello.com/c/YYpdSq7E/)

Publish route for get a divorce task list page

---

Gemfile.lock

Hey :wave:
This is needed by the E2E tests to run signon in mock mode while collections-publisher runs in production.

Upgrade gds-sso to latest version

---

config/initializers/logstasher.rb

This is defined in govuk_app_config [1] and is no longer needed on a
per-application basis.
[1] https://github.com/alphagov/govuk_app_config/blob/master/lib/govuk_app_config/govuk_logging.rb#L26-L36

Remove duplicate logstasher initializer

---

lib/tasks/publishing_api.rake

The Modelling Services team are renaming the `document_type` from `task_list` to `step_by_step_nav` as the term `task list` has already been used to define something else.

 Rename rake tasks to use updated document_type name

---

lib/tasks/step_nav/learn_to_drive_a_car.rake

Set the correct step logic to allow for the concurrent step.
Add the new title and introduction fields to allow us to render the enter step by step nav page from content store (added in https://github.com/alphagov/govuk-content-schemas/pull/720)
https://trello.com/c/3pQPJDmj/440-allow-collections-to-render-task-lists-from-the-publishing-api

Update learn to drive

---

app/controllers/step_by_step_pages_controller.rb
app/views/layouts/application.html.erb
app/views/step_by_step_pages/index.html.erb
config/routes.rb
spec/controllers/step_by_step_pages_controller_spec.rb

The Modelling Services team are working on implementing the Step by Step pages into the publisher.
We want to be able to develop features and deploy them without affecting the workflow already in place.
Users with GDS editor permissions should be able to see the `Step by step pages` link next to `Topics`.
Trello Card: [Step by Step Page behind access permissions](https://trello.com/c/LjXNfJg1/504-step-by-step-page-behind-access-permissions)

 Set up access permissions for Step by Step pages

---

lib/tasks/step_nav/learn_to_drive_a_car.rake

The schema has changed to allow [introduction to be markdown](https://github.com/alphagov/govuk-content-schemas/blob/master/examples/step_by_step_nav/publisher_v2/learn_to_drive_a_car.json#L26)

Update learn to drive with new schema

---

.rubocop.yml
Gemfile.lock
app/models/step_by_step_page.rb
db/migrate/20180219165923_create_step_by_step_pages.rb
db/schema.rb
spec/factories.rb
spec/models/step_by_step_page_spec.rb

The Modelling Services team are implementing the `Step by step` publishing tool into Collections Publisher.
We want to store `Step by step` content in the database, and use the data to generate the json content we want to send as part of the payload to `publishing_api`.
A second PR is required after ths one to add the `Step` model, which will have a `belongs_to` relationship with the `StepByStepPage` model.
Trello card: [Allow Step by Step Pages to be stored in Collections Publisher](https://trello.com/c/oZX9zHNf/506-allow-step-by-step-pages-to-be-stored-in-collections-publisher)

Add new StepByStepPage model

---

app/models/step_by_step_page.rb

The current format regex for the `base_path` does not accept a single word. This has now been updated.
This is part of https://github.com/alphagov/collections-publisher/pull/320

Update StepByStep validation

---

Gemfile
Gemfile.lock
app/models/step.rb
app/models/step_by_step_page.rb
db/migrate/20180221152119_create_steps.rb
db/schema.rb
spec/factories.rb
spec/models/step_by_step_page_spec.rb
spec/models/step_spec.rb
spec/rails_helper.rb

The Modelling Services team are implementing the Step by step publishing tool into Collections Publisher.
The `StepByStepPage` model has already been created in this pr: https://github.com/alphagov/collections-publisher/pull/320
This PR creates the `Step` model, which has a `belongs_to` relationship with `StepByStepPage`.
Trello card: [Allow Step by Step Pages and Steps to be stored in Collections Publisher](https://trello.com/c/oZX9zHNf/506-allow-step-by-step-pages-and-steps-to-be-stored-in-collections-publisher)

Add new Step model

---

app/models/step_by_step_page.rb
spec/models/step_by_step_page_spec.rb

The Modelling Services team are implementing the Step by step publishing tool into Collections Publisher.
We want to ensure that the `Steps` for a `StepByStepPage` are returned in ascending order.
This PR addresses the comment in: https://github.com/alphagov/collections-publisher/pull/324#pullrequestreview-99604806

Add position order of Steps

---

app/services/step_content_parser.rb
spec/services/step_content_parser_spec.rb

We want to allow free text specification of step by step navigation content using markdown-like syntax.
At present this is:
```
single line of text for a paragraph
- [A link in a standard list](/a-link)
- [Another link](/another-link)
* [A link in a bulleted list](/a-link)
* [Another link](/another-link)
```
You can optionally add text after the link which is parsed as a `context` item.
These get parsed into the format that the [step by step nav component](https://government-frontend.herokuapp.com/component-guide/step_by_step_nav)
expects.
https://trello.com/c/FU7WB1dX/481-spike-find-a-way-to-parse-markdown

Parse simple step nav content

---

lib/tasks/step_nav/learn_to_drive_a_car.rake

This patches links on all the learn to drive a car related content so that a reverse link to the step by step navigation page is set up.
This allows us to move away from hard coded navigation configuration.
The "missing" items in the array are pages in guides that we think of as related, but don't have their own content ID.  They're included to avoid confusion until the publishing tool can cope.
https://trello.com/c/nhjWvdTN/535-update-govukpublishingcomponents-to-read-sidebar-nav-data-from-links-data

Set up learn-to-drive step nav links

---

lib/tasks/step_nav/learn_to_drive_a_car.rake

We list the fee for applying for a provisional as £34. This is the fee to apply online; the fee to apply by post is £43.
https://trello.com/c/H77MJZRD/477-change-fee-for-apply-for-a-provisional-licence

Update cost of provisional driving

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/step_by_step_pages_controller.rb
app/models/step_by_step_page.rb
app/views/step_by_step_pages/_form.html.erb
app/views/step_by_step_pages/index.html.erb
db/migrate/20180302155853_add_content_id_to_step_by_step_pages.rb
db/migrate/20180302165039_rename_step_by_step_base_path_to_slug.rb
db/schema.rb
spec/factories.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/models/list_spec.rb
spec/models/step_by_step_page_spec.rb
spec/support/authentication.rb
spec/support/factory_girl.rb

This commit introduces the `content_id` to all the step by step pages.
Renames base_path to slug.
It also fixes some linting problems and a typo.

Add content id to step by step pages

---

app/assets/stylesheets/steps.scss
app/helpers/step_helper.rb
app/views/shared/steps/_form_errors.html.erb
app/views/shared/steps/_heading.html.erb
app/views/shared/steps/_markdown_help.html.erb
app/views/shared/steps/_page_title.html.erb
app/views/shared/steps/_step_breadcrumb.html.erb
app/views/step_by_step_pages/_form.html.erb
app/views/step_by_step_pages/edit.html.erb
app/views/step_by_step_pages/index.html.erb
app/views/step_by_step_pages/new.html.erb
app/views/step_by_step_pages/show.html.erb
app/views/steps/_form.html.erb
app/views/steps/edit.html.erb
app/views/steps/new.html.erb

These are some smaller frontend improvements to the step by step navigation publisher:
- Make titles and breadcrumbs more consistent
- Add unique page titles to every page
- Improve content of Markdown example snippet
- Make format of slugs clearer
- Add defaults for likely step options
- Hide optional step help section, show when needed
- Improve guidance links for step nav
- Fix breadcrumbs showing when empty
- Remove duplication and unnecessary complexity from form errors

Step nav frontend improvements

---

app/services/step_content_parser.rb
spec/services/step_content_parser_spec.rb

We want to accommodate content designers to continue writing their markdown
the same way was they have so far with Govspeak.
This means that both `-` and `*` can be used to indicate bulleted links and also accommodates when publishers want to use bullet points without any links (just text).
It also removes LINK_CAPTURE_REGEX constant to
enable taking advantage of named capture groups in regular expressions
to use named backreferences. This is possible when the regular
expression is on the left hand side of the operator `=~`, by doing so it
assigns the captured text to local variables with the corresponding
names. [Regex Docs](https://ruby-doc.org/core-2.1.1/Regexp.html)
Trello: https://trello.com/c/2zhfNYfj

Handle bullets in the publisher tool markdown to align it with govspeak

---

app/controllers/step_by_step_pages_controller.rb
app/controllers/steps_controller.rb
app/presenters/step_nav_presenter.rb
app/services/step_nav_publisher.rb
spec/factories.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/features/managing_steps_spec.rb
spec/models/step_by_step_page_spec.rb
spec/presenters/step_nav_presenter_spec.rb
spec/services/step_nav_publisher_spec.rb
spec/support/step_nav_steps.rb

I've added a bunch of tests to the existing step by step pages and steps so that we can ensure we're covered on this.
I think we'll refactor the step tests soon to make use of shared steps a bit more, but we need to get this stuff in master soon as we've got too many branches in flight.

Send step by step drafts to publishing api 

---

app/services/step_content_parser.rb
spec/services/step_content_parser_spec.rb

Currently it was not accounting for "\r" endings.
This commit fixes that and adds a test for it.
Trello: https://trello.com/c/28INLtX8/552-markdown-parser-to-handle-new-line-endings

StepContentParser handle new line endings

---

app/models/step_by_step_page.rb
app/validators/slug_validator.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/models/step_by_step_page_spec.rb
spec/models/step_spec.rb
spec/presenters/step_nav_presenter_spec.rb
spec/services/step_nav_publisher_spec.rb
spec/support/step_nav_steps.rb

The Modelling Services team have been working on implementing the `Step by step` publishing tool.
To prevent users from creating slugs that have already been taken, we are using the SlugValidator as part of our validations on the `StepByStepPage` model. 
Trello card: [Add SlugValidator in Collections Publisher](https://trello.com/c/daxHC9M9/549-add-slugvalidator-in-collections-publisher)

Add SlugValidator to StepByStepPage model

---

app/presenters/step_nav_presenter.rb
app/services/step_content_parser.rb
app/services/step_nav_publisher.rb
spec/presenters/step_nav_presenter_spec.rb
spec/services/step_content_parser_spec.rb
spec/services/step_nav_publisher_spec.rb
spec/support/step_nav_steps.rb

This parses base_paths from step content, looks up content_ids using the
publishing-api endpoint, and then uses these to add pages_part_of_step_navs
edition links as part of the presenter.
We'll review the publishing api communication in due course, as I suspect we'll
need to move some of it to sidekiq workers.
https://trello.com/c/pKrmHkDr/551-handle-editionlinks

Send step nav edition links to publishing-api

---

app/helpers/application_helper.rb
app/views/step_by_step_pages/index.html.erb
app/views/step_by_step_pages/show.html.erb

This commit allows Content designers to preview new navigation before publication so that they can see how it will look when live and edit accordingly.
Trello: https://trello.com/c/fwUWX8tI/526-build-preview-functionality-into-the-publishing-tool

Add link to Preview draft step by step pages

---

app/models/step_by_step_page.rb
app/views/step_by_step_pages/_form.html.erb
spec/features/managing_step_by_step_pages_spec.rb

When the step by step page is saved and the editor goes back to edit it
it should not be able to edit the slug, neither the slug should be validated again
as the slug already exists.
Kinda part of this: https://trello.com/c/daxHC9M9/549-add-slugvalidator-in-collections-publisher

Don't change the slug once the Step Page is saved

---

app/controllers/steps_controller.rb
app/helpers/step_helper.rb
app/views/steps/_form.html.erb
db/migrate/20180319152348_remove_optional_content_from_steps.rb
db/schema.rb
spec/features/managing_steps_spec.rb

After our second round of user research, some elements in the step nav edit form were found to not be very clear.
* Make label for content clearer
* Explain why marking a step as optional (or not) is necessary
* Remove optional content as it's not used yet and needs more work to explain to users
[Trello card](https://trello.com/c/jq8eTn7O)

Content improvements to step nav edit form

---

app/views/step_by_step_pages/reorder.html.erb

#356 was using a heading structure on the reorder page that wasn't updated with the latest changes in #337. This uses the partial that ensures the headings among the pages are consistent.

Make reorder heading consistent with others

---

Gemfile
Gemfile.lock
app/models/navigation_rule.rb
app/models/step_by_step_page.rb
db/migrate/20180319082643_add_table_navigation_rules.rb
db/schema.rb
spec/models/navigation_rule_spec.rb

This PR contains a migration that stores links that have been mentioned on a Step of a "Step by Step page".
We need this so that we can turn on or off the "Step by Step navigation sidebar"  for individual content item pages.
Extra note: The parser gem had to be updated given it was using a yanked version (which was making the end to end tests fail), more context: https://github.com/alphagov/whitehall/pull/3917
Trello: https://trello.com/c/VDKP6zpq

Navigation rules migration

---

app/controllers/steps_controller.rb
app/services/step_links_for_rules.rb
app/workers/step_links_for_rules_worker.rb
spec/features/managing_steps_spec.rb
spec/services/step_links_for_rules_spec.rb

StepLinksForRulesWorker is responsible to send data to run StepLinksForRules where the links are extracted from the step contents.
Once those links are found it runs a request to Publishing API to get the content_id of that link.
Once the content_ids are fetched from Publishing API it requests the content to save the title, content_id and base_path in NavigationRule.
We can build up the payload for rules covering all the base paths in the current steps.  We can then override the "include_in_links" property in the current rule set (if any).
Then we can clear out all the rules (to ensure that we've catered for rules that are no longer relevant), and then add in all the rules that are for existing linked content.
This is to be later seen in the Rules page (frontend, to be done in future …

Navigation Rules Backend

---

app/controllers/steps_controller.rb
app/models/step_by_step_page.rb
db/migrate/20180326073415_add_publish_and_draft_times_to_step_by_step_page.rb
db/schema.rb
spec/models/step_by_step_page_spec.rb

We'll use these date fields to track in the app when a draft/publish event
occurs.  This adds the fields to the model that we'll use in subsequent work.
Also fixing a small bug where deleting a step doesn't update the draft correctly.

Add publishing fields to step by step page model

---

app/views/step_by_step_pages/show.html.erb

Before: 
After: 
[Trello card](https://trello.com/c/pAa4JrrZ)

Prevent long titles in step nav wrapping buttons

---

app/controllers/step_by_step_pages_controller.rb
app/controllers/steps_controller.rb
app/models/publish_intent.rb
app/models/step_by_step_page.rb
app/presenters/step_nav_presenter.rb
app/services/step_nav_publisher.rb
app/views/step_by_step_pages/index.html.erb
app/views/step_by_step_pages/publish.html.erb
app/views/step_by_step_pages/show.html.erb
config/routes.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/features/managing_steps_spec.rb
spec/models/step_by_step_page_spec.rb
spec/presenters/step_nav_presenter_spec.rb
spec/support/step_nav_steps.rb

We should only be able to publish something that has a draft
We should only be able to delete something that doesn't have a published version
I've added the skeleton of the unpublishing bits as it's coming directly next - we should only be able to unpublish a thing that has a published version
When you publish, you can add a change note for a minor version but it's not
mandatory.  It is mandatory for a major version.
I've started transferring to using gds-api-adapter test helpers rather than
stubbing the methods ourselves.

 Add publish functionality

---

app/controllers/step_by_step_pages_controller.rb
app/models/step_by_step_page.rb
app/services/step_nav_publisher.rb
app/views/step_by_step_pages/publish.html.erb
app/views/step_by_step_pages/unpublish.html.erb
spec/factories.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/support/step_nav_steps.rb

This allows a step by step page to be unpublished from the content-store.
It does not delete it from the application, so once unpublished, it can be
resubmitted at a later point.

Add unpublishing feature

---

app/services/step_content_parser.rb
spec/services/step_content_parser_spec.rb

We need to be able to cope with relative paths that are a number of different
styles:
- those with segments on the end
- those with query strings on the end
We need to strip these so that the base path lookup to publishing-api works for
more cases.
We also want to make this more robust so that typos are less likely to cause
a problem
https://trello.com/c/TDl0QL4k/576-why-doesnt-the-step-nav-show-on-my-page

Cope with more path variants

---

app/services/step_links_for_rules.rb

This ensures that we don't concatenate lines together and confuse the link parser.

Join content with a new line

---

app/assets/stylesheets/steps.scss
app/controllers/navigation_rules_controller.rb
app/helpers/application_helper.rb
app/models/navigation_rule.rb
app/models/step_by_step_page.rb
app/presenters/step_nav_presenter.rb
app/services/step_links_for_rules.rb
app/views/navigation_rules/edit.html.erb
app/views/step_by_step_pages/index.html.erb
app/views/step_by_step_pages/show.html.erb
config/routes.rb
spec/factories.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/features/managing_steps_spec.rb
spec/features/step_by_step_navigation_spec.rb
spec/presenters/step_nav_presenter_spec.rb
spec/services/step_links_for_rules_spec.rb
spec/support/step_nav_steps.rb

We add a page to select whether a linked content item appears in the `pages_part_of_step_nav` links (which will mean that it will be part of that page's navigation) or the `pages_related_to_step_nav` (which means that it won't be included in a page's navigation - yet)
The navigation rules backend has been largely added already
We can only do this if we've found the item in publishing api, so we try a parent path if we don't find the item initially (so we try `/foo` if we don't find `/foo/bar`).  This is a known problem with linking to guide chapters but not the default guide page.

Add navigation rules frontend

---

app/validators/slug_validator.rb
spec/models/step_by_step_page_spec.rb

Rails includes the field name by default so if we include it too we get "Slug Slug has already been taken" which is just weird
https://trello.com/c/KSK0Y2qu/538-check-and-fix-slug-validation-error-message

Remove field name from validation message

---

app/presenters/step_nav_presenter.rb
app/presenters/tag_presenter.rb
spec/presenters/mainstream_browse_page_presenter_spec.rb
spec/presenters/topic_presenter_spec.rb

This field has been replaced by the `meets_user_needs` link type.

Remove need_ids

---

lib/publish_organisations_api_route.rb
lib/tasks/publishing_api.rake

This commit fixes the organisations API publishing rake task by requiring some files and removing the reliance on time zones.
Trello: https://trello.com/c/p7ywlbk1/130-migrate-organisations-api

Fix organisations API publishing rake task

---

app/services/finder_publisher.rb
lib/finders/organisation_content.json
lib/tasks/publishing_api.rake
spec/services/finder_publisher_spec.rb

This is to replace the ["latest" page](https://www.gov.uk/government/latest?departments%5B%5D=department-for-work-pensions) for an organisation
It's not exactly a like for like because this finder will allow you to find latest content for all orgs using the facet, whereas the previous page would lock you to one org.
This finder doesn't currently have a subscribe to email link on it as it will subscribe users to all content for all orgs.  I've left it off until we can figure out how this might work.
The existing email subscription link on the org page will work as usual.
https://trello.com/c/fSv9RhjE/199-migrate-latest-pages-from-organisations

Add organisation finder

---

lib/finders/organisation_content.json

This now matches the [latest documents section](https://github.com/alphagov/collections/blob/63bc6efd0dd673fbab9bef1e22ec6644b325f36f/app/presenters/organisations/documents_presenter.rb#L73) on org pages.
This needs https://github.com/alphagov/govuk-content-schemas/pull/795 to be deployed before it will pass

Update latest orgs content finder

---

lib/finders/organisation_content.json

This adds the public updated at date to each result which makes it clear that the results are newest first.

Paginate finder and add publish date

---

app/helpers/application_helper.rb
app/lib/jwt_helper.rb
app/models/step_by_step_page.rb
app/presenters/step_nav_presenter.rb
app/views/step_by_step_pages/index.html.erb
app/views/step_by_step_pages/show.html.erb
config/application.rb
spec/helpers/application_helper_spec.rb
spec/lib/jwt_helper_spec.rb
spec/models/step_by_step_page_spec.rb
spec/presenters/step_nav_presenter_spec.rb

Trello: https://trello.com/c/9ZMVHe0u
Nearly all of the step-by-steps that are created need to be reviewed by people in departments who don't have signon access.  Content designers have been getting around this limitation by following a complicated process to create a preview app to send to factcheckers, but this process will become harder to support as more and more step-by-steps are created.
There is already a pattern used by Mainstream and Whitehall publishers that allows a list of `auth_bypass_ids` to be passed into the payload sent to publishing-api. This id is used by [authenticating-proxy](https://github.com/alphagov/authenticating-proxy) to decode a query string passed into the URL of the draft step-by-step. If the ids match, the user can view the content, otherwise, they will be …

Allow publishers to view draft step-by-steps without signon

---

app/assets/javascripts/steps.js
app/assets/stylesheets/steps.scss
app/models/step_by_step_page.rb
app/views/step_by_step_pages/index.html.erb
spec/models/step_by_step_page_spec.rb

- adds a status for a step by step navigation to the step by step navigation publishing interface
- status can be draft, published, or unpublished changes (i.e. has been published and since edited)
Trello cards: 
- https://trello.com/c/lgxjhPT6/750-display-status-of-step-by-step-on-index-page
- https://trello.com/c/1hRIjqY9/578-improve-search-and-filtering-functionality

Add status to step by step index page

---

app/views/step_by_step_pages/index.html.erb
spec/features/managing_step_by_step_pages_spec.rb
spec/support/step_nav_steps.rb

We should remove the 'Delete' link from the list of actions on the Step by step list page: https://collections-publisher.integration.publishing.service.gov.uk/step-by-step-pages
Deleting a step by step could removes live content from the site, this is now handled in Publish tab.
- Delete link removed from list page
- Tests for delete link removed
Ticket:
https://trello.com/c/kzy3S0gN/761-remove-the-delete-action-from-the-step-by-step-list-page-s

Remove the 'Delete' action from the Step by step list page (S)

---

app/assets/stylesheets/steps.scss
app/controllers/step_by_step_pages_controller.rb
app/views/navigation_rules/edit.html.erb
app/views/shared/steps/_form_notice.html.erb
app/views/step_by_step_pages/_form.html.erb
app/views/step_by_step_pages/_nav.html.erb
app/views/step_by_step_pages/edit.html.erb
app/views/step_by_step_pages/publish_or_delete.html.erb
app/views/step_by_step_pages/reorder.html.erb
app/views/step_by_step_pages/show.html.erb
config/routes.rb
spec/features/managing_step_by_step_pages_spec.rb

- Changes the position of the publish, delete and preview buttons
The position of the "Delete" Button on the Step by step overview page makes it feel like the default button to click.
We should reorder the buttons so that publishers don't keep clicking on Delete by accident.
Ticket: https://trello.com/c/3HrLsnG4/728-change-position-of-publish-delete-and-preview-buttons

Change position of Publish, Delete and Preview buttons

---

app/models/link_report.rb
db/migrate/20180807103538_create_link_reports.rb
db/schema.rb
spec/factories.rb
spec/models/link_report_spec.rb

This is a pull request that forms part of a link-checking feature for collections-publisher. The aim is for publishers to be able to check that links in their step-by-step guides are still alive. We're going to batch up all the links in a Step and send them to link-checker-api, collect the returned batch_id and store it against the Step, and then retrieve that batch by calling the API again when the batch is complete..
This pull request changes the schema and adds a new table to the database, called LinkReports. It also adds a relationship to the Step table. It sets up the branch for application changes.

Changes schema to include LinkReport model

---

app/lib/services.rb
app/models/step.rb
app/views/steps/_form.html.erb
spec/models/step_spec.rb

This commit adds a method to the Step model. It retrieves the most recent batch_id associated with the Step. Then it retrieves the full batch report from the link-checker-api service. Any broken links are returned to the frontend as an array of Hashes with the same structure as a [`BatchReport`](https://github.com/alphagov/link-checker-api/blob/master/docs/api.md#batchreport-entity)
We're only saving the batch_id for efficiency. There's a tradeoff between storing the whole batch locally against fetching it over the wire, but I've tried to keep the data in one place rather than replicating it in link-checker-api and in collections-publisher.
[Ticket](https://trello.com/c/yZLz7LTB/765-display-the-broken-link-report-in-the-edit-step-page)

Display summary of broken links on edit steps page

---

app/controllers/steps_controller.rb

This change is copied from the one already in the master branch. It uses the permitted step_params method to avoid permitting all parameters and instead only accepts the ones we need.
This PR: https://github.com/alphagov/collections-publisher/pull/437, enables brakeman security checking.
Unfortunately, the changes were merged after the "link-checker" feature branch was created, so now all of the branches for the link-checking feature are failing with: 
```
[build] Message: Parameters should be whitelisted for mass assignment
[build] Code: params.require(:step).permit!
[build] File: app/controllers/steps_controller.rb
[build] Line: 26
[build] 
[build] Confidence: Medium
[build] Category: Mass Assignment
[build] Check: MassAssignment
[build] Message: Parameters should be whitelisted for …
```

Fix the brakeman security errors

---

app/assets/stylesheets/steps.scss
app/controllers/mainstream_browse_pages_controller.rb
app/services/tag_republisher.rb
app/views/shared/steps/_broken-links-summary.html.erb
app/views/step_by_step_pages/show.html.erb
app/views/steps/_form.html.erb
spec/features/navigating_browse_pages_spec.rb
spec/models/tagged_documents_spec.rb
spec/presenters/archived_tag_presenter_spec.rb
spec/presenters/root_browse_page_presenter_spec.rb
spec/presenters/root_topic_presenter_spec.rb

It uses a panel and a collapse to display the information regarding the broken links.
Tickets: 
- https://trello.com/c/EPGwXv7z/768-add-styling-to-link-report-information-on-edit-steps-page-s
- https://trello.com/c/D5HDhtSx/767-display-a-summary-of-the-broken-link-report-on-the-step-overview-page-xs
Replaces https://github.com/alphagov/collections-publisher/pull/449
Collapsed:
Open:
Broken links:

Adds broken links section to edit steps page

---

app/controllers/link_report_controller.rb
config/routes.rb
spec/controllers/link_report_controller_spec.rb

This commit adds a webhook that receives a batch from the link-checker-api and updates that batch's completed time. This enables us to search for the most recent batch_id and retrieve that from the link-checker-api. We've implemented a webhook to avoid spamming the link-checker-api.
[Ticket](https://trello.com/c/eK2bYYNM/769-accept-responses-from-link-checker-api-about-the-status-of-a-link-report-s-m)

Adds webhook to receive batch

---

app/models/navigation_rule.rb
app/presenters/step_nav_presenter.rb
app/services/step_links_for_rules.rb
db/migrate/20180817100339_add_publishing_app_to_navigation_rules.rb
db/schema.rb
spec/factories.rb
spec/models/navigation_rule_spec.rb
spec/presenters/step_nav_presenter_spec.rb
spec/services/step_links_for_rules_spec.rb

Trello: https://trello.com/c/FJTvAlWq
Related to: https://github.com/alphagov/smart-answers/pull/3604
When smartanswers are published, two content items are created. One with a document type of "transaction" (start page) and the other with a document type of "smartanswer" (the main body of the smartanswer including the done page). 
When a step by step links to a smartanswer, only the start page is being linked to, therefore only the content_item for the start page contains the details of the step by step.
This means that when a user navigates to the end of a smartanswer they have no way of finding their way back to the step by step.
When a step by step is saved to the publishing-api add a check to determine whether the navigation rules contain any smartanswer start pages. 
If they do find …

Show step by step navigation on smartanswer done pages

---

app/presenters/step_nav_presenter.rb
spec/presenters/step_nav_presenter_spec.rb

Trello: https://trello.com/c/WHtWvjCl
Follows on from: PR #458 
Adds the  content_id of the service done page to the `part_of_step_nav` links in the payload for
publishing-api if the content_id for service start page is already included. 
So that the step by step navigation displays on the service done page.

Add service done pages to part_of_step_nav_links

---

app/controllers/link_report_controller.rb
app/controllers/step_by_step_pages_controller.rb
app/lib/services.rb
app/models/link_report.rb
app/models/step.rb
app/services/step_content_parser.rb
app/views/step_by_step_pages/show.html.erb
config/routes.rb
spec/controllers/link_report_controller_spec.rb
spec/models/link_report_spec.rb
spec/services/step_content_parser_spec.rb

[Ticket!](https://trello.com/c/nX8IgZ6z/766-request-a-broken-link-report-m)
This PR adds a number of methods to allow users to parse Step content for links, batch them, and then send them to link-checker-api. It includes a rogue commit that hotfixes an issue with the webhook. The issue only came to light when I tried it out for real, and [it's in this commit](https://github.com/alphagov/collections-publisher/commit/78cc154e95976785539c03144aafbd2d9b6f7137).

Batch links for api

---

app/models/step.rb
app/views/shared/steps/_broken-links-summary.html.erb
app/views/step_by_step_pages/show.html.erb
spec/models/step_spec.rb

Trello: https://trello.com/c/VKiDCA1o
Only show an error message for broken links on the step overview page if the step has broken links.

[WIP] Only show error message if there is a broken link

---

Gemfile
Gemfile.lock
app/assets/stylesheets/steps.scss
app/models/step.rb
app/models/step_by_step_page.rb
app/views/step_by_step_pages/show.html.erb
spec/models/step_by_step_page_spec.rb
spec/models/step_spec.rb

Trello: https://trello.com/c/qR9lA9GQ
Dependant on PR https://github.com/alphagov/govuk-lint/pull/103 to fix the lint issues addressed in Rubocop 0.52.1
Show the date and time for the last time that the links were checked, to give context to the link alert messages. Messages showing that the steps have no broken links are misleading if the links haven't been checked in a while.

Add a "last checked" timestamp below the check for broken links button 

---

app/models/internal_change_note.rb
db/migrate/20180829153755_create_internal_change_notes.rb
db/schema.rb

This commit adds an InternalChangeNote model with a foreign key on the StepByStepPage model. This enables us to build new functionality to record the changes that content designers have made to a step-by-step.
[Ticket](https://trello.com/c/OvHzWmh0/814-change-database-schema-to-add-changenote-model) and [more context](https://trello.com/c/G0fchnmS/733-ability-to-record-change-notes-l)
Research with content designers revealed that they like being able to see the changes they've made to a step-by-step. Ultimately this will probably be similar to git versioning, but as an MVP we're just implementing change notes. They'll have an author, a timestamp, and some content, all of which are validated. This will allow content designers to track changes they're making and also externalise knowledge …

Adds InternalChangeNote model

---

app/views/step_by_step_pages/publish_or_delete.html.erb

Add a reminder to check for broken links before publishing
To reduce the chances of step navs being published with broken links
This message can't be added until the link-checking feature has been rebased against master and the layout changes have been picked up.
This card should be played immediately after the link-checking feature has been merged into master.
collections-publisher
https://trello.com/c/6xZxg4b0/808-add-a-reminder-to-check-for-broken-links-before-publishing-xs

Add a reminder to check for broken links before publishing

---

app/models/step_by_step_page.rb
spec/factories.rb
spec/models/step_by_step_page_spec.rb

This commit adds an association on StepByStepPage to retrieve any associated InternalChangeNotes. 
[Ticket](https://trello.com/c/Ln7BhJct/829-add-method-to-step-by-step-page-to-retrieve-change-notes-s) and [wider context](https://trello.com/c/G0fchnmS/733-ability-to-record-and-view-change-notes-l)
It's a very small PR that allows a frontend dev to pull out the change notes for a step by step and display them so that users can find out the history of the step-by-step. This is part of a wider feature that allows publishers to add changenotes to a SBS page.
The team is looking at a better way to implement this, but as a minimum viable way of recording what publishers have done we're happy with it for the moment.
An array of InternalChangeNotes associated with a SBS can be recalled via …

Adds method to retrieve InternalChangeNotes

---

app/controllers/steps_controller.rb
app/views/steps/edit.html.erb
spec/features/managing_steps_spec.rb

Users of the step-by-step publishing tool were frustrated that after saving changes to a particular step they were booted back to the main edit view. This meant that if they were making a number of quick edits they spent a lot of time fruitlessly clicking back to get where they wanted to go.
This commit changes that redirect and just refreshes the page. It still displays a flash to let users know that their changes have been saved.

Changes Step edit to refresh page

---

app/controllers/internal_change_notes_controller.rb
app/controllers/step_by_step_pages_controller.rb
app/views/step_by_step_pages/_nav.html.erb
app/views/step_by_step_pages/internal_change_notes.html.erb
config/routes.rb
spec/controllers/internal_change_notes_controller_spec.rb
spec/features/managing_steps_spec.rb

This PR adds a controller and a form for publishers to add changenotes to their Step-By-Steps. It's a very rough MVP and does not contain a method to retrieve those notes. That method will be added in another PR.
[Ticket for this PR](https://trello.com/c/OqkwUwN3/818-create-changenote-controller-with-create-action) and [wider context](https://trello.com/c/G0fchnmS/733-ability-to-record-change-notes-l)
Publishers want a way to record changes they've made to a SBS, or leave notes for people on 2i to read. This is a small PR, because the team is currently working on pushing to master at least once a day as an experiment to find out if it gets value to users faster.

Internal changenotes controller

---

db/migrate/20180907075324_add_edition_number_to_internal_change_notes.rb
db/schema.rb

If a step by step has been previously published and has a draft, add a "discard draft" button. When this button is clicked:
* a "discard draft" request is sent to publishing api.
* get the latest "published" content from publishing-api
* copy the latest content over the step by step. Basically, reverse engineer the "render for publishing api" presenter. Things to consider:
* Excluding "done" pages from the navigation rules.
* Use the "content_id" to find the step by step to update as the base_path may have changed.
* Make sure the number of steps matches as some could have been added or removed between versions
* **[This PR]Add an edition id field to the change notes table. The default value should be nil.**
* Add a post publish task that:
* Gets the user_facing_version of the latest …

Adds edition_number column to internal_change_notes

---

app/assets/javascripts/steps.js
app/assets/stylesheets/steps.scss
app/controllers/internal_change_notes_controller.rb
app/models/internal_change_note.rb
app/views/step_by_step_pages/internal_change_notes.html.erb

As a content designer creating step by steps
I want to be able to see previous versions of the step by step
So that I can know who made changes to it and find out why, and so that I can revert to those versions if there's an issue with the current version
Mainstream Publisher has version history for each content item, so that you can see the changes that were made to it each time it was published. This would be very useful to have in the step by step publishing tool.
Explanation of why we're doing this work
https://trello.com/c/xurzZOox
Collections Publisher
https://trello.com/c/iDT6zgEA

Ability to record and view change notes

---

app/models/step.rb
spec/models/step_spec.rb

Trello: https://trello.com/c/e1vAwREO
Link-checker-api throw a 5xx error if `get_batch` is called for a batch report that doesn’t exist.
This isn’t usually a problem in Production, but step by step pages, and their associated link reports are copied
to integration and staging each night. This means that if when you try to view the step by step in those environments, it’s
querying link-checker-api with a batch id that was created in (and probably only exists in) production. This causes link-checker-api to
fail with a 5xx.
We should update link-checker-api to fail more gracefully if it can’t find a requested batch, but until then, allow collections-publisher
to load step by steps even if the link report details cannot be found.
Error in …

Rescue error raised from missing batch report

---

app/models/step.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/support/step_nav_steps.rb

Trello: https://trello.com/c/CcC66wRE
Link reports belong to a step.
Adding this dependancy fixes the Foreign Violation that occurs when you try to delete a step:
```
Cannot delete or update a parent row: a foreign key constraint fails (`collections_publisher_development`.`link_check_reports`, CONSTRAINT `fk_rails_ae2309ed25` FOREIGN KEY (`step_id`) REFERENCES `steps` (`id`))
```
Error in [Sentry](https://sentry.io/govuk/app-collections-publisher/issues/681560042/?query=is:unresolved)

Destroy link reports when a step is deleted

---

app/controllers/step_by_step_pages_controller.rb
spec/controllers/step_by_step_pages_controller_spec.rb
spec/support/step_nav_steps.rb

Trello: https://trello.com/c/kSH4Bvak
After a step by step is published, get the latest user_facing_version from publishing-api and store it against the change notes.
This will allow us in the future, to use the user_facing_version stored in the change notes and it marry to the edition stored in publishing-api to allow publishers in the future to see what was changed and why.
For now though, if a change note has a edition number, we will assume it belongs to a previous edition. However, if a change note does not have an edition number, we’ll assume it belongs to the latest draft, and delete it if the draft is ever discarded.

Update edition number of change notes on publish

---

spec/factories.rb

Fixes an error introduced in this PR: #487 
The `User deletes a step` feature test was failing with the following error:
```
ActiveRecord::RecordInvalid:
Validation failed: Title can't be blank, Base path can't be blank, Content can't be blank, Publishing app can't be blank, Schema name can't be blank
```
The factory being used created two steps, ` step` and an `or_step`. The `or_step` did not have any content, so when the first `step` was deleted and the navigation_rules were updated, they threw an error.
I have no idea why the test didn’t fail when it was first added.

Fix the delete step text

---

app/controllers/topics_controller.rb
app/views/layouts/application.html.erb
app/views/mainstream_browse_pages/show.html.erb
app/views/topics/index.html.erb
app/views/topics/new.html.erb
app/views/topics/propose_archive.html.erb
app/views/topics/show.html.erb
config/routes.rb
spec/features/archiving_topic_tags_spec.rb
spec/features/managing_topic_pages_spec.rb

Update the name for a legacy taxonomy. The user facing interface now uses `specialist sectors` instead of `topics` as `topics` is used by a lot of different things, and we're trying to ensure that the only thing that is considered a topic is the topic taxonomy.
Trello:
https://trello.com/c/uHNW4dZb/189-change-instances-of-topics-in-collections-publisher-to-specialist-sectors

Change legacy notation from topics to specialist sectors

---

config/routes.rb

When trying to visit the root of collections publisher, there is a redirect in place to take the user to `/topics`. The path `/topics` is now deprecated and the new route is
`/specialist-sector-pages`.

Fix redirect from home page

---

app/services/step_by_step_page_reverter.rb
spec/services/step_by_step_page_reverter_spec.rb

Trello: https://trello.com/c/c4z7hAxs
Dependant on PR #487
When draft changes are made to a published step by step in collections publisher, there is no way to discard those draft changes without manually unpicking them.
However, all of the previous editions are being stored in Publishing API.
We should give publishers the ability to discard a draft in collections-publisher by getting the latest published version of the step by step from the publishing-api and using that to repopulate the data for the step by step in collections-publisher.
In other words, programmatically unpicking the changes so that the publisher doesn't have to.
This is the first step in the ability to overwrite step by step data in collections-publisher with a version of the step by step held by publishing-api. The …

Repopulate a StepByStepPage with content from publishing-api

---

app/helpers/publishing_api_helper.rb
spec/helpers/publishing_api_helper_spec.rb

Trello: https://trello.com/c/UQPB5Tam
Functionality is being added to allow publishers to discard drafts of previously published content.
When these drafts are discarded, the data in the step by step will be replaced with the content of
latest published version held in publishing api.
By default, `get_content` retrieves the latest version regardless of publication state. Though we will
be sending a discard-draft request to publishing-api, this request may not have completed by the
time we are ready to revert the step-by-step, so we should make sure that we are over-writing it with
the correct version of the content.
However, we can specify which version of content we want by passing in the `latest_edition_number` as
the `version` when we are ready to replace the data:
e.g. …

Get version number of latest published edition

---

app/models/step_by_step_page.rb
spec/models/step_by_step_page_spec.rb

Drop all change notes associated with a draft but without an associated edition when that draft is discarded. 
When a SBS guide is published, it gets an edition number. At that point, we tag all the change notes **without** an edition number to that edition. However, if the draft is discarded, we don't want the change notes to hang around. If we leave them in the table they'll be tagged to the next published edition of that SBS guide. This would result in change notes that refer to a discarded draft being associated with a published guide, and that would cause confusion. 
This has been implemented with a method on the StepByStepPage that is called from the StepByStepPage controller. It drops all the changenotes associated to that StepByStepPage that don't have an edition. …

Adds method to discard change notes without an edition

---

db/migrate/20180921105035_add_draft_created_by_to_step_by_step_pages.rb
db/schema.rb

This is a database migration that creates a `draft_created_by` column on the `step_by_step_pages` table. It will store the name of the user that created the current draft.
This will enable work that will allow content designers to see who created the current draft. It's remedial work to prevent slowdowns when we scale SBS guide production up and start allowing more publishers to build them. 
[Specific ticket](https://trello.com/c/cnZkBnrq/871-add-a-column-to-stepbysteppage-to-store-the-current-user)

Adds column to StepByStepPage table

---

app/views/step_by_step_pages/internal_change_notes.html.erb

As a user I want to be able to see which edition a change note relates to so that I can distiguish which edition a change was made on.
Ticket: https://trello.com/c/kqQHs6wu/855-add-edition-badge-to-change-notes-s

Add edition badge to change notes

---

app/assets/stylesheets/steps.scss
app/views/step_by_step_pages/internal_change_notes.html.erb

Ticket: https://trello.com/c/CUlJqwif/861-bug-wrap-the-text-display-text-for-change-notes

Wrap the text display text for change notes

---

app/models/step_by_step_page.rb
spec/features/managing_step_by_step_pages_spec.rb

This change adds a `before_destroy` action to delete a draft guide's changenotes before deleting the draft guide itself. It's a custom method, to avoid accidentally deleting all of the changenotes associated to that guide.
As it stands a foreign key violation is thrown if you try to destroy a draft step by step without first deleting all of the change notes. This is because the changenotes have a foreign key on `step_by_step_pages`, and once the guide is deleted, the changenotes would be orphaned.
https://sentry.io/govuk/app-collections-publisher/issues/695190304/?query=is:unresolved

Fix delete guide when changenotes bug

---

app/helpers/publishing_api_helper.rb

Publishing api returns a content item hash with string keys.
Allow the hash to be accessed with label keys as well.
See https://api.rubyonrails.org/v4.2/classes/ActiveSupport/HashWithIndifferentAccess.html
Fixes a bug introduced in Pr #492

Allow indifferent access for content item hash

---

app/helpers/publishing_api_helper.rb

The fix applied in PR #502 didn’t completely fix the problem.
We need to parse the content returned by GDS API before we can apply Hash methods (with_indifferent_access) to it.
Error in [sentry](https://sentry.io/govuk/app-collections-publisher/issues/696647763/?query=is:unresolved)

Fix latest edition number bug

---

db/migrate/20180921153838_change_column_name_to_assigned_to.rb
db/schema.rb

This commit updates step_by_step_pages.draft_created_by to step_by_step_pages.assigned_to
The original naming was made in #498 
This change is because further user research showed that users were interested in who was working on the guide right now, rather than just who created it. This change enables that future work.
[Ticket](https://trello.com/c/vJylutsp/874-change-the-column-name-to-assignedto)

Updates column name

---

app/controllers/step_by_step_pages_controller.rb
app/models/step_by_step_page.rb
app/views/step_by_step_pages/publish_or_delete.html.erb
config/routes.rb
spec/controllers/step_by_step_pages_controller_spec.rb
spec/features/managing_step_by_step_pages_spec.rb

Trello: https://trello.com/c/C8eFHFSz
Related to PRs #485 #493 
Adds functionality to discard draft changes if the step by step has been previously published.
This functionality uses the new or existing functionality to:
1. Send a discard draft request to publishing-api
2. Drop the internal change notes for the discarded draft
3. Get the latest published content from publishing-api
4. Repopulate StepByStepPage with the latest published content
5. Display a "discard draft" button on the "Publish or delete" page

Allow publishers to discard a draft of previously published content 

---

app/controllers/step_by_step_pages_controller.rb
app/controllers/steps_controller.rb
app/workers/step_by_step_draft_update_worker.rb
spec/support/common_feature_steps.rb
spec/support/step_nav_steps.rb
spec/workers/step_by_step_draft_update_worker_spec.rb

This commit adds a small method that assigns whoever the current user is to the current draft when it is updated. This happens if a new guide is created or an existing guide is edited in any way. The meat of this commit is updating areas where this method is called and updating the tests as well.
It will allow users to see who is currently responsible for a draft.
I'm going to extend this in a future PR so that a change note is generated. This will create a "Chain of Custody" that describes who's been assigned the draft.

Adds method to assign current user to current draft

---

app/views/step_by_step_pages/publish_or_delete.html.erb

Trello: https://trello.com/c/C8eFHFSz
Confirmation text reads: "Discarding reverts content back to currently published version of the step by step. Do you want to discard your changes?"
Confirmation text reads: "This will delete your draft. Do you want to discard your changes?"

Change discard draft confirmation dialogue message

---

app/controllers/internal_change_notes_controller.rb
app/models/internal_change_note.rb
app/workers/step_by_step_draft_update_worker.rb
spec/workers/step_by_step_draft_update_worker_spec.rb

This PR is for a small function that runs when a step by step is going into draft. It generates an InternalChangeNote with the text `"Draft created by #{current_user.name}"`. 
We think that this will help users to keep track of who started the current draft and make communication and traceability easier.
[Ticket](https://trello.com/c/lsMQWc6u/875-add-a-change-note-when-the-draft-is-assigned-to-a-new-user)

Generate changenote when assigned

---

app/assets/stylesheets/steps.scss
app/views/shared/steps/_heading.html.erb
app/views/shared/steps/_last-saved-by.html.erb
app/workers/step_by_step_draft_update_worker.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/workers/step_by_step_draft_update_worker_spec.rb

These changes:
* display the name of the user who most recently saved a guide
* generate a change note when a different user saves a guide
After discussing with our content designers we've made these changes to make it easier to track the history of a step by step guide. The automatically generated chain of custody, alongside user-written change notes, should give a rich history of the guide in question. 
[Ticket](https://trello.com/c/KC9JoEZM/845-display-the-name-of-the-user-who-initiated-the-current-draft-m-l)

Assign user and log change

---

lib/finders/organisation_content.json

The Organisations finder at https://www.gov.uk/government/organisations/latest
needs a filter to only display items associated with Brexit.
** updated screenshot **
Trello: https://trello.com/c/Ci8Mst30/88-allowing-users-to-explore-brexit-content-related-to-a-department

Updates the organisations finder to include a brexit filter.

---

lib/special_route_publisher.rb
lib/tasks/publishing_api.rake

This creates the functionality to publish the [new campaign page](https://github.com/alphagov/collections/pull/952).
This has been tested by deploying this branch to integration and running the `publishing-api:publish_special_routes` rake task. The content item can be seen [here](https://www-origin.integration.publishing.service.gov.uk/api/content/prepare-uk-leaving-eu).

Create special route for campaign page

---

app/models/step.rb

This commit adds an exception handler for 404 errors from link-checker-api. This can happen if the batch link report has been removed, which happens autmoatically on a schedule to prevent build-up of old reports. The app should handle this case.

Handle missing batch link reports

---

app/views/step_by_step_pages/_form.html.erb

Currently you cannot edit the slug of an existing step-by-step
item.
This commit allows the slug to be edited.
I've tried this in integration and it seems to work fine.
Redirects are being set up for the old slug.

Make slug on step-by-step editable

---

app/lib/services.rb

Trello: https://trello.com/c/2IdzHdtp
Related to: 
* https://github.com/alphagov/govuk-puppet/pull/8488
* https://github.com/alphagov/link-checker-api/pull/227
Passes the bearer token needed to authenticate with link-checker-api using signon.

Add bearer tokens for link-checker-api authentication

---

Gemfile
Gemfile.lock

Related to: https://trello.com/c/2IdzHdtp/26-add-authentication-to-link-checker-api

Bump gds-api-adapters to 57.0

---

lib/special_route_publisher.rb

We want to make the `/prepare-eu-exit` page appear in GOV.UK site search under the services supergroup.  I'm doing this by tagging it as an `answer` document type in the short term - we can change this _soon_.  
The page is not appearing in search at all at the moment which is a problem.
I've set the description to one concocted by the Bravigation teams' content specialists.
Related to: https://github.com/alphagov/collections/pull/1056
https://trello.com/c/5GLtZUxs/152-get-prepare-eu-exit-in-search

Get prepare-eu-exit page into site search

---

app/services/finder_publisher.rb
lib/tasks/publishing_api.rake
spec/services/finder_publisher_spec.rb

The finder at https://www.gov.uk/api/content/government/organisations/latest
will be unpublished, and will redirect to https://www.gov.uk/search/all.
The organisation param will be preserved. The brexit param will not.
The rake task to unpublish the content item must be run manually:
```
publishing_api:unpublish_org_finder
```
Trello: https://trello.com/c/dhMHTIOr/377

Make it possible to unpublish the organisation finder

---

app/presenters/mainstream_browse_page_presenter.rb
lib/tasks/publishing_api.rake
spec/presenters/mainstream_browse_page_presenter_spec.rb

The primary publishing organisation is Government Digital Service for all Mainstream Browse Pages.
This is because GDS owns these pages.

Add primary publsihing organisation for Mainstream Browse Pages

---

app/presenters/topic_presenter.rb
lib/tasks/publishing_api.rake
spec/presenters/topic_presenter_spec.rb

Currently Topics don't have primary publishing organisation set.
This PR sets Government Digital Service as the primary publishing organisation.
Government Digital Service is added as it is the organisation, which owns it.
It also adds a rake task to update links for all topics.

Add primary publishing organisation for Topics

---

app/presenters/root_browse_page_presenter.rb
lib/tasks/publishing_api.rake
spec/presenters/root_browse_page_presenter_spec.rb

Root browse page is a special case as it is separate from the rest of mainstream browse pages, therefore needs a separate way of adding an organisation

Add primary publishing organisation to root browse page

---

app/presenters/root_topic_presenter.rb
lib/tasks/publishing_api.rake
spec/presenters/root_topic_presenter_spec.rb

Root topic page is a special case as it is separate from the rest of the topic pages, therefore needs a separate way of adding an organisation

Add primary publishing organisation to root topic page

---

app/services/step_content_parser.rb
spec/services/step_content_parser_spec.rb

At present, steps with multiple trailing lines will create an empty paragraph once parsed.
This breaks Google's [rich snippet parser](https://search.google.com/test/rich-results?id=sm1WcP0wSd_gSZ-3ZSSVUQ) for HowTo schemas, so we should fix it.
Note that it doesn't have any visible effects on the page as we seem to defend against that in the step by step component.
https://collections-publisher.publishing.service.gov.uk/step-by-step-pages/66/internal-change-notes

Cope with trailing whitespace in step markdown

---

app/assets/javascripts/steps.js
app/assets/stylesheets/steps.scss
app/controllers/secondary_content_links_controller.rb
app/models/secondary_content_link.rb
app/models/step_by_step_page.rb
app/presenters/step_nav_presenter.rb
app/services/step_by_step_page_reverter.rb
app/views/secondary_content_links/index.html.erb
app/views/step_by_step_pages/_nav.html.erb
config/routes.rb
db/migrate/20190520162024_create_secondary_content_links.rb
db/schema.rb
spec/controllers/secondary_content_links_controller_spec.rb
spec/factories.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/features/secondary_content_for_step_by_steps_spec.rb
spec/models/secondary_content_link_spec.rb
spec/models/step_by_step_page_spec.rb
spec/presenters/step_nav_presenter_spec.rb
spec/services/step_by_step_page_reverter_spec.rb

Trello: https://trello.com/c/iE60uYXs
Related to:
* https://github.com/alphagov/govuk_publishing_components/pull/900
* https://github.com/alphagov/publishing-api/pull/1501
* https://github.com/alphagov/govuk-content-schemas/pull/896
Secondary content is content that is about the service, but not needed by enough users to be included in the step by step. An example of this is internal links in content that is part of the step by step.
At the moment, if users click on internal links, they lose sight of the step by step journey they are on.
This PR allows content designers to assign content on GOV.UK as secondary content on a step by step.
A new tab in collections-publisher to assign secondary content to a step by step page in its links.
Secondary content behaves in the same way as all other …

Assign secondary content to step by step pages

---

app/controllers/step_by_step_pages_controller.rb
spec/controllers/step_by_step_pages_controller_spec.rb

**What**
Automatically create a change note when a step by step is published that reads:
- "Major update published by <user_name> with note: <change_note>"
- "Minor update published by <user_name> with note: <change_note>"
- "Minor update published by <user_name>" _- when optional description is not provided_
**Why**
It gives the content designers more detailed history of the changes made.  It
will also save them time they would spend on creating change notes manually.
**Examples**
- __Major__
- __Minor without note__
[Trello card](https://trello.com/c/5t0oXw2T/9-record-who-published-a-step-by-step-and-when-they-published-it)

Generate an internal change note when a step by step is published

---

app/services/step_nav_publisher.rb
spec/factories.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/services/step_nav_publisher_spec.rb

Sets `draft_updated_at` before sending payload to publishing-api.
This fixes a bug whereby live step-by-steps can't be previewed
if they have only been edited once since publish. If someone
added/removed/edited a step in a live step-by-step and then
clicked 'Preview', they would see the "Sorry, we're experiencing
technical difficulties page" normally only seen by users missing
an access token in the request URL. However, if they then made an
additional edit, they could preview the step-by-step as expected.
The bug arises from the fact that StepNavPresenter only sets the
`access_limited` field in the publishing-api payload if the
StepByStepPage `has_draft?` method returns `true`:
https://github.com/alphagov/collections-publisher/blob/909a35f7a688f12447579186d8f0eee48cd60afe/app/presenters/s …

Fix ability to preview step by step on first attempt

---

db/migrate/20190716152152_add_scheduled_at_to_step_by_step_pages.rb
db/schema.rb

Trello: https://trello.com/c/5WNB5kgU
Adds a field to record the date and time that the step by step is scheduled to be published.
The functionality to allow publishers to schedule step by steps is currently being added. Creating this migration separately allows, the different parts of the scheduling flow (Scheduling a step by step, sending scheduled jobs to publishing-api) to be worked on simultaneously.

Add scheduled_at field to StepByStepPages

---

app/controllers/application_controller.rb

Trello: https://trello.com/c/i5BbBKPg
A new "Scheduling" permission has been added to collections-publisher.
This will allow us to "soft" deploy the features being added to implement scheduling and
hide them behind this special permission.
When scheduling is ready to go "live" this permission will be removed.

Add scheduling permission

---

app/models/step_by_step_page.rb

Builds on the work done in https://github.com/alphagov/collections-publisher/pull/654.
Having a 'scheduled' status is a pre-requisite for other pieces of work this sprint. By defining the 'scheduled' status, we also display schedule status on the index, like this:
Trello: https://trello.com/c/oX0nn9NG/43-scheduled-status-should-appear-in-index-page

Adds 'Scheduled' status

---

app/models/step_by_step_page.rb
app/presenters/step_nav_presenter.rb
app/services/step_nav_publisher.rb
app/workers/step_by_step_scheduled_publish_worker.rb
spec/factories.rb
spec/models/step_by_step_page_spec.rb
spec/presenters/step_nav_presenter_spec.rb
spec/services/step_nav_publisher_spec.rb
spec/spec_helper.rb
spec/workers/step_by_step_scheduled_publish_worker_spec.rb

Trello: https://trello.com/c/ZDJTzOzG
Creates a job to schedule publication of the step by step, and processes that job on the scheduled date/time.
Scheduling a job:
* Notifies publishing-api of the intent to publish on date/time
* Adds a job to `StepByStepScheduledPublishWorker`
Processing a job:
* Only publishes step by steps with a status of "Scheduled"
* Only publishes step by steps with a scheduled date that's in the past
* Clears the `scheduled_at` date & time when the publish request is sent to publishing-api, i.e. it sets the status to "Published"
* Generates an internal change note
New jobs can be created by calling:
```
StepNavPublisher.schedule_for_publishing(step_by_step_page)
```
Note: the UI for users will be created in a separate PR.

Add scheduled job worker

---

app/presenters/step_nav_presenter.rb
app/services/step_nav_publisher.rb
spec/presenters/step_nav_presenter_spec.rb
spec/services/step_nav_publisher_spec.rb

Trello: https://trello.com/c/lxL03mid
Informs publishing-api that the scheduled job has been cancelled.
This should remove the header set by content-store to clear the cache at the scheduled time.
Note: This doesn't remove the job from the sidekiq queue. To do that we would have to store the job id of the schedule job, and loop through all of the jobs on the queue to find the right one to delete. Rather than do this, and run the risk of the wrong job being removed, we are instead [checking whether the job is still valid](https://github.com/alphagov/collections-publisher/blob/master/app/workers/step_by_step_scheduled_publish_worker.rb#L12) before processing it.

Notify publishing-api that scheduled publication has been cancelled

---

app/assets/javascripts/curated_lists.js
app/assets/javascripts/ordered_lists.js

This avoids an issue where jQuery modified by jQuery UJS gets
overridden by the unmodified jQuery required by the
govuk_publishing_components. This stops the X-CSRF-Token being sent,
breaking re-ordering list items.
Explictly add the header in, so that this functionality isn't
dependant on jquery-ujs.

Explicitly pass the CSRF token in AJAX requests

---

app/controllers/step_by_step_pages_controller.rb
app/views/step_by_step_pages/publish_or_delete.html.erb
config/routes.rb
spec/controllers/step_by_step_pages_controller_spec.rb
spec/features/managing_step_by_step_pages_spec.rb

**Why**
We have recently added the functionality to schedule publishing #652 and we should enable publishers to unschedule the publication of a step by step after it has been scheduled.
In the event that a scheduled publication date needs to change we should ensure that we have the functionality to unschedule a piece of content that has been scheduled for publication.
**What**
- users can see an option to unschedule a step by step, which is currently scheduled
- user can unschedule a publication of step by step
- `scheduled_at` datetime is cleared
- the status is updated on index page to 'Draft' or to 'Unpublished changes'
- internal change note is created when a step by step is unscheduled
- access to the feature is limited to users with 'Scheduling' permissions
_Note_
We have decided …

Unschedule publishing of Step by step

---

app/controllers/secondary_content_links_controller.rb
spec/controllers/secondary_content_links_controller_spec.rb
spec/features/secondary_content_for_step_by_steps_spec.rb

Fixes a regression whereby no error message is displayed if a
slug for a step by step's secondary link doesn't exist.
The error wasn't showing as it's outputting to flash[:danger],
which was no longer getting displayed in admin_layout.html.
The regression wasn't caught in tests as the test didn't assert
that the page contained content (it was missing an 'expect()').
Addresses https://trello.com/c/uZhLL67i/99-show-an-error-message-on-secondary-content-page-if-link-does-not-exist.
It's worth noting that the form error was probably intended to be displayed further down the page:
https://github.com/alphagov/collections-publisher/blob/87cc196cacb9a66ca1377f1b818a80ae2b25124b/app/views/secondary_content_links/index.html.erb#L47
^ That line currently doesn't appear to be doing anything. Worth …

Show error message when secondary link slug doesn't exist

---

app/views/step_by_step_pages/publish_or_delete.html.erb
spec/features/managing_step_by_step_pages_spec.rb

Trello: https://trello.com/c/UBOZ3bje
The date was being displayed as: 
"Scheduled to be published at 2019-12-10 16:35:00 UTC"
This formats the same date to read as: 
"Scheduled to be published on Tuesday, 10 December 2019 at 4:35 pm"

Format scheduled date on publish and delete page

---

app/models/step_by_step_page.rb
app/views/secondary_content_links/index.html.erb
app/views/step_by_step_pages/publish_or_delete.html.erb
spec/features/managing_step_by_step_pages_spec.rb
spec/models/step_by_step_page_spec.rb
spec/support/step_nav_steps.rb

When a user has scheduled a step by step for publishing, they should not be able to make any further changes to that step by step.
**'Delete or publish' page**
User _cannot_ publish unpublish, delete a step by step page or discard draft.
User _can_ unschedule.
<kbd><img width="972" alt="delete_publish_locked" src="https://user-images.githubusercontent.com/38078064/62711901-bff0d880-b9f1-11e9-93e9-b8cba317d296.png"></kbd>
**'Secondary links' page**
User _cannot_ add new secondary content links or delete existing secondary content links.
User _can_ view existing secondary content links.
<kbd><img width="972" alt="secondary_content_locked" src="https://user-images.githubusercontent.com/38078064/62711923-c5e6b980-b9f1-11e9-9d4a-cd72b889d988.png"></kbd>
This prevents any unexpected edits being …

Lock 'Delete or publish' & 'Secondary links' pages when publishing is scheduled

---

app/models/step_by_step_page.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/models/step_by_step_page_spec.rb
spec/support/step_nav_steps.rb

Trello: https://trello.com/c/KnzX5H6C
Change notes are only generated when a draft is saved by a "new user".
[This][1] was added to prevent a change note from being added every time the
user clicks the "save" button.
Unfortunately, this meant that a change note wasn't being added if the same
user who had previously published the step by step made new changes. To solve this
problem the user is being unassigned when the step by step is published.
[1]: https://github.com/alphagov/collections-publisher/blob/master/app/workers/step_by_step_draft_update_worker.rb#L27

Unassign the user when step by step is published

---

app/assets/javascripts/steps.js
app/views/navigation_rules/edit.html.erb
app/views/secondary_content_links/index.html.erb

Cancel links from navigation rules and secondary contents links do not have effect  at the moment and they should be removed.
These links were used to hide a container and reset the input value of the field. It turns out they weren't useful the way they were designed and after the UI update they don't have any effects anymore so it's been decided to remove them.
[Trello card](https://trello.com/c/Il5JA4d2)

Remove cancel links

---

app/assets/javascripts/application.js
app/assets/javascripts/components/autocomplete.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_autocomplete.scss
app/controllers/step_by_step_pages_controller.rb
app/helpers/time_options_helper.rb
app/services/datetime_parser.rb
app/views/components/_autocomplete.html.erb
app/views/components/docs/autocomplete.yml
app/views/step_by_step_pages/publish_or_delete.html.erb
app/views/step_by_step_pages/schedule.html.erb
spec/components/autocomplete_spec.rb
spec/controllers/step_by_step_pages_controller_spec.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/helpers/time_options_helper_spec.rb
spec/services/datetime_parser_spec.rb

This PR splits up the datetime text field into [Date](https://govuk-publishing-components.herokuapp.com/component-guide/date_input) and time (the latter of which is based on the autocomplete component copied from [Content Publisher](https://github.com/alphagov/content-publisher/)). The time field now provides a dropdown list of half-hourly suggested times - and a special case of 12:01am - but can also take any arbitrary time. These fields' placeholder values default to '9am tomorrow'. It stores this schedule time in London timezone format, so that BST is accounted for.
In addition, this PR also swaps out the Bootstrap submit button with [GOV.UK submit button](https://govuk-publishing-components.herokuapp.com/component-guide/button), and changes the redirect value of the cancel button to a …

Scheduling UI revamp - Design System

---

app/assets/stylesheets/_steps.scss
app/assets/stylesheets/utilities/_overrides.scss
app/views/layouts/admin_layout.html.erb
app/views/shared/steps/_markdown_help.html.erb
app/views/steps/_form.html.erb
app/views/steps/edit.html.erb

This PR improves the overall layout of the edit step page and includes the following changes:
- Increases the font size for the markdown example code (we avoid using 14 pixels as it's too small)
- Update the markdown guidance link to use govuk styles
- Make the 'Step title' input label bold, for consistency with the other fields
- Remove arbitrary margin overwrites
- Remove redundant row grid wrapper on primary action/return link
- Correct the back link/breadcrumbs positioning as per [design system template](https://design-system.service.gov.uk/styles/page-template/) and remove main wrapper overwrite.
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
[Trello card](https://trello.com/c/ousy4kjO)

Improve edit step page

---

app/views/step_by_step_pages/_nav.html.erb
spec/features/managing_step_by_step_pages_spec.rb

When a user has scheduled a step by step for publishing, they should not be able to make any further changes to that step by step.
- User _cannot_ see the Reorder steps tab and therefore change the order
- User _can_ still see the order in the steps Overview page
**Not scheduled**
**Scheduled for publishing**
_Note:_ No extra check implemented in the controller, as we trust content designers not to try to hack the url. 
This prevents any unexpected edits being published in error or too early.
[Trello card](https://trello.com/c/E4uqOWRy/82-lock-a-step-by-step-that-has-been-scheduled-for-publication-on-the-reorder-page-s)

Hide Reorder steps tab when the step by step is scheduled

---

app/views/components/_markdown_editor.html.erb

According to the guidance steps content should only need injectors for links and bullets.
[Trello card](https://trello.com/c/PiQCXSt0)

Remove unneeded buttons from the markdown toolbar

---

spec/features/managing_steps_spec.rb

We lock down a lot of behaviour when a step by step is scheduled,
but it should still be possible to add internal change notes.
Trello: https://trello.com/c/i5J47svc/89-lock-a-step-by-step-that-has-been-scheduled-for-publication-on-the-change-notes-page

Ensure change notes can be added to scheduled step by steps

---

app/views/step_by_step_pages/_form.html.erb
spec/features/managing_step_by_step_pages_spec.rb

When a user has scheduled a step by step for publishing, they should not be able to make any further changes to that step by step but they should still be allowed to check for broken links and view step content.
This prevent any unexpected edits being published too early.
[Trello card](https://trello.com/c/YMFbkQ13)

Show information instead of inputs if step by step can not be edited

---

app/views/step_by_step_pages/show.html.erb
spec/features/managing_step_by_step_pages_spec.rb

Trello: https://trello.com/c/ltbNPIGz
When a user has scheduled a step by step for publishing, they should not be able to make any further changes to that step by step
BUT they should still be allowed to add internal changenotes, check for broken links and preview changes.

Remove edit options from overview page for scheduled step by steps

---

app/models/navigation_rule.rb
app/views/navigation_rules/edit.html.erb
spec/factories.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/models/navigation_rule_spec.rb
spec/support/step_nav_steps.rb

When a user has scheduled a step by step for publishing, they should not be able to make any further changes to that step by step. 
- User _cannot_ change the navigation setting
- User _can_ view the navigation setting
**Not scheduled**
**Scheduled for publishing**
This prevents any unexpected edits being published in error or too early.
[Trello card](https://trello.com/c/0yrygTBl/88-lock-a-step-by-step-that-has-been-scheduled-for-publication-on-the-choose-navigation-pages)

Lock 'Choose navigation' page when the step by step is scheduled

---

config/routes.rb

The default page was Specialist sector pages, which is not used as often. We
are switch it to Step by step so its clear to users who are less familiar with
the tool.
[Trello card](https://trello.com/c/eA4r21sL/115-switch-the-default-tab-on-collections-publisher-to-be-step-by-step-pages)

Change default page to Step by step pages

---

config/application.rb
spec/controllers/step_by_step_pages_controller_spec.rb
spec/models/step_spec.rb

Trello: https://trello.com/c/WrpUNtsn
Config taken from: https://github.com/alphagov/content-publisher/commit/4ae1c4ed683bf0b24eb11d135aebd3cdd1a8ffa6
We store dates in the database in UTC, which means that when we're displaying
dates and times in the views they're an hour out of date during daylight saving
time. This sets the app's time zone to 'London' so that ActiveRecord
automatically converts dates and times to the UK's current time zone, whether
it's GMT or BST.
Also updates a test that was trying to get around this problem by converting the dates checked to "UTC +00:00"

Set the time zone to London

---

app/controllers/application_controller.rb
app/controllers/step_by_step_pages_controller.rb
app/views/step_by_step_pages/publish_or_delete.html.erb
db/seeds.rb
spec/controllers/step_by_step_pages_controller_spec.rb
spec/features/managing_step_by_step_pages_spec.rb

Trello: https://trello.com/c/By0dGoA7
Removes the "scheduling" special permission.
So anybody with GDS editor permissions can schedule a step by step for publication.

"Turn on" scheduling

---

app/views/step_by_step_pages/_nav.html.erb
app/views/step_by_step_pages/show.html.erb

Change the 'Edit steps' tab to 'View steps' when Step by step is scheduled
**Not scheduled**
<kbd><img width="971" alt="not_scheduled" src="https://user-images.githubusercontent.com/38078064/63332959-7462f680-c330-11e9-9463-2385604ea6d1.png">
</kbd>
**Scheduled for publishing**
<kbd>
</kbd>
Once the step by step is scheduled it is not possible to edit steps but they can still be viewed. The text on the tab is changed not to confuse content designers by giving the impression that the steps are editable.
[Trello card](https://trello.com/c/y3j0hfRN/133-change-the-edit-steps-tab-to-view-steps-when-step-by-step-is-scheduled)

Change the tab to View steps when Step by step is scheduled

---

app/models/step_by_step_page.rb
app/views/step_by_step_pages/publish_or_delete.html.erb
spec/features/managing_step_by_step_pages_spec.rb
spec/models/step_by_step_page_spec.rb
spec/support/step_nav_steps.rb

Trello: https://trello.com/c/3qZiI22D
Hides the "Publish" and "Schedule Publish" buttons if there are no steps, and if any steps don't have content.
Step by steps will still be able to be saved and previewed, but hiding the buttons will prevent any incomplete step by steps from being accidentally published.

Check steps have content before publishing

---

app/assets/javascripts/steps.js
app/assets/stylesheets/_steps.scss
app/assets/stylesheets/components/_all.scss
app/assets/stylesheets/components/_timeline-entry.scss
app/views/step_by_step_pages/internal_change_notes.html.erb
spec/features/managing_steps_spec.rb

This PR:
- Updates the change notes layout to use a  2/3 column for the internal notes timeline
- Make internal notes permanently visible
- Replaces the accordion with a [timeline entry pattern used consistently with content-publisher](https://github.com/alphagov/content-publisher/blob/60fa3c2fd2b351b2ca3ad5d1bd39f3ea1527918a/app/views/documents/show/_history_tab.html.erb)
- Use the accordion at the edition level (rather then internal note entry level).
<table>
<tr><td valign="top">
</td><td valign="top">
</td></tr>
</table>
**Note**: I appreciate the history of this PR doesn't make much sense as there was a bit of a back and forth on it, so I'd suggesting file-based review and I can squash them before merging.
[Trello …

Update change note history

---

app/assets/stylesheets/_steps.scss
app/assets/stylesheets/admin_layout.scss
app/assets/stylesheets/objects/_side.scss
app/assets/stylesheets/utilities/_overrides.scss
app/controllers/step_by_step_pages_controller.rb
app/helpers/time_options_helper.rb
app/models/step_by_step_page.rb
app/views/layouts/admin_layout.html.erb
app/views/step_by_step_pages/publish_or_delete.html.erb
app/views/step_by_step_pages/show.html.erb
spec/controllers/step_by_step_pages_controller_spec.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/helpers/time_options_helper_spec.rb
spec/models/step_by_step_page_spec.rb

This PR updates the summary page as follows:
- Updates the header of the page to use the admin_layout yield blocks
- Uses the metadata component to display information about the step-by-step
<table>
<tr><td valign="top">
</td><td valign="top">
</td></tr>
</table>
[Trello card](https://trello.com/c/arYq0tST)

Update heading and metadata on summary page

---

app/controllers/step_by_step_pages_controller.rb
app/models/publish_intent.rb
app/views/step_by_step_pages/publish_or_delete.html.erb
spec/controllers/step_by_step_pages_controller_spec.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/support/step_nav_steps.rb

When first publishing a step by step, it makes little sense to provide a changenote or
to designate a change as Major or Minor.
This change makes the publish screen show a "Publish" button for draft step by steps,
which publishes immediately. Published step by steps will continue to have a "Publish
changes" button with an intermediary changenotes screen.
Trello: https://trello.com/c/VKLFfznn/120-update-the-publishing-flow-so-the-change-note-minor-major-only-shows-if-updating-a-live-version

Bypass changelog screen when first publishing step by steps

---

app/assets/stylesheets/utilities/_overrides.scss
app/controllers/step_by_step_pages_controller.rb
app/presenters/step_by_step_page_presenter.rb
app/views/step_by_step_pages/show.html.erb
spec/presenters/step_by_step_page_presenter_spec.rb

Moved the business logic into a presenter rather than muddying the
view.
Did this as part of #703 then realised it was out of scope, so moving into its own PR.
There's no Trello card dependent on this, but it's probably a good idea to clean up
our view for maintainability.

Move metadata summary content into new StepByStepPresenter

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_steps.scss
app/assets/stylesheets/admin_layout.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_autocomplete.scss
app/assets/stylesheets/components/_markdown-editor.scss
app/assets/stylesheets/components/_panel.scss
app/assets/stylesheets/objects/_side.scss
app/assets/stylesheets/utilities/_overrides.scss
app/presenters/step_by_step_page_presenter.rb
app/views/components/_tabs.html.erb
app/views/step_by_step_pages/show.html.erb
package.json
spec/features/managing_step_by_step_pages_spec.rb
yarn.lock

Trello card: https://trello.com/c/qXVCEouI/23-show-the-content-title-slug-introduction-description-using-the-summary-component
Depended on by https://github.com/alphagov/collections-publisher/pull/709.
1. Upgrades govuk_publishing_components to 19.0.0, and
2. Uses summary_list component to render new sections on the 'step by step' admin page: 'Content', showing title/slug/intro/description (and an Edit link).
3. Adds tests so we can start having confidence that the right content is appearing on this page.
The summary list component was added to govuk_publishing_components
v18.2.0, hence the upgrade. As this is a major version change, there have
been some breaking changes (all detailed in the commit message).
A note from Alex:
> The legacy mode is not required in this app, but I'd keep it …

Upgrade govuk_publishing_components (19.0.0) & use summary_list

---

spec/models/step_by_step_page_spec.rb

Fixes error:
```
1) StepByStepPage validations must have a scheduled_at value that is nil or in the future
Failure/Error: expect(step_by_step_page).to be_valid
expected #<StepByStepPage id: nil, title: "Construct a giant castle made of armadillos", slug: "how-to-be-the-amazing-1", introduction: "Find out the steps to become amazing", description: "How to be amazing - find out the steps to become a...", created_at: nil, updated_at: nil, content_id: "826a0245-74b9-4d67-9a54-441acd06cd20", published_at: nil, draft_updated_at: nil, assigned_to: nil, scheduled_at: "2019-09-04 09:37:11", status: "draft"> to be valid, but got errors: Scheduled at can't be in the past
```
We only allow users to schedule publishing down to the minute, so it's ok to limit our tests to the same.

Fix scheduling validation check

---

app/presenters/step_by_step_page_presenter.rb
app/views/step_by_step_pages/show.html.erb
spec/features/managing_step_by_step_pages_spec.rb

Trello cards: https://trello.com/c/h6Oj4hno/46-move-sidebar-settings-and-secondary-links-inside-the-summary-component
Dependent on https://github.com/alphagov/collections-publisher/pull/703
1. Uses summary_list component to render new sections on the 'step by step' admin page:
- 'Sidebar settings' (and Edit/View link)
- 'Secondary links' (and Edit/View link), with guidance content taken from the secondary links page
2. Adds tests to verify that the correct content is appearing on this page.
Here are the additional sections added to the bottom of the page:
------

Add 'Sidebar settings' and 'Secondary links' sections

---

app/controllers/step_by_step_pages_controller.rb
app/views/step_by_step_pages/_change_notes.html.erb
app/views/step_by_step_pages/publish.html.erb
spec/controllers/step_by_step_pages_controller_spec.rb
spec/features/managing_step_by_step_pages_spec.rb

**What**
- View is updated in line with the [card](https://trello.com/c/ZB4lH4G8/28-publish-delete-tab-clarify-what-major-and-minor-updates-mean) description
- References to minor/major are removed from UI
**Why**
Content designers were not sure what does the minor and major update mean.
**Example**

Clarify major and minor updates

---

app/assets/stylesheets/admin_layout.scss
app/assets/stylesheets/objects/_grid.scss
app/assets/stylesheets/utilities/_overrides.scss
app/helpers/time_options_helper.rb
app/views/layouts/admin_layout.html.erb
app/views/step_by_step_pages/index.html.erb
app/views/step_by_step_pages/index/_filters.erb
app/views/step_by_step_pages/index/_results.erb
spec/features/managing_step_by_step_pages_spec.rb
spec/helpers/time_options_helper_spec.rb

This PR updates the summary page as follows:
- Update the heading and the "Create new" button
- Splits the index page into `_filters` and `_results` for maintainability and consistency with other publishing apps
- Updates the header of the page to use the admin_layout yield blocks and show the add button next to the title
- Updates the results table to use the table helper and document list component to generate the results consistently across publishing apps.
<table>
<tr><td valign="top">
</td><td valign="top">
</td></tr>
</table>
co-author: @AgaDufrat
[Trello card](https://trello.com/c/C4HHCrAX)

Update index page

---

app/assets/stylesheets/utilities/_overrides.scss

Last updated date is composed of 3 white-space-separated elements that wrap on new lines in default table conditions. Given we know this column will always be the last one in the results table we add an app-level overwrite to not wrap the cell content for this column.
[Trello card](https://trello.com/c/C4HHCrAX)

Fix last updated date wrapping

---

app/presenters/step_by_step_page_presenter.rb
app/views/step_by_step_pages/show.html.erb
spec/features/managing_step_by_step_pages_spec.rb

Merged "Sidebar settings" and "Secondary links" into one summary list.
[Trello card](https://trello.com/c/ABI6zopj/27-merge-the-choose-navigation-and-secondary-links-under-new-title-where-it-appears)

Merge "Where to show" sections

---

app/controllers/application_controller.rb
app/controllers/review_controller.rb
app/helpers/step_nav_actions_helper.rb
app/models/step_by_step_page.rb
app/validators/status_prerequisite_validator.rb
config/routes.rb
db/migrate/20190913122638_add_reviewer_to_step_by_step_pages.rb
db/schema.rb
spec/controllers/review_controller_spec.rb
spec/helpers/step_nav_actions_helper_spec.rb
spec/models/step_by_step_page_spec.rb
spec/validators/status_prerequisite_validator_spec.rb

Trello: https://trello.com/c/axseYRGB
This is a WIP. Things left to do:
1. Add "Claim 2i Review" action on overview page
2. Show who has claimed the review
Tested locally by:
1. Adding a temporary button to the overview page:
`<%= button_to "Claim 2i review", {controller: "review", action: "claim_2i_review", step_by_step_page_id: @step_by_step_page.id}, method: :post, class: "govuk-button gem-c-button gem-c-button--secondary-quiet" %>`
2. Creating a new user, and setting the `review_requester_id` to the uid of the new user
The status changes to "In review" as expected.

2i reviewer can claim step-by-step for review (backend)

---

app/controllers/step_by_step_pages_controller.rb
app/views/step_by_step_pages/schedule.html.erb
app/views/step_by_step_pages/schedule_datetime.html.erb
config/routes.rb
spec/controllers/step_by_step_pages_controller_spec.rb
spec/features/managing_step_by_step_pages_spec.rb

Updates scheduling workflow to let content designers choose if they want to tell users about the change to a step-by-step.
This is an option when publishing a step-by-step immediately, but was not available when scheduling.
First view in the workflow:
Second view in the workflow:
Trello card: https://trello.com/c/XM1zjRfM/62-add-notify-users-about-change-to-scheduling-workflow
This is a much simplified version of https://github.com/alphagov/collections-publisher/pull/735.

Add "notify users about change" to step-by-step scheduling workflow

---

app/assets/stylesheets/utilities/_overrides.scss
app/models/step_by_step_page.rb
app/views/step_by_step_pages/show.html.erb
app/views/step_by_step_pages/show/_required_actions.html.erb
spec/factories.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/models/step_by_step_page_spec.rb
spec/support/step_nav_steps.rb

Trello card: https://trello.com/c/IEGDwZch/49-use-inset-text-component-to-flag-actions-that-need-to-be-done-before-publishing
This PR:
- Uses `inset-text` component to show the important actions a user must take before they can
publish their step by step.
- Adds new pre-requisite: "Add at least one step"
Whilst it was never possible to publish an empty step by step (would fail the `has_content?`
check), it used to only have the generic error message "Every step must have content", which
doesn't make much sense if you haven't even added a step.
- Adds new pre-requisite: "Check for broken links"
Cannot publish a step by step without checking for broken links since your last update.
- Displays multiple links if step by step is affected by multiple things. Example:
One step may have no …

Flag actions to do before publishing step by step

---

app/controllers/review_controller.rb
app/models/step_by_step_page.rb
app/validators/status_prerequisite_validator.rb
config/routes.rb
spec/controllers/review_controller_spec.rb
spec/validators/status_prerequisite_validator_spec.rb

Once a 2i review has been requested, the reviewer needs to be able to either approve the review or request changes.
This PR carries the backend work.  Frontend work will be done separately.
Trello cards: https://trello.com/c/R85nupi5/38-2i-reviewer-can-approve-step-by-steps-backend and https://trello.com/c/rlPS1Kyo/36-2i-reviewer-can-request-change-to-step-by-step-backend

Allow 2i reviews to be approved, or changes requested

---

app/controllers/review_controller.rb
app/models/step_by_step_page.rb
app/validators/status_prerequisite_validator.rb
docs/arch/adr-3-store-status.md
spec/controllers/review_controller_spec.rb
spec/validators/status_prerequisite_validator_spec.rb

Rename `2i_approved` status with `approved_2i` to enable references to it.

Rename 2i approved status

---

app/controllers/step_by_step_pages_controller.rb
spec/features/managing_step_by_step_pages_spec.rb

When a user checks for broken links, they should see a message telling
them that their check is in progress. Previously we provided no feedback.
If the user refreshes the page, the message goes away.
Trello: https://trello.com/c/qensq3Jw/57-provide-feedback-when-clicking-check-for-broken-links

Show submission confirmation to user when they check for broken links

---

app/views/step_by_step_pages/show/_actions.erb
spec/features/managing_step_by_step_pages_spec.rb

We now have the preview a bit coupled with the Publishing action, which is not needed. With the changes in this PR we render the preview link regardless if the document can be published or not or whether the steps have content or not.

Show preview link even when the document can not be published

---

app/controllers/steps_controller.rb
spec/features/create_step_by_step_spec.rb
spec/features/filter_step_by_steps_spec.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/features/managing_steps_spec.rb
spec/features/secondary_content_for_step_by_steps_spec.rb
spec/features/step_by_step_navigation_spec.rb
spec/support/navigation_steps.rb
spec/support/step_nav_steps.rb

After the completion of the [UI revamp epic](https://trello.com/c/arYq0tST/22-epic-update-summary-page-layout-and-content) and half-complete addition of 2i workflow, our tests have become a little verbose and tricky to maintain. This is an attempt to split it into logical files, make each scenario more readable, and remove any redundant tests.
In writing these tests I also noted a redirect URL inconsistency, which I've fixed in my first commit.
Trello: https://trello.com/c/CXwhB5tD/76-simplify-tests-after-ui-changes

Simplify tests and fix redirect inconsistency

---

app/models/step_by_step_page.rb
app/views/step_by_step_pages/show/_required_actions.html.erb
spec/features/managing_step_by_step_pages_spec.rb
spec/models/step_by_step_page_spec.rb
spec/support/link_checker.rb
spec/support/step_nav_steps.rb

Prevents publishing/scheduling of step by steps if they contain broken links.
Trello: https://trello.com/c/9hBzk8lJ/69-change-inset-text-to-tell-user-to-fix-broken-links
Screenshot:

Fix broken links before publish

---

app/controllers/steps_controller.rb
spec/features/managing_steps_spec.rb
spec/features/step_by_step_navigation_spec.rb
spec/support/step_nav_steps.rb

Users were being kept on the steps page after they added or updated a step.  This caused confusion during user research.
This returns them to the step by step overview page (with confirmation banner) once they have created/updated a step.
Trello card: https://trello.com/c/ZhgPvuXD/79-redirect-users-to-summary-page-after-step-is-saved

Redirect users to summary page after step is saved

---

app/views/step_by_step_pages/show/_actions.erb
spec/features/managing_step_by_step_pages_spec.rb
spec/support/step_nav_steps.rb

This fix prevents the preview link from being shown when a step by step has been published and doesn't have changes since then.

Show preview link when the step-by-step has a draft

---

app/services/step_content_parser.rb
spec/services/step_content_parser_spec.rb

Fixes two bugs:
1) "Sidebar settings" page on step by step pages would break if there was a broken markdown URL in any step. They are now safely ignored (first commit).
2) Broken markdown links would also prevent the preview draft from updating. They are now safely ignored (and are simply rendered as broken markdown in the preview, making it obvious to content designers that there is a problem).
Trello card: https://trello.com/c/2hNZqWUY/67-preview-does-not-update-if-there-is-invalid-markdown-in-a-step

Make step markdown link-checking more robust (fix sidebar settings & preview)

---

spec/factories.rb
spec/features/step_by_step_actions.rb

As we're implementing 2i workflow into step by step publication, and
there is the possibility of 'fact check' workflow thereafter, our test
suites are becoming more difficult to maintain and less all-encompassing
of all possible states and use cases.
This new test suite has a simple aim: to denote exactly which actions
are available (and whether they are Primary, Secondary or Tertiary),
given a step by step is in a particular state and being viewed by a
particular author.
To be merged into #761. NB, I expect the tests to fail because currently we're showing "Publish" instead of "Submit for 2i" if a step by step has passed all its pre-requisite checks (e.g. link checking). This will be fixed in #761. In other words, this entire PR is the 'Red' in the 'Red Green Refactor' TDD approach. …

New test suite: contextual action button tests for step by steps

---

app/controllers/review_controller.rb
config/routes.rb
spec/controllers/review_controller_spec.rb

Trello: https://trello.com/c/eS79gejo/39-content-designer-can-revert-to-draft-if-changes-are-needed-after-2i
This adds logic to revert a step by step page back to draft. This will be needed in the event that a reviewer requests major changes that cannot be implemented without a 2nd approval.

Add route and logic to revert something back to draft

---

spec/support/step_nav_steps.rb

Tests were failing intermittently due to:
```
NameError: uninitialized constant StepNavSteps::LinkChecker
```
When running StepNavSteps in isolation, this error was reported on every run.
The rails_helper loads all support files for the tests.
Rspec runs the tests in a random order, so it appears 'rails_helper' had already been loaded from a previous spec on times when it passed.

Require rails_helper in StepNavSteps

---

Jenkinsfile

Every CI build since a2114054c05be6eac7e79f8f09c41e9596a1cc8c (inclusive) has failed with an error:
```
+ git tag -a release_n -m Jenkinsfile tagging with release_n
fatal: tag 'release_n' already exists
```
Whilst the release was being tagged, the CI build was marked as failing, therefore making it difficult to differentiate between passed and failed builds in the Jenkins interface.
The cause was due to govuk.buildProject being executed twice.  This has now been reduced down to a single request.

Resolve CI build release tagging error

---

app/views/step_by_step_pages/show/_actions.erb
app/views/step_by_step_pages/show/_required_actions.html.erb
spec/factories.rb
spec/features/create_step_by_step_spec.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/features/reviewing_step_by_steps_spec.rb
spec/features/step_by_step_actions_spec.rb
spec/support/common_feature_steps.rb
spec/support/step_nav_steps.rb

This work introduces the "Submit for 2i review" and the results or that action. I'm trying to avoid a massive PR, so since we're behind a feature flag I'm raising early to check the direction of this work with the rest of the team. Planning to raise a follow up PR that enables "claiming" after this gets merged.
In draft state or with changes after being published
After submitted for 2i
[Trello card](https://trello.com/c/Fwo562zl)

Add submit for 2i review action

---

app/controllers/internal_change_notes_controller.rb
app/controllers/review_controller.rb
app/controllers/step_by_step_pages_controller.rb
app/models/internal_change_note.rb
app/views/step_by_step_pages/internal_change_notes.html.erb
app/workers/step_by_step_draft_update_worker.rb
app/workers/step_by_step_scheduled_publish_worker.rb
db/migrate/20190925124652_add_internal_change_note_headline.rb
db/schema.rb
spec/controllers/internal_change_notes_controller_spec.rb
spec/controllers/review_controller_spec.rb
spec/controllers/step_by_step_pages_controller_spec.rb
spec/factories.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/features/reviewing_step_by_steps_spec.rb
spec/models/internal_change_note.rb
spec/workers/step_by_step_draft_update_worker_spec.rb
spec/workers/step_by_step_scheduled_publish_worker_spec.rb

Currently, we are displaying `Internal note` as the headline for all history entries.  A smaller description text explains the actual change (e.g. `Published`).
There are a number of issues with this:
- It is more difficult to users to scan through for specific status changes
- The author is duplicated (their name is appended to the description field, in addition to appearing after the timestamp)
This update adds a headline field to the internal change note table.  This is populated for each history entry with either a status change or where in the workflow it is.  All existing/historic history entries will retain their current style (i.e. labelled as `Internal note`).
Additionally, there are a number of copy changes detailed in a [Google …

Update change note title and entry

---

app/models/step.rb
app/models/step_by_step_page.rb
db/migrate/20190927080905_set_step_positions.rb
db/schema.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/models/step_spec.rb
spec/services/step_links_for_rules_spec.rb
spec/support/publishing_api_helpers.rb
spec/support/step_link_fixtures.rb
spec/support/step_nav_steps.rb

Adding new steps would not set the `position` property - this was only being set when explicitly reordering steps from the reorder screen - which led to strange bugs such as new steps being added to the top of the step by step.
We now set `position` to the "number of steps in the step by step + 1" so that it is added to the end. We also reset the positions if a step is deleted, to prevent step numbers becoming out of sync with how many steps there are.
I had hoped to implement this at the schema level with an `auto_increment` on the `positions` field, however this is not allowed on non-primary key fields, and in any case would not work properly as there are multiple step by steps (so incrementing would apply based on the number of steps in the database, irrespective of which step by step …

Fix ordering of steps

---

app/helpers/step_nav_actions_helper.rb
spec/helpers/step_nav_actions_helper_spec.rb

The current logic only permits a step by step to be claimed for review once.  There could be cases where another reviewer needs to take over the review.
This changes the logic so `can_review?` returns true if a user who is neither the current reviewer nor the review requester wishes to review the step by step.
Trello card: https://trello.com/c/Fwo562zl/72-2i-reviewer-can-claim-sbs-for-review

Allow an in_review step by step to be taken over by another reviewer

---

app/models/step_by_step_page.rb
spec/models/step_by_step_page_spec.rb

This enables access to details about the reviewer and review requester, e.g. to get the reviewer name:
```
step_by_step_page.reviewer.name
```
Trello card: https://trello.com/c/Fwo562zl/72-2i-reviewer-can-claim-sbs-for-review

Allow access to the reviewer and review requester details

---

app/models/step_by_step_page.rb
app/validators/status_prerequisite_validator.rb
app/views/step_by_step_pages/show/_actions.erb
app/views/step_by_step_pages/show/_required_actions.html.erb
spec/controllers/step_by_step_pages_controller_spec.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/models/step_by_step_page_spec.rb
spec/support/step_nav_steps.rb
spec/validators/status_prerequisite_validator_spec.rb

**Step by step in review, not approved (reviewer): **
<kbd>
</kbd>
**Step by step in review, not approved (review requestor): **
<kbd>
</kbd>
**Step by step approved:**
<kbd><img width="783" alt="approved_2i" src="https://user-images.githubusercontent.com/38078064/65701825-e2aa7f80-e079-11e9-8f75-87362e589edd.png"></kbd>
**TO DO** in a separate PR after feature flag is removed: 
*(WIP in improve-2i-publish-schedule branch)*
- Add `approved_2i?` condition to `can_be_published` method in the model and add unit tests
- Publish and schedule routes should not be usable unless SBS is in an approved_2i state
[Trello card](https://trello.com/c/yvGd29qp/74-only-approved-step-by-steps-can-be-published-or-scheduled)

Only approved_2i step by steps can be published or scheduled

---

app/controllers/secondary_content_links_controller.rb
app/models/step_by_step_page.rb
spec/controllers/secondary_content_links_controller_spec.rb
spec/models/step_by_step_page_spec.rb

Sometimes content designers will copy paths that have a space at the start or the end.
This PR makes two changes:
- Strips spaces from the beginning and end of secondary link paths.  These previously returned a 500 error.
- Strips spaces from the beginning and end of the step by step slug.  This would have given a `Slug is invalid` error.
Trello card: https://trello.com/c/kVsnP1b7

Remove spaces from start and end of step paths

---

app/views/layouts/admin_layout.html.erb
app/views/step_by_step_pages/_form.html.erb
app/views/steps/_form.html.erb

This resolves an issue where the title of pages in the step-by-step section are quite frequently missing. For example https://collections-publisher.integration.publishing.service.gov.uk/step-by-step-pages currently has `<title> - GOV.UK Collections Publisher</title>` whereas with this change it has: `<title>Step by steps - GOV.UK Collections Publisher</title>`
This also resolves a couple of contextual links that act as controls which show a visited state - which adds some confusion.
Before:
After:
Before:
After:

Couple of small fixes

---

app/views/secondary_content_links/index.html.erb
app/views/shared/steps/_markdown_help.html.erb
app/views/step_by_step_pages/_change_notes.html.erb
app/views/step_by_step_pages/_form.html.erb
app/views/step_by_step_pages/reorder.html.erb
app/views/step_by_step_pages/schedule_datetime.html.erb
app/views/steps/_form.html.erb
config/locales/en.yml

**As a** content designer
**I want** to be able to update contextual guidance in human readable files
**So that** I can do this without knowing Ruby
---
-  Decided to store the guidance in a single file as it will be easier for content designers to find and amend without knowing the structure of the folders and files. _This can be revised when we add more text._
- YAML file structure follows the folder structure of the views so it can be easily followed and the text can be reused in the future. It's the preferred way and it also allows to use a 'lazy' lookup without providing full path to the key when referencing it in the `t` method eg. `t(".slug_guidance")`
_Note:_ Not moved as it contains Markdown:
- Guidance on markdown `shared/steps/markdown_help.html.erb` 
- Guidance on secondary …

Move existing step by step guidance to a YAML file

---

app/helpers/step_nav_actions_helper.rb
app/views/step_by_step_pages/show/_actions.erb
app/views/step_by_step_pages/show/_required_actions.html.erb
spec/factories.rb
spec/features/reviewing_step_by_steps_spec.rb
spec/features/step_by_step_actions_spec.rb
spec/helpers/step_nav_actions_helper_spec.rb
spec/support/authentication.rb
spec/support/common_feature_steps.rb
spec/support/step_nav_steps.rb

[Trello card](https://trello.com/c/Fwo562zl)

2i reviewers can claim step by step

---

spec/support/step_nav_steps.rb

Depending on the order in which the support files are required, `common_feature_steps` may not have been loaded by the time we include it.  Therefore this adds an explicit require.

Explicitly require CommonFeatureSteps

---

app/views/steps/edit.html.erb

This removes the last instance of a page using the back link rather than breadcrumbs. This means that the whole process is consistent. 
Trello - https://trello.com/c/6Sv1xIAx/98-make-navigation-consistent-use-breadcrumbs

Step edit page uses breadcrumbs

---

app/helpers/application_helper.rb
app/views/secondary_content_links/index.html.erb
app/views/step_by_step_pages/reorder.html.erb
config/locales/en.yml
spec/helpers/application_helper_spec.rb

Content designers may wish to update in-app guidance by raising PRs on YAML files.  At the moment they would have to include HTML for any formatting.  The changes in this PR allow markdown to be used in guidance, and updates the existing guidance to use valid markdown.
Trello card: https://trello.com/c/zNqQjbMo

Parse markdown in in-app guidance

---

app/controllers/review_controller.rb
app/helpers/step_nav_actions_helper.rb
app/views/review/submit_2i_verdict.erb
app/views/shared/forbidden.html.erb
app/views/step_by_step_pages/show/_actions.erb
config/routes.rb
spec/controllers/review_controller_spec.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/features/managing_steps_spec.rb
spec/features/reviewing_step_by_steps_spec.rb
spec/features/step_by_step_actions_spec.rb
spec/helpers/step_nav_actions_helper_spec.rb
spec/support/common_feature_steps.rb
spec/support/step_nav_steps.rb

Trello: https://trello.com/c/2hmErFyt/75-2i-reviewer-can-approve-and-request-changes-on-step-by-steps
~Write `step_by_step_actions_spec.rb` tests for `2i_approved` state.~ Will do this [later](https://trello.com/c/Qle5c1QQ/43-write-tests-display-the-appropriate-buttons-depending-on-the-state-of-the-sbs-and-who-is-logged-in).
NB, uses copy found in the sketch attached to the ["2i reviewer can claim SBS for review" card](https://trello.com/c/Fwo562zl/72-2i-reviewer-can-claim-sbs-for-review).

2i reviewer can approve and request changes on step by steps

---

app/views/review/submit_2i_verdict.erb
spec/features/reviewing_step_by_steps_spec.rb

The labels were the wrong way round for the two 2i verdict actions (approve and request changes).
Also added a test to make sure the correct label is present in each scenario.
Trello card: https://trello.com/c/kx0JkDEb

Correct label when submitting 2i verdict

---

app/views/step_by_step_pages/show/_required_actions.html.erb
spec/features/managing_step_by_step_pages_spec.rb

All the other inset prompts start with an uppercase letter, this changes "get 2i approval" to "Get 2i approval" to keep this consistent.

Keep the case consistent in inset prompts

---

app/helpers/step_nav_actions_helper.rb
spec/features/reviewing_step_by_steps_spec.rb
spec/helpers/step_nav_actions_helper_spec.rb
spec/support/step_nav_steps.rb

Users without the `2i reviewer` permission could see the `Claim for 2i` button.  This would have resulted in a 403 error when clicked, since the permission was checked on this action.
This updates the conditions for showing the `Claim for 2i` button so only eligible users can see it.
Trello card: https://trello.com/c/mK2oXYID

Require 2i reviewer permission to see claim button

---

app/views/secondary_content_links/index.html.erb
config/locales/en.yml

- Updates a sentence in the guidance
- Removes `Base Path` label from input field
Documented in: https://docs.google.com/document/d/1YVTT-gJFGQPO5OKtP3BjWxI4IuJkijBRvEwU2EhQogE/edit#heading=h.837gql2zzefn
Trello card: https://trello.com/c/RKFEN2jg

Update secondary links contextual guidance

---

app/views/step_by_step_pages/show/_required_actions.html.erb
spec/features/managing_step_by_step_pages_spec.rb

User research found links that take users further down the summary page are not useful.  We are therefore removing the links.
Note that following a discussion with the team in person, we decided to remove all links, not just the "Check for broken links" link detailed on the Trello card.
Trello card: https://trello.com/c/qycgPimT

Remove links from inset text

---

app/controllers/review_controller.rb
spec/features/reviewing_step_by_steps_spec.rb

Just being asked to tell an author that a 2i had been approved or that a SbS needed changes was slightly confusing. This adds a line that makes it clear that no messages are automatically sent in these situations.
Trello - https://trello.com/c/Itc6JTZO/120-add-text-to-make-it-clear-that-the-app-has-not-sent-any-notifications-when-the-2ier-approves-or-requests-changes

Add message to warn user that notifications aren't sent

---

app/models/link_report.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/models/link_report_spec.rb

Link Checker API uses cached check results if a URL has been checked at any point in the last 4 hours.  Some users may wish to add newly published pages to a step by step.  Therefore the 'checkec_within' threshold needs to be set to something lower than the default value.
Not to be merged until https://github.com/alphagov/link-checker-api/pull/306 is merged and deployed.
Trello card: https://trello.com/c/9mLVRWFC

Set link checker 'checked_within' threshold to zero

---

app/controllers/steps_controller.rb
app/presenters/step_nav_presenter.rb
app/services/step_by_step_page_reverter.rb
app/views/steps/_form.html.erb
config/locales/en.yml
spec/factories.rb
spec/features/managing_steps_spec.rb
spec/presenters/step_nav_presenter_spec.rb
spec/services/step_by_step_page_reverter_spec.rb

Trello - https://trello.com/c/P1mSis5e/97-hide-optional-vs-essential-question-when-editing-step
Content designers say it wasn't being used consistently and it was confusing users
Pr to remove from Content Schemas
https://github.com/alphagov/govuk-content-schemas/pull/927

Remove optional / essential radio buttons

---

app/services/step_content_parser.rb
spec/services/step_content_parser_spec.rb

This will allow absolute URL links to be picked up by StepLinksForRules
for inclusion in the Sidebar Settings page.
This PR also refactors `StepContentParser` a little (see first commit).
Trello: https://trello.com/c/4JeWifGe/86-strip-govuk-from-link-markdown-and-show-them-on-sidebar-settings

Ignore GOV.UK prefix to show absolute links on Sidebar Settings

---

app/services/step_nav_publisher.rb
spec/services/step_nav_publisher_spec.rb

Sometimes a reviewer or review requester will want to make minor changes without getting stuck in a 2i review loop.  This change prevents the status from changing to 'draft' when a step by step that is currently submitted for 2i or in 2i review is edited.  If a step by step has been approved, published or scheduled, then the status is returned to 'draft' and another 2i review is required.
Trello card: https://trello.com/c/4FN9RaqT

Do not revert step by step to draft under certain circumstances

---

app/assets/stylesheets/_steps.scss
app/assets/stylesheets/admin_layout.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_autocomplete.scss
app/assets/stylesheets/components/_markdown-editor.scss
app/assets/stylesheets/objects/_side.scss
app/assets/stylesheets/utilities/_overrides.scss

This application doesn't rely on `govuk-template` so we're removing this flags to use the new colour scheme. This aligns the styles for Collections Publisher with Content Publisher and Signon.

Remove compatiblity with govuk-template

---

app/controllers/steps_controller.rb
spec/features/managing_steps_spec.rb

Content designers like to make small changes, save steps, refresh their preview
and repeat. Therefore there was an additional overhead involved in navigating
back to the step that is being edited, when making multiple small changes to it.
A product decision has been made to keep content designers on the 'Edit Step' page
when updating a step, to enable them to make multiple changes more easily. This
reverses logic added in https://github.com/alphagov/collections-publisher/pull/759
NB, we DO want to redirect to the overview page when CREATING steps, but we want
to stay on the edit page when updating existing steps.
Trello card: https://trello.com/c/qqOsgr1W/117-change-app-behaviour-to-not-redirect-user-to-summary-page-after-saving-a-step

Keep content designers on same page when editing a step

---

spec/factories.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/features/step_by_step_actions_spec.rb
spec/support/step_nav_steps.rb

Our step by steps can now be in any of a number of different 'states', and accessed by a number of different 'actors', all of which affects the actions available on the step by step.
We've started a dedicated feature file to test that the correct actions apply at the correct times, but this PR fills in some of the gaps:
(won't silently fail if another action creeps in, for example)
Trello: https://trello.com/c/Qle5c1QQ/43-write-tests-display-the-appropriate-buttons-depending-on-the-state-of-the-sbs-and-who-is-logged-in

Test actions thoroughly

---

app/services/step_nav_publisher.rb
app/views/step_by_step_pages/show/_actions.erb
spec/features/managing_step_by_step_pages_spec.rb
spec/features/step_by_step_actions_spec.rb
spec/services/step_nav_publisher_spec.rb

Once a step by step has been approved, content designers may wish to make minor edits without having to get 2i approval again.
This PR therefore makes two changes:
- Editing an approved step by step will not change the status to draft
- Adds a "revert to draft" action for approved step by steps (with warning prompt)
Example action:
Example warning:
Trello card: https://trello.com/c/eS79gejo

Add "revert to draft" button for approved step by steps

---

app/controllers/step_by_step_pages_controller.rb
app/models/step_by_step_page.rb
spec/controllers/step_by_step_pages_controller_spec.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/models/step_by_step_page_spec.rb
spec/support/step_nav_steps.rb

Requires a step by step to have been 2i approved before it can be scheduled or published.
This protects the relevant routes to ensure the approved status is set, and updates the `can_be_published?` logic so the relevant actions are only shown after approval.
Tests have been updated to match this change.  Feature tests have been changed to assume the SBS have been 2i approved in all cases, except where the test is specifically testing the 2i workflow.
Not to be merged until the 2i workflow is to be released and "Unreleased feature" flag is removed.
Trello card: https://trello.com/c/8o8PMB6n/88-only-approved-step-by-steps-can-be-published-or-scheduled-after-2i-is-released

[DO NOT MERGE] Only 2i approved step by steps can be published or scheduled

---

app/controllers/review_controller.rb
app/helpers/step_nav_actions_helper.rb
app/views/step_by_step_pages/show/_actions.erb
spec/controllers/review_controller_spec.rb
spec/features/create_step_by_step_spec.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/features/reviewing_step_by_steps_spec.rb
spec/features/step_by_step_actions_spec.rb
spec/helpers/step_nav_actions_helper_spec.rb
spec/support/common_feature_steps.rb

To be merged with #797 
I kept the `require_unreleased_feature_permissions!` method
[Trello card](https://trello.com/c/g1qXMozp/139-remove-all-references-of-the-feature-flag-in-the-code-and-any-tests)

Remove feature flag from 2i workflow

---

app/models/step_by_step_page.rb
app/services/step_nav_publisher.rb
db/migrate/20191008111813_add_auth_bypass_id_column_to_step_by_step_pages.rb
db/migrate/20191008113036_populate_auth_bypass_id.rb
db/migrate/20191009091313_disallow_null_auth_bypass_id.rb
db/schema.rb
spec/factories.rb
spec/models/step_by_step_page_spec.rb
spec/services/step_nav_publisher_spec.rb

Rather than [mutate a content_id](https://github.com/alphagov/collections-publisher/blob/master/app/models/step_by_step_page.rb#L130-L143) to calculate the `auth_bypass_id`, this instead uses a random UUID which changes for each edition. This makes it so that the same token cannot be used to preview later versions of the content and stops the ID being a predictable value.
Due to the random nature, we now store the `auth_bypass_id` in the database, rather than calculate it each time it is required.
This will require a two-step deployment.  Firstly, the release should be deployed using the `app:migrate` deploy task to add the `auth_bypass_id` database column and backfill this with existing IDs.  Secondly, the application can be deployed normally to actually switch to using the randomised …

Use a random UUID for the auth_bypass_id

---

db/migrate/20191008113036_populate_auth_bypass_id.rb

This migration was written to use `update`.  This changes the `updated_at` field during the migration (making it look like all step by steps have been modified by a content designer).  Changing to `update_column` so this time is not changed.
This migration has not yet been deployed to production.
Trello card: https://trello.com/c/jKRvjyAe

Use update_column for backfilling auth_bypass_id values

---

app/views/shared/steps/_markdown_help.html.erb
app/views/step_by_step_pages/_form.html.erb
app/views/steps/_form.html.erb
config/locales/en.yml
spec/features/managing_step_by_step_pages_spec.rb
spec/features/managing_steps_spec.rb

This adds contextual guidance to the add/edit step-by-step and add/edit step pages.
[Trello card - Add Contextual guidance to Add/Edit Content page](https://trello.com/c/nNcyHxaw)
[Trello card - Add Contextual guidance to Add/Edit Step page](https://trello.com/c/d9XCwVa2)

Add contextual guidance to edit pages

---

app/presenters/step_by_step_page_presenter.rb
app/views/step_by_step_pages/show.html.erb
spec/features/managing_step_by_step_pages_spec.rb

Adds a link to the step by step in Content Tagger under a new "Tags" section.
The label will always say "Edit", since the tags can be changed regardless of whether the step by step is draft or published.
Trello card: https://trello.com/c/uoBZfPNn

Add link to Content Tagger for step by steps

---

app/controllers/step_by_step_pages_controller.rb
app/views/step_by_step_pages/guidance.html.erb
app/views/step_by_step_pages/show/_required_actions.html.erb
config/locales/en.yml
config/routes.rb
spec/features/step_by_step_actions_spec.rb

This adds the contextual guidance page, links to it from SBS's that are in review and tests for same. This will provide a place where 2i reviewers can go to see guidance on what the intended use of attributes are.
Trello - https://trello.com/c/K4Uyg9m6/127-add-a-view-giving-some-contextual-guidance-to-2i-reviewers

Add contextual guidance page

---

app/views/navigation_rules/edit.html.erb
app/views/secondary_content_links/index.html.erb
config/locales/en.yml

This PR
- adds guidance to sidebar settings page and fixes broken markup
- adds guidance to secondary links page and fixes broken markup
[Trello card](https://trello.com/c/ij0U9BPn)

Add guidance to sidebar settings and secondary links pages

---

app/views/step_by_step_pages/show/_required_actions.html.erb
spec/features/managing_step_by_step_pages_spec.rb

Adds in a check for the status of a SBS and provides guidance accordingly. This should stop a bug where the "To publish this SBS you need to" box appeared without giving any suggestions.
Trello - https://trello.com/c/7IzRnut3/163-to-publish-this-sbs-you-need-to-doesnt-list-any-things-the-user-needs-to-do

Fix bug that caused box to appear with no suggestions

---

app/helpers/step_nav_actions_helper.rb
app/views/step_by_step_pages/show/_required_actions.html.erb
spec/features/managing_step_by_step_pages_spec.rb
spec/helpers/step_nav_actions_helper_spec.rb
spec/support/step_nav_steps.rb

Trello - https://trello.com/c/XM016j2s/149-bug-check-for-broken-links-when-there-are-no-links
Stops a message from appearing at the top of the page asking the user to "Check for broken links" if the step-by-step doesn't contain any links.

Broken links bug

---

app/helpers/step_nav_actions_helper.rb
app/models/step_by_step_page.rb
app/views/step_by_step_pages/show/_required_actions.html.erb
spec/features/managing_step_by_step_pages_spec.rb
spec/helpers/step_nav_actions_helper_spec.rb
spec/models/step_by_step_page_spec.rb
spec/support/step_nav_steps.rb

Trello: https://trello.com/c/t2MylOor
Reverts changes made in PR #754 
Remove the requirement that forced users to fix all of the broken links before they can publish step-by-steps.
In many cases step-by-steps contain links to draft content or other draft step-by-steps. It's also possible to for draft step-by-steps to be linked to each other. As Link Checker API doesn't handle draft content, and can only check links that are publicly accessible, publishers could end up in a chicken or egg situation where they can't publish any step-by-steps.

Remove fix broken links requirement

---

app/helpers/step_nav_actions_helper.rb
app/views/step_by_step_pages/show/_actions.erb
spec/features/step_by_step_actions_spec.rb
spec/helpers/step_nav_actions_helper_spec.rb

This allows the author to revert to draft when the Step by step is in `submitted_for_2i` state or in `in_review` state.
**Before**
**After**
[Trello card](https://trello.com/c/FoRZjA0I/164-when-a-sbs-is-submitted-for-2i-theres-no-revert-to-draft-link-only-an-unpublish-option)
_Note:_ Functionality that allows the reviewer to abandon review will be added as a separate PR.

Show Revert to draft link when step by step is submitted for 2i and in review

---

app/views/review/submit_2i_verdict.erb
app/views/review/submit_for_2i.html.erb
app/views/step_by_step_pages/internal_change_notes.html.erb
app/views/step_by_step_pages/publish.html.erb
app/views/step_by_step_pages/schedule.html.erb
app/views/step_by_step_pages/schedule_datetime.html.erb
config/locales/en.yml

Add Contextual guidance to change notes:
- internal change notes (on history page)
- notes when submitting for 2i
- notes when requesting changes or approving
- notes when publishing or scheduling
[Trello card](https://trello.com/c/EOm5X8Mp)

Add contextual guidance for notes

---

app/views/step_by_step_pages/show/_required_actions.html.erb

The 2i reviewer name was appearing twice.  This removes the duplication, by removing the name from the link.
Example:

Remove duplicated 2i reviewer name

---

app/presenters/step_nav_presenter.rb
spec/presenters/step_nav_presenter_spec.rb
spec/services/step_nav_publisher_spec.rb

Trello: https://trello.com/c/sUjBwDG0
Follows on from: 
* https://github.com/alphagov/govuk-rfcs/blob/master/rfc-113-expanding-draft-access-for-unauthenticated-users.md
* https://github.com/alphagov/publishing-api/pull/1614
`auth_bypass_ids` have been separated from the `access_limited` hash in publishing-api.
This updates collections-publisher to send `auth_bypass_ids` to the new field.

Use new auth_bypass_ids field in publishing-api

---

app/services/step_content_parser.rb
spec/services/step_content_parser_spec.rb

We are currently treating step links with a URL that has no protocol (e.g. `www.gov.uk/random` or `gov.uk/random`) as external links and therefore sending the URL as-is to link checker.  The link check fails due to no protocol.
This change removes these URLs from the external links array, so they get treated as internal links.
Trello card: https://trello.com/c/yRlt59zb

Deal with internal step links without a protocol

---

app/presenters/step_by_step_page_presenter.rb
app/views/navigation_rules/edit.html.erb
app/views/secondary_content_links/index.html.erb
app/views/step_by_step_pages/_form.html.erb
app/views/step_by_step_pages/guidance.html.erb
app/views/steps/_form.html.erb
config/locales/en.yml

**As a** Content Designer
**I want** to easily modify the contextual guidance and make sure it's consistent across the app
**So that** the various places the guidance appears remain synchronised
- Shared contextual guidance is stored under `guidance` key, which removes repetition
- Rewrite guidance.html.erb so it doesn't rely on the structure of the YAML file
- Change formatting of the guidance page as shown below
| Before  | After |
| ------------- | ------------- |
| <img width="334" alt="guidance_before" src="https://user-images.githubusercontent.com/38078064/67223078-893e3200-f426-11e9-81a5-6134fe179af2.png">  | <img width="330" alt="new" src="https://user-images.githubusercontent.com/38078064/67266384-0bbb0600-f4a8-11e9-8397-eb709927c443.png">  |
[Trello …

Restructure locales YAML file

---

app/controllers/secondary_content_links_controller.rb
app/controllers/step_by_step_pages_controller.rb
app/controllers/steps_controller.rb
app/services/step_by_step_updater.rb
app/services/step_nav_publisher.rb
spec/services/step_by_step_updater_spec.rb
spec/services/step_nav_publisher_spec.rb
spec/spec_helper.rb
spec/support/sidekiq.rb

This commit makes sure the status of the step by step is in the correct
state after an edit has been made. Previously, the code to update the
state was inside a sidekiq worker which may not have completed upon the
new page being loaded. This led to the wrong links being displayed until
the worker has processed the job.
Trello:
https://trello.com/c/L4IbSFuv/111-status-doesnt-update-to-draft-until-page-is-refreshed

Update status on page refresh after update

---

app/assets/stylesheets/utilities/_overrides.scss

Fix wrapping action links on summary-list component
Make steps more prominent
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>

Fix actions on summary list

---

.scss-lint.yml
Gemfile
Gemfile.lock
Jenkinsfile
lib/tasks/lint.rake

https://trello.com/c/EcitEsfK/1297-audit-dependabot-for-collections-publisher
Previously we replaced govuk-lint-ruby with rubocop-govuk. This completely
removes govuk-lint by replacing govuk-lint-sass with using scss-lint
directly, ensuring we're linting locally and in Jenkins.

Replace govuk-lint(-sass) with scss-govuk

---

app/controllers/application_controller.rb
app/controllers/coronavirus_controller.rb
app/presenters/coronavirus_page_presenter.rb
app/views/coronavirus/index.html.erb
app/views/layouts/admin_layout.html.erb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/coronavirus_page_spec.rb
spec/fixtures/coronavirus_landing_page.yml
spec/fixtures/invalid_corona_page.yml
spec/presenters/coronavirus_page_presenter_spec.rb

This allows publishing of the page that is configured in [Github](https://github.com/alphagov/govuk-coronavirus-content)
The flow is:
- Update the yaml in github (and merge it)
- Update the draft in by hitting the button in this app
- Review the draft
- Update Github as necessary
- Publish
There is some basic yaml validation here, but mainly the hope is that changes
will generally be small enough to be eyeballed correctly.
https://trello.com/c/0uZVAYYt/35-look-at-options-for-publishers-to-update-page

Add publish coronavirus page

---

app/controllers/coronavirus_controller.rb
app/presenters/coronavirus_page_presenter.rb
spec/presenters/coronavirus_page_presenter_spec.rb

This is timing out on integration, so add some extra leeway and provide better feedback if it does fail.
Also adding a default "minor" update type to draft updating.  This is overridden by the value chosen at publish time, but publishing-api seems to need it.

Increase publishing timeout

---

lib/tasks/publishing_api.rake

It'll be useful to be able to preview the draft before publishing.
If there is no draft to publish, then the publish job will fail.  This is
not a bad thing.
I named the tasks weirdly so that they appear next to each other when listed.

Split draft update and publishing of business page

---

app/views/coronavirus/shared/_draft.html.erb
app/views/coronavirus/shared/_publish.html.erb

form_with now assumes an xhr request unless you specify `local: true`
The flash message was being rendered and returned to the browser as an AJAX response, so the client page never updated.

Fix flash messages not appearing

---

app/models/secondary_content_link.rb
app/models/step_by_step_page.rb
app/models/tag.rb

Fixes Rail 6.1 deprecation warnings
```
DEPRECATION WARNING: Uniqueness validator will no longer enforce case sensitive comparison in Rails 6.1. To continue case sensitive comparison on the :slug attribute in StepByStepPage model, pass `case_sensitive: true` option explicitly to the uniqueness validator
DEPRECATION WARNING: Uniqueness validator will no longer enforce case sensitive comparison in Rails 6.1. To continue case sensitive comparison on the :slug attribute in Tag model, pass `case_sensitive: true` option explicitly to the uniqueness validator
DEPRECATION WARNING: Uniqueness validator will no longer enforce case sensitive comparison in Rails 6.1. To continue case sensitive comparison on the :base_path attribute in SecondaryContentLink model, pass `case_sensitive: true` option …
```

Uniqueness validator explicitly uses case sensitivity

---

app/views/coronavirus/shared/_publish.html.erb

- This isn't a code change, just a words change for step 5 of the coronavirus 'publish a draft onto the website' workflow.
- I was testing a thing in integration and having it say 'production' even though I was in integration made me hesitate and look at the code to make sure it wasn't hardcoded to production.
- I tried to make the environment it specified match the currently deployed environment (`GovukPublishingComponents::AppHelpers::Environment.current_acceptance_environment`), but I'm too tired to make the interpolation work properly in the component.

coronavirus: Remove 'to production' wording from '5. Publish changes'

---

app/controllers/coronavirus_controller.rb
app/models/live_stream.rb
app/presenters/coronavirus_page_presenter.rb
app/services/live_stream_updater.rb
app/views/coronavirus/index.html.erb
app/views/coronavirus/live_stream.html.erb
config/routes.rb
db/migrate/20200409194204_create_live_stream.rb
db/schema.rb
spec/features/coronavirus_page_spec.rb
spec/fixtures/coronavirus_content_item.json
spec/fixtures/coronavirus_landing_page.yml
spec/presenters/coronavirus_page_presenter_spec.rb
spec/services/live_stream_updater_spec.rb
spec/support/coronavirus_feature_steps.rb

- first attempt at adding a button to the coronavirus pages tab in collections publisher so that content designers/others can activate the livestream without dev input. 
- Set the livestream state (on or off) in collections publisher instead of in the [yaml](https://github.com/alphagov/govuk-coronavirus-content/blob/master/content/coronavirus_landing_page.yml) file in the govuk-coronavirus-content repo
- Persist live stream state in database
- Read from database when creating payload for publishing api
[Trello card](https://trello.com/c/tsal0J9i/158-create-a-way-for-content-designers-to-switch-the-livestream-on-and-off)

Turn on coronavirus live streams from collections publisher

---

lib/tasks/publishing_api.rake

These are no longer used now that the publishing tool is up and running.

Remove redundant rake tasks

---

app/views/coronavirus/live_stream.html.erb
app/views/coronavirus/shared/_live.html.erb
app/views/coronavirus/show.html.erb
spec/features/coronavirus_page_spec.rb
spec/support/coronavirus_feature_steps.rb

Fixes: 
- [The livestream toggle page](https://collections-publisher.publishing.service.gov.uk/coronavirus/live_stream) "Check live" link that is not currently environment specific
- [The business support page](https://collections-publisher.publishing.service.gov.uk/coronavirus/business) has a "View live version" link that points to the /coronavirus page

Fix a couple of coronavirus issues 

---

app/controllers/coronavirus_controller.rb
spec/features/coronavirus_page_spec.rb
spec/support/coronavirus_feature_steps.rb

This adds the education hub page basic information.  We'll need to add the referenced yaml file

Add education page

---

app/views/coronavirus/index.html.erb
config/routes.rb
spec/features/coronavirus_page_spec.rb

Because we are no longer toggling the live stream
video component (ref: https://github.com/alphagov/collections/pull/1694#pullrequestreview-399998300)
we no longer need this button. A separate PR will
contain the work needed to allow content designers to
publish the daily live stream url via this interface.

Hide the Update Live Stream button

---

app/controllers/coronavirus_controller.rb
app/models/live_stream.rb
app/presenters/coronavirus_page_presenter.rb
app/services/live_stream_updater.rb
app/validators/url_validator.rb
app/views/coronavirus/index.html.erb
app/views/coronavirus/live_stream.html.erb
config/routes.rb
db/migrate/20200424104605_add_url_to_live_stream.rb
db/migrate/20200424214202_remove_state_from_live_stream.rb
db/schema.rb
db/seeds.rb
spec/features/coronavirus_page_spec.rb
spec/fixtures/coronavirus_content_item.json
spec/models/live_stream_spec.rb
spec/presenters/coronavirus_page_presenter_spec.rb
spec/services/live_stream_updater_spec.rb
spec/support/coronavirus_feature_steps.rb

[trello](https://trello.com/c/PdKUXgfr/216-update-the-landing-page-publishing-tool-to-allow-content-designers-to-add-a-specific-youtube-url)
Once this is merged we can remove some keys from the [coronavirus landing page yaml](https://github.com/alphagov/govuk-coronavirus-content/blob/master/content/coronavirus_landing_page.yml)
https://github.com/alphagov/govuk-coronavirus-content/blob/5142f9c856d4e798a68fbcab2bfa40d94245218a/content/coronavirus_landing_page.yml#L236-L237
https://github.com/alphagov/govuk-coronavirus-content/blob/5142f9c856d4e798a68fbcab2bfa40d94245218a/content/coronavirus_landing_page.yml#L219-L220 we should probably leave these in but set the values to nil

Live stream url updater

---

app/controllers/coronavirus_controller.rb
app/presenters/coronavirus_page_presenter.rb
app/services/live_stream_updater.rb
db/migrate/20200429150108_add_formatted_stream_date_to_live_stream.rb
db/schema.rb
spec/features/coronavirus_page_spec.rb
spec/models/live_stream_spec.rb
spec/presenters/coronavirus_page_presenter_spec.rb
spec/services/live_stream_updater_spec.rb
spec/support/coronavirus_feature_steps.rb

This is follow up work to [the Live stream url updater PR](https://trello.com/c/PdKUXgfr/216-update-the-landing-page-publishing-tool-to-allow-content-designers-to-add-a-specific-youtube-url) which contains a bug.
**Bug**:
Updating the content item updated the value of livestream date in the payload for publishing api. 
**Fix**:
Persist the date of the live stream so that the field isn't overwritten each time the content item is updated. 
A remaining issue is that if someone updates the link to the livestream and makes a mistake, for example they publish yesterday's livestream again rather than today's live video, the date field is still programatically updated to todays date. So whilst we could reset the url, we can't easily undo the date change through the UI. We could add another text …

Store the livestream date 

---

app/controllers/coronavirus_controller.rb
spec/components/markdown_editor_spec.rb
spec/features/curating_topic_contents_spec.rb
spec/fixtures/coronavirus_landing_page.yml
spec/presenters/groups_presenter_spec.rb
spec/support/coronavirus_feature_steps.rb

We have [changed the structure](https://github.com/alphagov/govuk-coronavirus-content/pull/219) of the content item. The publishing tool needs to know about it.

Update coronavirus landing page publishing tool

---

app/views/coronavirus/live_stream.html.erb

We are currently linking to the No 10 YouTube account page.  From here, you click 'Videos'.  This takes you to a page that only has pre-recorded videos and not upcoming live streams.  This has to be selected from a drop-down, which has caused confusion on multiple occassions.
Therefore updating the URL to link directly to No 10's live stream page.

Link directly to live streams page for Coronavirus daily update

---

app/controllers/application_controller.rb
app/controllers/step_by_step_pages_controller.rb
app/helpers/step_nav_actions_helper.rb
app/views/step_by_step_pages/show/_actions.erb
config/routes.rb
db/seeds.rb
spec/controllers/step_by_step_pages_controller_spec.rb
spec/features/step_by_step_actions_spec.rb
spec/helpers/step_nav_actions_helper_spec.rb
spec/support/common_feature_steps.rb

This changes allows user's with the `Skip review` permission to publish Step by Step pages
without first receiving a "two eye" review from another content designer.
When permission is granted, a red "Publish without 2i" button is available on the Step by Step page, and the internal change note details if the change was made without review.
[Trello](https://trello.com/c/nRiaTxuK/2003-3-add-skip-review-permission-to-collections-publisher)

Allow users with permission to skip Step by Step 2i 

---

app/controllers/coronavirus_controller.rb

The paths here should match the file in https://github.com/alphagov/govuk-coronavirus-content/pull/275
https://trello.com/c/Pd19z0rM/326-add-employee-hub-configuration-to-collections-publisher

Add the worker support hub page

---

app/controllers/application_controller.rb
app/controllers/coronavirus_controller.rb
app/controllers/live_stream_controller.rb
app/views/coronavirus/index.html.erb
app/views/layouts/admin_layout.html.erb
app/views/layouts/application.html.erb
app/views/live_stream/index.html.erb
config/routes.rb
spec/features/access_control_spec.rb
spec/features/coronavirus_page_spec.rb
spec/features/live_stream_page_spec.rb
spec/services/live_stream_updater_spec.rb
spec/support/aaa_database_cleaner.rb
spec/support/coronavirus_feature_steps.rb
spec/support/livestream_helpers.rb
spec/support/navigation_steps.rb

Allow users with a new signon permission `Livestream editor` access to edit the daily livestream URL.
So that we can hand over control of updating the livestream URL to Cabinet Office/number 10.
Currently to edit the livestream you need both GDS editor and Coronavirus editor permissions:
- GDS Editor permissions required to access the landing page of Collections Publisher (root is step by step index page). 
- From landing page, navigate to Coronavirus Pages, which requires Coronavirus Editor permissions. 
- If user has only Livestream Editor permissions, accessing the app they will now be routed to the livestream edit page. 
- This is the only page they can access.
- Coronavirus editors accessing the app will see no change in their flow. …

Livestream can be updated with new signon permission

---

app/services/coronavirus_pages/updater.rb
app/views/coronavirus_pages/_accordion_summary_list.html.erb
spec/fixtures/coronavirus_landing_page.yml
spec/services/coronavirus_pages/updater_spec.rb

This work relates to the WIP coronavirus publishing tool.
- When we find or create our coronavirus page model, we should store the sections title as well.
- In the view, read the sections title from the database rather than hard coding it.

Store the accordion heading (aka section heading) 

---

app/assets/stylesheets/admin_layout.scss
app/assets/stylesheets/views/_coronavirus_manage_pages.scss
app/controllers/application_controller.rb
app/controllers/coronavirus_pages_controller.rb
app/models/coronavirus_page.rb
app/views/coronavirus_pages/index.html.erb
spec/controllers/coronavirus_pages_controller_spec.rb
spec/features/coronavirus_page_spec.rb
spec/features/live_stream_page_spec.rb
spec/models/coronavirus_page_spec.rb
spec/support/coronavirus_feature_steps.rb

Pair programming effort between @danacotoran and @hannako 
Frontend: Implement the design of the new index page for the coronavirus publishing tool.
Backend: Wire up the index page to read from database objects passed through from the controller.
https://trello.com/c/u16kFlyh

Re-style coronavirus index page

---

app/models/coronavirus_page.rb
app/services/coronavirus_pages/configuration.rb
app/views/coronavirus_pages/show.html.erb
db/migrate/20200623165045_add_state_to_coronavirus_pages.rb
db/schema.rb
spec/models/coronavirus_page_spec.rb
spec/services/coronavirus_pages/updater_spec.rb

Once we implement updating and publishing, we will need to store the state of the CoronavirusPage object. 
- Adding a column to the coronavirus_pages table
- Default state is draft
- Setting state to published for the existing landing and hub pages
Trello: https://trello.com/c/zNcOOclL/377-coronavirus-publishing-tool-update-draft-content-item

Coronavirus publishing tool: Add column state to CoronavirusPages

---

app/controllers/sub_sections_controller.rb
app/models/coronavirus_page.rb
app/models/sub_section.rb
app/views/shared/sub_sections/_form_errors.html.erb
app/views/sub_sections/_form.html.erb
app/views/sub_sections/edit.html.erb
app/views/sub_sections/new.html.erb
spec/models/coronavirus_page_spec.rb
spec/models/sub_section_spec.rb

Currently we allow invalid subsections to be saved to the database. Adding validations so that all subsections must have title, content, and a parent CoronavirusPage.
```
s = SubSection.create!
s.valid?
true
```
```
s = SubSection.create!
ActiveRecord::RecordInvalid (Validation failed: Title can't be blank, Content can't be blank, Coronavirus page can't be blank)
```
trello: https://trello.com/c/zNcOOclL/377-coronavirus-publishing-tool-update-draft-content-item

Coronavirus publishing tool: Add some validations to SubSections 

---

app/views/coronavirus_pages/index.html.erb

This change affects the corona virus index page subtopic links.
When the Edit accordion links are not there, the 2 by 2 spacing looks strange.
This ensures that the spaced list class is only applied when the Edit Accordions links are present
https://trello.com/c/u16kFlyh

Add ul spacing class conditionally

---

Gemfile
Gemfile.lock
app/controllers/step_by_step_pages_controller.rb
app/mailers/application_mailer.rb
app/mailers/publisher_notifications.rb
app/views/publisher_notifications/publish_without_2i.text.erb
config/application.rb
config/environments/production.rb
config/environments/test.rb
config/secrets.yml
spec/controllers/step_by_step_pages_controller_spec.rb
spec/features/managing_step_by_step_pages_spec.rb
spec/mailers/publisher_notifications_spec.rb

Adds Notify to Collections Publisher and adds an action to send an email when content has been published without 2i review so content teams can keep track of who is publishing without review as this should only happen in exceptional circumstances.
Depends on the below being merged:
Trello:
https://trello.com/c/NrZVDIlG/2018-3-alert-users-when-a-step-by-step-is-force-published-in-collections-publisher

Add Notify to collections publisher

---

app/views/step_by_step_pages/show/_actions.erb

This adds some guidance around when a publisher should publish without
2i when they hit the "Publish without 2i review" button. The
confirmation pop up follows the same pattern as some of the other
actions like 'delete' and 'revert to draft'.
The bulk of the text was copied from whitehall's 'Force publish' partial
here -> https://github.com/alphagov/whitehall/blob/master/app/views/admin/edition_workflow/_force_publish_modal.html.erb,
with a few words changed as there isn't a 'Force publish' concept in
collections-publisher.
Trello:
https://trello.com/c/NrZVDIlG/2018-3-alert-users-when-a-step-by-step-is-force-published-in-collections-publisher

Add confirmation banner when publishing without 2i

---

app/presenters/sub_section_json_presenter.rb
spec/presenters/sub_section_json_presenter_spec.rb

Update SubSectionJsonPresenter to flag featured links
- Matches link url to subtopic page base url
- If match marks link as featured_link
- And gets meta_description from raw content, to populate link description
Some of the links within the accordions have a featured_link flag in the content item, which renders a white arrow next to the link text. See attached screen shots.
We want to implement this feature within the collections publisher tool.

359 Automatically display hub page links with an arrow

---

app/controllers/sub_sections_controller.rb
app/presenters/sub_section_json_presenter.rb
app/services/coronavirus_pages/content_builder.rb
app/services/coronavirus_pages/draft_updater.rb
spec/controllers/coronavirus_pages_controller_spec.rb
spec/controllers/sub_sections_controller_spec.rb
spec/presenters/sub_section_json_presenter_spec.rb

- pair programming effort with @reggieb 
- Wire up the app to send changes to the coronavirus page database model to publishing api.
- Better reporting of errors to user
- Send errors to sentry.
[trello](https://trello.com/c/zNcOOclL/377-coronavirus-publishing-tool-update-draft-content-item)

Coronavirus page publishing tool: Send updates to publishing api

---

app/services/coronavirus_pages/draft_updater.rb
spec/controllers/sub_sections_controller_spec.rb
spec/features/coronavirus_page_spec.rb
spec/services/coronavirus_pages/draft_updater_spec.rb

- The CoronavirusPages::DraftUpdater should have been calling the
payload method on the presenter.
- Adds a spec so we don't mess up again.
https://sentry.io/organizations/govuk/issues/448130709/?project=202214&query=is%3Aunresolved

Coronavirus publishing tool: Correctly form payload

---

app/controllers/sub_sections_controller.rb
app/services/coronavirus_pages/draft_updater.rb
app/views/coronavirus_pages/_sub_sections_summary_list.html.erb
app/views/coronavirus_pages/show.html.erb
spec/controllers/sub_sections_controller_spec.rb

- Wire up the delete subsection button on the coronavirus show page
- If after deleting the subsection, publishing api fails to update the draft content item, we recreate the subsection in the database.
[trello](https://trello.com/c/3JOJVLT8/360-story-4-delete-sections-from-collections-publisher)

Coronavirus publishing tool: Delete sub_sections

---

app/presenters/coronavirus_page_presenter.rb
app/services/coronavirus_pages/content_builder.rb
app/services/live_stream_updater.rb
spec/controllers/sub_sections_controller_spec.rb
spec/factories.rb
spec/features/coronavirus_page_spec.rb
spec/presenters/coronavirus_page_presenter_spec.rb
spec/services/coronavirus_pages/content_builder_spec.rb
spec/services/coronavirus_pages/draft_updater_spec.rb
spec/support/coronavirus_feature_steps.rb

Move the logic that combines the livestream data into the payload for publishing api, out of the CoronavirusPagePresenter and into the ContentBuilder and LivestreamUpdater.
When we make content changes, we fetch the github yaml file, turn it into a hash and combine it with the coronaviruspage data persisted in the database. We should add the livestream data persisted in the database to the content hash as well, rather than doing that elsewhere in the code base. As that is the pattern that can be continued as we persist more and more parts of the github content into the collections publisher database.

Move livestream logic

---

app/views/components/_markdown_editor.html.erb
app/views/components/docs/markdown_editor.yml
app/views/sub_sections/_form.html.erb
spec/components/markdown_editor_spec.rb

- Extend markdown editor component with an option to hide the bullets button on the toolbar.
- Remove the bullets button from the markdown editor toolbar on the coronavirus accordion section editor form.
Markdown editor component with the bullets button vs without bullets button:
Users should not need to use this control in this particular instance, we are removing the button from the toolbar as an additional measure.  
https://trello.com/c/thetabg3

Hide markdown editor bullets button from covid accordion editor

---

app/helpers/application_helper.rb
app/views/step_by_step_pages/index/_results.erb
app/views/step_by_step_pages/show/_actions.erb
spec/helpers/application_helper_spec.rb

Trello: https://trello.com/c/IQ26eiaW/240-make-content-publisher-use-changing-auth-bypass-tokens
This token was defining the issuer (using the iss grant) with the uid of
the user who created this token, which was a rather general applying of
the issuer name.
The use of issuer should relate more to the organisation that is
issuing the token rather than the user that created it, such that this
issuer could be validated online [1].
The use of the user_id is also a little dubious as this could be
construed as personally identifiable information in some contexts and
JWTs are not encrypted (which is a common misconception). The simplest
thing is to just remove them from tokens.
I'm of the mindset that one day in some scenario it would have been very
useful to know the user_id of who issued a …

Remove incorrect issuer usage in JWT token

---

app/services/coronavirus_pages/content_builder.rb
spec/factories.rb
spec/fixtures/coronavirus_landing_page.yml
spec/services/coronavirus_pages/content_builder_spec.rb
spec/support/coronavirus_feature_steps.rb

When #1084 was merged, a bug was introduced. 
- Updating the livestream url was behaving as normal.
- Updating the page via the prepare action was removing the livestream content still stored in github from the content item
Combine livestream content currently stored in github, with the persisted livestream data, when we publish the landing page.

Coronavirus publishing tool: Form landing page content payload correctly

---

app/services/yaml_fetcher.rb
spec/controllers/coronavirus_pages_controller_spec.rb
spec/controllers/sub_sections_controller_spec.rb
spec/presenters/coronavirus_page_presenter_spec.rb
spec/presenters/sub_section_json_presenter_spec.rb
spec/services/coronavirus_pages/content_builder_spec.rb
spec/services/coronavirus_pages/draft_updater_spec.rb
spec/services/coronavirus_pages/model_builder_spec.rb
spec/services/yaml_fetcher_spec.rb
spec/support/coronavirus_feature_steps.rb

Github caches requests to the raw endpoint for 5 minutes (and it feels longer sometimes).  Adding a cache bust query parameter seems to defeat this, and will hopefully make repeated updates more reliable in the short term.
In the long term, the yaml is going to be less important as we're pulling this into the publishing tool.

Cache bust yaml fetch from Github

---

app/services/yaml_fetcher.rb

Resolves: https://sentry.io/organizations/govuk/issues/1772301843/?project=202214&query=is%3Aunresolved
This wasn't a problem in test/dev.

Add missing require

---

lib/tasks/coronavirus.rake

- Rake task to destroy all Coronavirus pages.
- If there are no coronavirus pages in the database, the first time https://collections-publisher.publishing.service.gov.uk/coronavirus is requested, we fetch all the content from github and create the coronavirus page models.
- Should be run once we are ready to make the tool live, before we remove the sections content from github, and then can be removed from the code base.
https://trello.com/c/NTcgcNwn/379-coronavirus-publishing-tool-resync-database-rake-task

Coronavirus Publishing tool rake task

---

app/assets/javascripts/admin_layout.js
app/assets/javascripts/sections.js
app/controllers/coronavirus_pages_controller.rb
app/controllers/reorder_sub_sections_controller.rb
app/services/coronavirus_pages/content_builder.rb
app/services/coronavirus_pages/model_builder.rb
app/views/coronavirus_pages/_sub_sections_summary_list.html.erb
app/views/coronavirus_pages/reorder.html.erb
app/views/reorder_sub_sections/_reorder_list.html.erb
app/views/reorder_sub_sections/index.html.erb
app/views/step_by_step_pages/reorder.html.erb
config/routes.rb
db/migrate/20200701141142_add_position_to_sub_section.rb
db/schema.rb
spec/controllers/coronavirus_pages_controller_spec.rb
spec/controllers/reorder_sub_sections_controller_spec.rb
spec/factories.rb
spec/features/coronavirus_page_spec.rb
spec/fixtures/simple_coronavirus_page.yml
spec/services/coronavirus_pages/content_builder_spec.rb
spec/services/coronavirus_pages/model_builder_spec.rb
spec/support/coronavirus_feature_steps.rb

Pair programming effort @danacotoran and @hannako 
Implements reordering of subsections (aka accordions)
**Frontend** 
- Implements accordion reordering following the existing [pattern established in step-by-step pages]( https://collections-publisher.integration.publishing.service.gov.uk/step-by-step-pages/87/reorder) 
- On the accordion reordering page [there is a form](https://github.com/alphagov/collections-publisher/pull/1063/files#diff-c9b3ce154ac76d4a02cb44e9c925ca34) with a `<input type="hidden" name="section_order_save" id="js_order_save" />` On page load (and whenever the items under `<ul id="js-reorder-group">` are moved up/down), the value of this hidden input is dynamically updated to reflect the positions of the items. 
- The value will look something like this …

Coronavirus publishing tool: Reordering subsections

---

app/helpers/coronavirus_page_helper.rb
app/models/coronavirus_page.rb
app/services/coronavirus_pages/model_builder.rb
app/views/coronavirus_pages/index.html.erb
app/views/coronavirus_pages/show.html.erb
db/migrate/20200707201559_add_title_to_coronavirus_page.rb
db/schema.rb
spec/support/coronavirus_feature_steps.rb

Replace hard coded strings with attributes stored on the coronavirus page model. 
- Store title field on the model
- Create helper to format the title to match the output on the [design](https://www.figma.com/file/92QVsy9eJOXdiULVrjQbEk/Coronavirus-topic-publisher?node-id=0%3A1)
trello: https://trello.com/c/6DHW4Wxx/413-persist-coronavirus-page-title

Coronavirus publishing tool: Persist titles

---

app/models/topic.rb
spec/presenters/archived_tag_presenter_spec.rb
spec/presenters/topic_presenter_spec.rb
spec/services/tag_archiver_spec.rb

These email subroutes get published when a Topic (specialist sector) is
published / republished. As part of the work to move these redirected
routes out of collections-publisher we need to stop publishing them in
the first place.
After this gets merged we should republish all the Topic's via https://github.com/alphagov/collections-publisher/blob/master/lib/tasks/publishing_api.rake#L12.
This will keep the publishing-api in sync.
---
Trello:
https://trello.com/c/Fi2Z2zDy/399-redirect-and-remove-legacy-email-signup-routes-for-collections

Stop publishing email-signup routes for Topic's

---

lib/tasks/redirect_legacy_email_signups.rake

Adds a temporary rake task to create redirects for specialist sector
email signup URL's.
The current behaviour is for these specialist sector email-signup URL's
to be sent to collections which then redirects to email-alert-frontend.
This commit creates a redirect for each specialist sector email signup
URL which points to the relevant parent page rendered by collections.
Depends on:
https://github.com/alphagov/collections-publisher/pull/1102
---
Trello:
https://trello.com/c/Fi2Z2zDy/399-redirect-and-remove-legacy-email-signup-routes-for-collections

Add temp rake task to redirect legacy signups

---

app/controllers/coronavirus_pages_controller.rb
app/helpers/coronavirus_page_helper.rb
app/services/coronavirus_pages/configuration.rb
app/services/coronavirus_pages/draft_updater.rb
app/views/coronavirus_pages/index.html.erb
app/views/coronavirus_pages/prepare.html.erb
app/views/coronavirus_pages/show.html.erb
app/views/reorder_sub_sections/index.html.erb
app/views/sub_sections/_form.html.erb
app/views/sub_sections/edit.html.erb
app/views/sub_sections/new.html.erb
spec/factories.rb
spec/models/coronavirus_page_spec.rb
spec/support/coronavirus_feature_steps.rb

Content designers on Coronavirus Content reviewed the tool and asked for changes to labelling and error message. Here is the [doc](https://docs.google.com/document/d/1aa-C5EEJwmI5bcJ50C26wu4rbW9Z4t8GJbzT7pmOAxI/edit) with requested changes.

Coronavirus publishing tool: Copy changes following review.

---

app/controllers/application_controller.rb
app/controllers/coronavirus_pages_controller.rb
app/controllers/reorder_sub_sections_controller.rb
app/controllers/sub_sections_controller.rb
app/views/coronavirus_pages/index.html.erb
spec/controllers/coronavirus_pages_controller_spec.rb
spec/controllers/reorder_sub_sections_controller_spec.rb
spec/controllers/sub_sections_controller_spec.rb
spec/factories.rb
spec/features/coronavirus_page_spec.rb
spec/support/coronavirus_feature_steps.rb

Remove checks for Unreleased feature signon permission that currently hide the new tools features.
https://trello.com/c/DU5dRL03/415-remove-feature-flag-hiding-the-coronavirus-publishing-tool

Coronavirus publishing tool: remove feature flag

---

app/controllers/sub_sections_controller.rb
app/models/sub_section.rb
app/presenters/sub_section_json_presenter.rb
app/services/coronavirus_pages/sections_presenter.rb
app/services/coronavirus_pages/sub_section_processor.rb
app/views/sub_sections/_form.html.erb
db/migrate/20200813094514_add_featured_link_to_sub_sections.rb
db/schema.rb
spec/controllers/sub_sections_controller_spec.rb
spec/presenters/sub_section_json_presenter_spec.rb
spec/services/coronavirus_pages/sections_presenter_spec.rb
spec/services/coronavirus_pages/sub_section_processor_spec.rb

Trello: https://trello.com/c/7Li6NbQr
Add an input field to the accordion page to allow users to mark one of the links featured in the content as a "featured" link. In the frontend application, links that have "featured_link" set to true automatically have special styling applied to them (the arrow head).
Add a "featured_link" attribute for a sub_section. This "featured_link" should contain the path to a page on GOV.UK. 
Also adds validations to make sure that the "featured_link" appears in the body content of the accordion.
Finally, the discard draft action has been updated to allow any changes to the featured link to be reverted with the rest of the draft changes.
At the moment the featured link is generate automatically if a topic link is included in the accordion.
We need the ability …

Allow users to set a link as a "featured link" in an accordion

---

lib/special_route_publisher.rb

[We're getting errors](https://sentry.io/organizations/govuk/issues/1884114207/?environment=production&project=202213&referrer=slack) because router is sending sub paths of /eubusiness to collections. We only have the /eubusiness page right now, so an exact route is the way to go.
I'll check about removing the prefix route once this is republished.
https://trello.com/c/aRd8ha9V/437-fix-app-error-in-collections

Change /eubusiness to an exact route

---

app/models/announcement.rb
app/models/coronavirus_page.rb
db/migrate/20200911084908_create_announcements.rb
db/schema.rb
spec/factories.rb
spec/models/announcement_spec.rb

Adds announcements model and migration.
This is part of the work to make the /coronavirus announcements section
publishable solely via this application as opposed to editing the YAML
in Github.
Has basic validation to check presence of fields, will add further
validation in future PR when adding the form.
Co-authored-by: @Rosa-Fox
[Trello](https://trello.com/c/7sOyvOmE/797-create-announcements-table)

Add announcements table

---

Gemfile
Gemfile.lock
app/services/coronavirus_pages/content_builder.rb
app/services/markdown_service.rb
spec/fixtures/coronavirus_landing_page.yml
spec/services/coronavirus_pages/content_builder_spec.rb
spec/services/markdown_service_spec.rb

Trello: https://trello.com/c/jdBmdPef
Follows on from: PR #1128 
Allow users to find the landing page by searching for timeline content in the GOV.UK site search.
At the moment only the content in the accordions on the landing and hub pages are being indexed in search.
It's likely that the content that appears in the timeline might not be repeated anywhere else on GOV.UK, so we need to give users a way to find it.
The landing and page will need to be republished for these changes to  take effect.

Index timeline content in search

---

app/presenters/sub_section_json_presenter.rb
app/services/coronavirus_pages/content_builder.rb
app/services/coronavirus_pages/sub_section_processor.rb
spec/factories.rb
spec/fixtures/coronavirus_page_sections.json
spec/services/coronavirus_pages/content_builder_spec.rb
spec/services/coronavirus_pages/model_builder_spec.rb
spec/services/coronavirus_pages/sub_section_processor_spec.rb
spec/support/coronavirus_feature_steps.rb

Update the payload for publishing-api by adding the preferred content-id as a query parameter "priority-taxon"
This is needed as there are cases where the content can be referenced from multiple places, so we want to be able to trace back to the content they linked from. Using the query parameter we can tell the superbreadcrumb which content it should link back to.
https://trello.com/c/Kdnp9TPC/761-spike-conditional-super-breadcrumb-based-on-which-hub-a-user-has-come-from

Superbreadcrumbs query parameters

---

config/initializers/gds_sso.rb

This file is no longer required as the latest release of the gds-sso gem sets these defaults itself ref: alphagov/gds-sso#241

Remove redundant GDS SSO initialiser

---

app/controllers/reorder_announcements_controller.rb
app/models/announcement.rb
app/models/coronavirus_page.rb
app/views/coronavirus_pages/_announcements.html.erb
app/views/reorder_announcements/_reorder_list.html.erb
app/views/reorder_announcements/index.html.erb
config/routes.rb
db/migrate/20200925123542_add_position_to_announcements.rb
db/schema.rb
spec/controllers/reorder_announcements_controller_spec.rb
spec/features/coronavirus_page_spec.rb
spec/models/announcement_spec.rb
spec/support/coronavirus_feature_steps.rb

Trello: https://trello.com/c/LgmLXbqZ
Allow users to reorder announcements in the Announcements section of the Coronavirus landing page.
The work to update publishing-api with the new order will be done in a separate commit.

Add a reorder page for announcements

---

app/services/coronavirus_pages/announcements_builder.rb
lib/tasks/coronavirus.rake
spec/fixtures/coronavirus_landing_page.yml
spec/services/coronavirus_pages/announcements_builder_spec.rb

Trello: https://trello.com/c/ODT9KYZB
Adds a task to get the existing announcements from the [YAML file](https://github.com/alphagov/govuk-coronavirus-content/blob/master/content/coronavirus_landing_page.yml) and store them in the database.
1. Run the task:
```
$ govuk-docker-run bundle exec rake coronavirus:sync_announcements
```
2. Open console:
```
$ govuk-docker-run bundle exec rails c
```
3. You should see three announcements in the DB:
```
> coronavirus_page = CoronavirusPage.find_by(slug: "landing")
> coronavirus_page.announcements.count
```

Sync announcements from govuk-coronavirus-content to collections-publisher

---

app/services/coronavirus_pages/model_builder.rb

Trello: https://trello.com/c/4i8Qmhpn
The "discard draft" action was failing. All of the subsections were being removed, but they were not being replaced by the entries in publishing-api. This change fixes that.
Error:
```
{"exception_class":"ActiveRecord::RecordNotSaved","exception_message":"Failed to replace sub_sections because one or more of the new records could not be saved.","stacktrace":["app/services/coronavirus_pages/model_builder.rb:40:in `store_live_subsections'","app/services/coronavirus_pages/model_builder.rb:23:in `discard_changes'","app/controllers/coronavirus_pages_controller.rb:64:in `discard_model_changes'","app/controllers/coronavirus_pages_controller.rb:39:in `discard'"]}
```
I'm don't know why storing the new sub_sections in variable before saving in the database …

Bug Fix: Sub-sections are deleted and not replaced when the draft is discarded

---

.github/dependabot.yml
.scss-lint.yml
Gemfile
Gemfile.lock
Jenkinsfile
Rakefile
app/assets/javascripts/admin_layout.js
app/assets/javascripts/application.js
app/assets/javascripts/components/autocomplete.js
app/assets/javascripts/curated_lists.js
app/assets/javascripts/ordered_lists.js
app/assets/javascripts/publishing.js
app/assets/javascripts/sections.js
app/assets/stylesheets/_curated_lists.scss
app/assets/stylesheets/_forms.scss
app/assets/stylesheets/_steps.scss
app/assets/stylesheets/_topics.scss
app/assets/stylesheets/components/_autocomplete.scss
app/assets/stylesheets/objects/_broken-link-status.scss
app/assets/stylesheets/utilities/_overrides.scss
app/assets/stylesheets/views/_mainstream_browse_pages.scss
lib/tasks/lint.rake
package.json
spec/javascripts/components/steps-spec.js
yarn.lock

Trello: https://trello.com/c/MeG1zc2m/195-roll-out-stylelint-config-gds-across-govuk
This removes Ruby Sass from this application by switching to [stylelint-config-gds](https://github.com/alphagov/stylelint-config-gds) and applies fixes/ignore rules to embrace this linter. It also adds in standardx for JS linting, there was previously no JS linting.
More info in the commits...

Switch scss-lint to stylelint and use standardx to lint JS

---

app/presenters/step_nav_presenter.rb
spec/presenters/step_nav_presenter_spec.rb

We want step content to be indexed by search so we can find these pages more easily. Search-api can understand html, and steps are written in markdown.
We therefore want render all the step content and titles as html, not for public consumption, but so that search can index the page content.
I've tried to present the output fairly verbosely with plenty of space between sections. Fully fledged step by step pages are quite chunky, and should we experience problems it'd be nice to be able to view this bit in a debugger without it just being a mass of html.
https://trello.com/c/rsiS0jZ6/516-improve-visibility-of-import-export-step-by-steps-in-site-search

Include step content in the body field

---

app/controllers/announcements_controller.rb
app/helpers/date_format_helper.rb
app/helpers/error_items_helper.rb
app/models/announcement.rb
app/presenters/announcement_json_presenter.rb
app/services/coronavirus_pages/announcements_builder.rb
app/services/coronavirus_pages/content_builder.rb
app/services/coronavirus_pages/draft_discarder.rb
app/views/announcements/_form.html.erb
app/views/announcements/new.html.erb
app/views/coronavirus_pages/_announcements.html.erb
app/views/coronavirus_pages/index.html.erb
app/views/reorder_announcements/_reorder_list.html.erb
app/views/shared/sub_sections/_form_errors.html.erb
db/migrate/20201124144059_change_column_names.rb
db/schema.rb
spec/controllers/announcements_controller_spec.rb
spec/factories.rb
spec/features/coronavirus_page_spec.rb
spec/fixtures/coronavirus_landing_page_with_announcements.yml
spec/fixtures/coronavirus_page_sections.json
spec/helpers/date_format_helper_spec.rb
spec/helpers/error_items_helper_spec.rb
spec/models/announcement_spec.rb
spec/presenters/announcement_json_presenter_spec.rb
spec/presenters/coronavirus_page_presenter_spec.rb
spec/services/coronavirus_pages/announcements_builder_spec.rb
spec/services/coronavirus_pages/content_builder_spec.rb
spec/services/coronavirus_pages/draft_discarder_spec.rb
spec/support/coronavirus_feature_steps.rb

**We want to be able to add an announcement via the UI.**
**This PR adds a button to the /coronavirus/landing page that enables a user to add an announcement via a form.** 
There was no formal design for this form, instead we adopted a style similar to the 'Edit guidance section` example on the [figma design](https://www.figma.com/file/92QVsy9eJOXdiULVrjQbEk/Coronavirus-topic-publisher?node-id=0%3A1).
There is still work to do on this including the edit and delete announcement actions, which will follow in subsequent PRs. Until then we have hidden the announcements view behind an unreleased feature flag requirement so it should only be accessible to those with the appropriate permissions 
We have tested that new announcements persist to the database,  and that the draft content is sent to …

Create announcement using the UI

---

app/services/coronavirus_pages/content_builder.rb
spec/fixtures/simple_coronavirus_page.yml

Until we are ready to go live with the announcements section and import the existing
announcements from the Github to the database, we need to make sure that we are still
sending announcements to publishing-api correctly.
When we [updated the DraftUpdater](https://github.com/alphagov/collections-publisher/commit/52e8fc1e31ca5b2a3140be54ad10baf7f80f9c19#) to get the announcements from the
database we inadvertently removed the announcements from the publishing-api.
This is because the assignment `data["announcements"] = announcements_data` overwrites
the announcements pulled in from the github data, but at the moment there is nothing to replace it
with.
To get the tests to work, we need to update the fixture to not return any announcements. This is so that
it matches the assertion in step …

Continue to get announcements from YAML

---

app/views/announcements/_form.html.erb

Trello: https://trello.com/c/dYuQSgk7
Form fields are pre-populated with user's input when the create announcement form is submitted and fails validation. Previously if the user filled any of the fields out incorrectly, the submitted data disappeared for all of the other fields, even though those fields did not fail validation.
Better user experience! It is annoying to have to fill the whole form out again if only one field was incorrect.

Keep existing user input on error

---

app/controllers/announcements_controller.rb
app/views/announcements/edit.html.erb
app/views/coronavirus_pages/_announcements.html.erb
spec/controllers/announcements_controller_spec.rb
spec/features/coronavirus_page_spec.rb
spec/support/coronavirus_feature_steps.rb

[Trello](https://trello.com/c/MLHLiI8L/800-edit-an-announcement-using-the-ui)
- Announcements are editable via the user interface.
- Draft content is sent to the publishing api.

Edit announcement

---

.github/pull_request_template.md
app/controllers/healthcheck_controller.rb
app/controllers/list_items_controller.rb
config/routes.rb
lib/special_route_publisher.rb
spec/controllers/healthcheck_controller_spec.rb
spec/controllers/list_items_controller_spec.rb
spec/lib/special_route_publisher_spec.rb

This PR brings Collections Publisher in line with the safety criteria defined in [RFC 128](https://github.com/alphagov/govuk-rfcs/blob/master/rfc-128-continuous-deployment.md) and enables Continuous Deployment.
Specifically, it adds:
- a 'healthcheck' endpoint
- a bunch of missing tests, bringing the code coverage above 95%
- a PR template warning about Continuous Deployment.

Prepare for Continuous Deployment

---

app/controllers/healthcheck_controller.rb

Follow on from #1199. Smokey needs to be able to access the healthcheck endpoint without authenticating.

Skip authentication on healthcheck endpoint

---

app/controllers/announcements_controller.rb
app/controllers/reorder_announcements_controller.rb
app/services/coronavirus_pages/content_builder.rb
app/views/coronavirus_pages/index.html.erb
app/views/coronavirus_pages/show.html.erb
spec/controllers/announcements_controller_spec.rb
spec/controllers/reorder_announcements_controller_spec.rb
spec/features/coronavirus_page_spec.rb

Trello: https://trello.com/c/ekjW492n
We're ready to make the announcements section, so we need to remove the "Unreleased feature" feature flag.

Make announcements section live

---

spec/lib/tasks/publishing_api_spec.rb

Fixes error:
```
1) rake publishing_api:publish_special_route finds a configured route by base path and publishes it
Failure/Error: @publisher.publish(default_options.merge(route))
The message 'publish' was received by #<GdsApi::PublishingApi::SpecialRoutePublisher:183300 @logger=#<ActiveSupport::Logger:0x0000562df0dbd908>, @publishing_api=#<GdsApi::PublishingApi:0x0000562df08b0e10>> but has already been received by #<GdsApi::PublishingApi::SpecialRoutePublisher:0x0000562df70125e0>
Finished in 1 minute 39.33 seconds (files took 16.95 seconds to load)
920 examples, 1 failure
Failed examples:
rspec ./spec/lib/tasks/publishing_api_spec.rb:10 # rake publishing_api:publish_special_route finds a configured route by base path and publishes it
```
⚠️ This repo is Continuously Deployed: make sure …

Fix failing Special Route Publisher rake test

---

lib/special_route_publisher.rb

The the logger wasn't being stubbed in the tests that call Special Router Publisher
GdsApi adapter method.
That mean't the first test that ran passed, but the second test fails with:
```
1) rake publishing_api:publish_special_route finds a configured route by base path and publishes it
Failure/Error: @publisher.publish(default_options.merge(route))
The message 'publish' was received by #<GdsApi::PublishingApi::SpecialRoutePublisher:227700 @logger=#<ActiveSupport::Logger:0x0000559f9afaea08>, @publishing_api=#<GdsApi::PublishingApi:0x0000559f9e5b92d8>> but has already been received by #<GdsApi::PublishingApi::SpecialRoutePublisher:0x0000559f9f870cf0>
Finished in 1 minute 49.86 seconds (files took 17.42 seconds to load)
920 examples, 1 failure
```
If a logger isn't passed in, GdsApi adapters …

Use default logger in Special Route publishing

---

app/services/coronavirus_pages/draft_discarder.rb
spec/fixtures/coronavirus_page_sections.json

Trello: https://trello.com/c/xN4yagBW
Discarding announcements was failing with this error:
[975bd1ce-869d-4e73-b234-d399b0ab70e2] {"exception_class":"ActiveRecord::RecordNotSaved","exception_message":"Failed to replace announcements because one or more of the new records could not be saved.","stacktrace":["app/services/coronavirus_pages/draft_discarder.rb:23:in `update_announcements'","app/services/coronavirus_pages/draft_discarder.rb:14:in `block in call'","app/services/coronavirus_pages/draft_discarder.rb:12:in `call'","app/controllers/coronavirus_pages_controller.rb:39:in `discard'"]}
When the name of the columns in the Announcements table changed to no longer match the
field names from publishing-api, it looks like fields from publishing-api where also accidentally
replaced.
⚠️ This …

Fix error when discarding draft announcements

---

spec/lib/special_route_publisher_spec.rb
spec/lib/tasks/publishing_api_spec.rb

The `#publish` test in special_route_publisher_spec.rb is very similar to the spec for the publishing_api rake tasks in lib/tasks/publishing_api_spec.rb. As both tests stub the same call, the [CI](https://ci.integration.publishing.service.gov.uk/job/collections-publisher/job/master/1061/console) is intermittently failing. 
- Refactor the rake task spec to check if publishing api receives the call to put and publish, rather than assert that the specialist publisher receives it.
- Add a test for find_route to the special_route_publisher_spec.rb

Tidy up specialist publisher tests

---

spec/lib/tasks/publishing_api_spec.rb
spec/lib/tasks/set_step_by_step_status_spec.rb
spec/rails_helper.rb

Each time `load_tasks` is run it’ll multiply the task so, as the line was in
two test files, whichever run first would pass, and the other would fail with:
```
The request PUT https://publishing-api.test.gov.uk/v2/content/bb986a97-3b8c-4b1a-89bf-2a9f46be9747 with given block was expected to execute 1 time but it executed 6 times
```
Hopefully this fixes it.

Fix flaky test

---

app/services/coronavirus_pages/content_builder.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
spec/controllers/announcements_controller_spec.rb
spec/controllers/reorder_sub_sections_controller_spec.rb
spec/controllers/sub_sections_controller_spec.rb
spec/presenters/coronavirus_page_presenter_spec.rb
spec/services/coronavirus_pages/draft_updater_spec.rb

Trello: https://trello.com/c/gzWPC4LU
The announcements UI was being hidden behind a user permission
"Unreleased feature" to stop them seeing and interacting with
announcements, however there was nothing to stop the backend code from
running.
This caused problems recently where the announcements section was
removed [1] in live because the code to populate publishing-api was
looking for the announcements in the wrong place. We added a flag to
check if there are any existing announcements to get around the problem
but since found that this had a knock-on effect when drafts are
discarded.
When the draft is discarded, announcements are retrieved from
publishing-api and populated in the database. As the local database had
announcements, any changes made to the announcements section via Github …

Add feature flag for backend code

---

app/services/coronavirus_pages/content_builder.rb
spec/controllers/announcements_controller_spec.rb
spec/controllers/reorder_sub_sections_controller_spec.rb
spec/controllers/sub_sections_controller_spec.rb
spec/presenters/coronavirus_page_presenter_spec.rb
spec/services/coronavirus_pages/draft_updater_spec.rb

Trello: https://trello.com/c/1YohbtSc
Adds a guard so that the merging of live stream data doesn't fail if the
database doesn't contain a live stream.
The live stream is an optional component on the coronavirus landing
page, and there hasn't been a live stream in months.
However the code expected there to be at least one live stream in the
database.
Adding the guard means that we no longer have to create an unnecessary
live stream object to test things like announcements and sub_sections.

Remove need for at least one live stream in db

---

app/models/coronavirus_page.rb
app/models/timeline_entry.rb
db/migrate/20210104141058_create_timeline_entries.rb
db/schema.rb
spec/factories.rb
spec/models/timeline_entry_spec.rb

We need somewhere to store the timeline entries from the coronavirus_landing_page.yml within the publishing application.
It turns out that rails can handle pluralizing ‘entry’ to ‘entries’ so we shouldn’t have to specify the association between the model and the table
Has basic validation to check presence of the heading and content fields. These fields don't currently match the fields in publishing-api, but that doesn't matter right now. We can do the mapping later when it's time to update the payload to publishing-api.
Currently there is no check for the presence of a 'position' value, nor is there a way of assigning a 'position' value. This will need to be addressed in subsequent work as the table will not accept a null value for 'position'. I have not set a default value for position …

Add Timeline entry model and migration.

---

app/models/timeline_entry.rb
db/migrate/20210108140318_change_timeline_entries_content_type.rb
db/schema.rb
spec/models/timeline_entry_spec.rb

We created this model with a DB column type of string, which in MySQL equates to a VARCHAR of max length 255. This causes us a problem as the current value we have in the timeline content is 679 characters. To resolve this I've switched the type to be text which has a max length of 64 KB.
I felt that there wasn't a real need for the heading field to be greater than 255 characters, so I haven't changed that. However it did seem a sufficiently small length that it could catch a user out, so I've added a validation. I didn't think there was much chance of a user being caught out with the 64KB content field so I …

Change TimelineEntry#contents type and validate heading length

---

app/services/coronavirus_pages/content_builder.rb
app/services/coronavirus_pages/draft_discarder.rb
spec/fixtures/coronavirus_page_sections.json
spec/services/coronavirus_pages/content_builder_spec.rb
spec/services/coronavirus_pages/draft_discarder_spec.rb
spec/support/coronavirus_feature_steps.rb

Trello: https://trello.com/c/0sxftxEF/1007-push-timeline-changes-to-publishing-api
This adds in the ability for timeline entries from the DB to be sent to the Publishing API. This is currently behind the `unreleased_features` flag so will not impact production where the YAML file will still be used. This also updates the draft discarder which I assumed was part of this task.
Screenshot of this working from integration:
A couple of pain points were: TimelineEntry and Publishing API use different naming for the content of an entry. Timeline entry uses "contents" and Publishing API already has "paragraph" which adds …

Send DB timeline entries to Publishing API

---

app/controllers/timeline_entries_controller.rb
app/views/components/_markdown_editor.html.erb
app/views/components/docs/markdown_editor.yml
app/views/steps/_form.html.erb
app/views/sub_sections/_form.html.erb
app/views/timeline_entries/_form.html.erb
app/views/timeline_entries/new.html.erb
config/application.rb
config/routes.rb
db/migrate/20210111110154_change_position_to_null.rb
db/schema.rb
spec/components/markdown_editor_spec.rb
spec/controllers/timeline_entries_controller_spec.rb
spec/features/coronavirus_page_spec.rb
spec/support/coronavirus_feature_steps.rb

Trello: https://trello.com/c/Gqe4lgaI
Create a page to allow new timeline entries to be stored in the database. 
Changes the markdown editor component to allow users to see the full range of menu options, whilst keeping the existing menu restrictions on the "step" and "sub-section" edit pages.
Only users with "Unreleased feature" permissions should be able to access the page whilst the timeline feature is being built.
The timeline entry is only persisted to the database. Whilst we are calling `DraftUpdater`, to send changes to the publishing-api, the actual creation of the payload for publishing-api will happen in another story.
URL of page: http://collections-publisher.dev.gov.uk/coronavirus/landing/timeline_entries/new
Error messages:
⚠️ This repo is Continuously Deployed: make sure you …

Add create timeline page

---

app/controllers/timeline_entries_controller.rb
app/views/timeline_entries/edit.html.erb
config/routes.rb
spec/controllers/timeline_entries_controller_spec.rb
spec/features/coronavirus_page_spec.rb
spec/support/coronavirus_feature_steps.rb

Trello: https://trello.com/c/8Kn2hKnd
Create a page to allow existing timeline entries to be edited.
Only users with "Unreleased feature" permissions should be able to access the page whilst the timeline feature is being built.
The changes to the timeline entry is only persisted to the database. Whilst we are calling DraftUpdater, to send changes to the publishing-api, the actual creation of the payload for publishing-api will happen in another story.
URL of page: `http://collections-publisher.dev.gov.uk/coronavirus/landing/timeline_entries/<timeline-entry-id>/edit`

Add page to edit timeline entries

---

app/views/coronavirus_pages/_actions.html.erb
app/views/coronavirus_pages/_announcements.html.erb
app/views/coronavirus_pages/_sub_sections.html.erb
app/views/coronavirus_pages/index.html.erb
app/views/coronavirus_pages/prepare.html.erb
app/views/coronavirus_pages/shared/_draft.html.erb
app/views/coronavirus_pages/shared/_github.html.erb
app/views/coronavirus_pages/shared/_live.html.erb
app/views/coronavirus_pages/shared/_preview.html.erb
app/views/coronavirus_pages/shared/_publish.html.erb
app/views/coronavirus_pages/show.html.erb
config/locales/en.yml

This moves the copy for announcements and sub sections into the en locale file. This will make it easier to keep track of.
There won't be any frontend changes with this, users won't notice a difference.
Trello - https://trello.com/c/0Nm1iIcz/973-put-content-for-coronavirus-publishing-tool-subsections-and-announcements-into-an-en-locale-file

Internationalise announcements and subsections

---

app/assets/stylesheets/views/_coronavirus_manage_pages.scss
app/views/coronavirus_pages/_announcements.html.erb
app/views/coronavirus_pages/_sub_sections.html.erb
app/views/coronavirus_pages/_timeline_entries.html.erb
app/views/coronavirus_pages/show.html.erb
app/views/reorder_announcements/_reorder_list.html.erb
app/views/reorder_sub_sections/_reorder_list.html.erb
spec/features/coronavirus_page_spec.rb
spec/support/coronavirus_feature_steps.rb

Display the new timeline entries section on /coronavirus/landing page in Collections Publisher.
The `Add timeline entry`, `change`, `delete`, `reorder` links don't go to anywhere yet. That functionality will be added in follow up PRs.
This section has been hidden behind the unreleased feature flag until the whole timeline entry feature is ready.
[Trello](https://trello.com/c/5BFwTEHk/1008-display-timeline-entries-on-the-summary-page-for-the-coronavirus-landing-page)

Display timeline entries

---

app/models/coronavirus_page.rb
app/models/timeline_entry.rb
app/services/coronavirus_pages/draft_discarder.rb
db/migrate/20210126122043_change_position_to_not_null.rb
db/schema.rb
spec/factories.rb
spec/fixtures/coronavirus_page_sections.json
spec/models/timeline_entry_spec.rb
spec/services/coronavirus_pages/draft_discarder_spec.rb

Trello: https://trello.com/c/0oeC49ub
Add new timeline entries to the front of the list (i.e. position 1) so that content designers can be sure that the order of the entries they see in the publishing tool matches the order of the timeline entries shown to the user.
For example, a content designer might add an entry for  "2 January", and later add an entry for "24 - 26 January". By default we need to display these entries in this order:
"24 -26 January"
"2 January"
A page to allow users to reorder timeline entries will be added in a later PR.
Paired with @Rosa-Fox 

Add new timeline entries front of list

---

spec/features/coronavirus_page_spec.rb
spec/support/coronavirus_feature_steps.rb

Trello: https://trello.com/c/W4nJDLBi
When the add and edit timeline pages where created, the timeline section
hadn't been added to the summary page. Now that the timeline section
exists, the feature tests can be updated to properly represent the user
journey / experience.

Update feature tests for add / edit timeline entry

---

app/presenters/sub_section_json_presenter.rb
spec/presenters/sub_section_json_presenter_spec.rb

Trello: https://trello.com/c/a8aT8ExJ/1051-allow-featured-links-in-accordions-to-link-to-external-links
We want to allow content designers to feature links that are to external
website (such as NHS). This was previously blocked due to needing to
pull a description from the Publishing API which required a relative
path. This adds a guard clause that doesn't pull in description for an
absolute link
It also does some refactoring to introduce the extra test so that they
are more succinct.
Co-authored-by: Alex Newton <alex.newton@digital.cabinet-office.gov.uk>
Co-authored-by: Rosa Fox <rosa.fox@digital.cabinet-office.gov.uk>
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-reque …

Only set featured link descriptions for relative links

---

app/controllers/reorder_announcements_controller.rb
app/controllers/reorder_sub_sections_controller.rb
app/controllers/reorder_timeline_entries_controller.rb
app/models/announcement.rb
app/views/coronavirus_pages/_timeline_entries.html.erb
app/views/reorder_timeline_entries/_reorder_list.html.erb
app/views/reorder_timeline_entries/index.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/announcements_controller_spec.rb
spec/controllers/reorder_announcements_controller_spec.rb
spec/controllers/reorder_sub_sections_controller_spec.rb
spec/controllers/reorder_timeline_entries_controller_spec.rb
spec/controllers/sub_sections_controller_spec.rb
spec/controllers/timeline_entries_controller_spec.rb
spec/features/access_control_spec.rb
spec/features/coronavirus_page_spec.rb
spec/features/live_stream_page_spec.rb
spec/presenters/announcement_json_presenter_spec.rb
spec/presenters/coronavirus_page_presenter_spec.rb
spec/services/coronavirus_pages/draft_updater_spec.rb
spec/services/live_stream_updater_spec.rb
spec/support/coronavirus_feature_steps.rb
spec/support/coronavirus_helpers.rb

Follows on from PR #1253
Trello: https://trello.com/c/d1it4WEP
Creates a page to allow content designers to reorder timeline entries using the UI.
This follows the existing pattern (design) for the other reorder pages (i.e. announcements and sub-sections)

Add a reorder page for timeline entries

---

app/controllers/announcements_controller.rb
app/controllers/sub_sections_controller.rb
app/controllers/timeline_entries_controller.rb
app/services/coronavirus_pages/draft_updater.rb
app/views/coronavirus_pages/_timeline_entries.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/announcements_controller_spec.rb
spec/controllers/sub_sections_controller_spec.rb
spec/controllers/timeline_entries_controller_spec.rb
spec/features/coronavirus_page_spec.rb
spec/support/coronavirus_feature_steps.rb

Trello: https://trello.com/c/rwtOUXAZ
Allow users to delete a timeline entry from the summary page.

Delete timeline entries

---

app/services/coronavirus_pages/timeline_entry_builder.rb
lib/tasks/coronavirus.rake
spec/services/coronavirus_pages/timeline_entry_builder_spec.rb

This adds a rake task to sync timeline entries with the database. Borrows heavily from [previous work](https://github.com/alphagov/collections-publisher/commit/116f59fcdd61e8bbd3a4a301e8ed366fee03b7ab) to do similar work for announcements.
Trello - https://trello.com/c/Hlr7PxjA/1050-migrate-timeline-entries-from-govuk-coronavirus-content-to-collections-publisher

Add rake task to sync timeline entries

---

config/locales/en.yml

- Previously timeline entry content was updated via YML fetched from Github.
- Updates link text to inform the user that timeline entries can be edited using the publishing tool.
[Trello](https://trello.com/c/IvPyOzow/1062-make-publishing-timeline-entries-via-the-publishing-tool-live)
Merge after: https://github.com/alphagov/collections-publisher/pull/1261 

Update /coronavirus/landing link text

---

app/controllers/reorder_timeline_entries_controller.rb
app/controllers/timeline_entries_controller.rb
app/services/coronavirus_pages/content_builder.rb
app/views/coronavirus_pages/show.html.erb
spec/controllers/reorder_timeline_entries_controller_spec.rb
spec/controllers/timeline_entries_controller_spec.rb
spec/features/coronavirus_page_spec.rb
spec/services/coronavirus_pages/content_builder_spec.rb

Trello: https://trello.com/c/IvPyOzow
Remove the unreleased features flag for timeline entries to make the feature live.

Make timeline entries "live"

---

app/controllers/coronavirus/announcements_controller.rb
app/controllers/coronavirus/coronavirus_pages_controller.rb
app/controllers/coronavirus/reorder_announcements_controller.rb
app/controllers/coronavirus/reorder_sub_sections_controller.rb
app/controllers/coronavirus/reorder_timeline_entries_controller.rb
app/controllers/coronavirus/sub_sections_controller.rb
app/controllers/coronavirus/timeline_entries_controller.rb
app/services/coronavirus/pages/configuration.rb
app/services/coronavirus/pages/content_builder.rb
app/services/coronavirus/pages/draft_discarder.rb
app/services/coronavirus/pages/draft_updater.rb
app/services/coronavirus/pages/model_builder.rb
app/services/coronavirus/pages/sections_presenter.rb
app/services/coronavirus/pages/sub_section_processor.rb
app/services/coronavirus/pages/timeline_entry_builder.rb
docs/coronavirus_page_publishing_tool.md
lib/tasks/coronavirus.rake
spec/controllers/coronavirus/coronavirus_pages_controller_spec.rb
spec/presenters/coronavirus_page_presenter_spec.rb
spec/services/coronavirus/pages/content_builder_spec.rb
spec/services/coronavirus/pages/draft_discarder_spec.rb
spec/services/coronavirus/pages/draft_updater_spec.rb
spec/services/coronavirus/pages/model_builder_spec.rb
spec/services/coronavirus/pages/sections_presenter_spec.rb
spec/services/coronavirus/pages/sub_section_processor_spec.rb
spec/services/coronavirus/pages/timeline_entry_builder_spec.rb
spec/support/coronavirus_feature_steps.rb

This is open as a draft as it depends on https://github.com/alphagov/collections-publisher/pull/1262. I've set that as the base branch for this PR
This change has been made so that these classes could be within the
Coronavirus namespace. These classes didn't seem to make much sense
without some relationship to page so I decided to create an additional
namespace of Pages with Coronavirus so they could be moved with minimal
changes.
There is probably scope to rethink the purpose of some of these classes
as they seem to venture outside of what would be considered to be a
service (Configuration) and there is a Presenter class here that seems
to have cross over with the presenters directory of classes.
⚠️ …

Rename CoronavirusPages module to Coronavirus::Pages

---

app/presenters/coronavirus/announcement_json_presenter.rb
app/presenters/coronavirus/coronavirus_page_presenter.rb
app/presenters/coronavirus/sub_section_json_presenter.rb
app/services/coronavirus/pages/content_builder.rb
app/services/coronavirus/pages/draft_updater.rb
app/services/live_stream_updater.rb
spec/presenters/coronavirus/announcement_json_presenter_spec.rb
spec/presenters/coronavirus/coronavirus_page_presenter_spec.rb
spec/presenters/coronavirus/sub_section_json_presenter_spec.rb
spec/services/coronavirus/pages/content_builder_spec.rb
spec/services/coronavirus/pages/draft_updater_spec.rb

This is open as a draft as it depends on https://github.com/alphagov/collections-publisher/pull/1265. I've set that as the base branch for this PR
This continues the work to move Coronavirus related code under the same
namespace. These names match their models, for example
Coronavirus::AnnouncementJsonPresenter is for
Coronavirus::Announcement.

Put Coronavirus presenters under Coronavirus namespace

---

app/controllers/coronavirus/reorder_timeline_entries_controller.rb
app/controllers/coronavirus/timeline_entries_controller.rb
app/views/coronavirus/pages/_actions.html.erb
app/views/coronavirus/pages/_announcements.html.erb
app/views/coronavirus/pages/_sub_sections.html.erb
app/views/coronavirus/pages/index.html.erb
app/views/coronavirus/pages/prepare.html.erb
app/views/coronavirus/pages/shared/_draft.html.erb
app/views/coronavirus/pages/shared/_github.html.erb
app/views/coronavirus/pages/shared/_live.html.erb
app/views/coronavirus/pages/shared/_preview.html.erb
app/views/coronavirus/pages/shared/_publish.html.erb
app/views/coronavirus/pages/show.html.erb
app/views/coronavirus/reorder_timeline_entries/index.html.erb
config/locales/en.yml
spec/support/coronavirus_feature_steps.rb

This is to make this key consistent with the namespacing approach
applied in the rest of the application as having coronavirus and pages
as distinct namespaces.

Change coronavirus_pages locale key to coronavirus.pages

---

spec/controllers/coronavirus/announcements_controller_spec.rb
spec/controllers/coronavirus/pages_controller_spec.rb
spec/controllers/coronavirus/reorder_announcements_controller_spec.rb
spec/controllers/coronavirus/reorder_sub_sections_controller_spec.rb
spec/controllers/coronavirus/reorder_timeline_entries_controller_spec.rb
spec/controllers/coronavirus/sub_sections_controller_spec.rb
spec/controllers/coronavirus/timeline_entries_controller_spec.rb
spec/factories.rb
spec/models/coronavirus/announcement_spec.rb
spec/models/coronavirus/live_stream_spec.rb
spec/models/coronavirus/page_spec.rb
spec/models/coronavirus/sub_section_spec.rb
spec/models/coronavirus/timeline_entry_spec.rb
spec/presenters/coronavirus/announcement_json_presenter_spec.rb
spec/presenters/coronavirus/page_presenter_spec.rb
spec/presenters/coronavirus/sub_section_json_presenter_spec.rb
spec/services/coronavirus/live_stream_updater_spec.rb
spec/services/coronavirus/pages/content_builder_spec.rb
spec/services/coronavirus/pages/draft_discarder_spec.rb
spec/services/coronavirus/pages/timeline_entry_builder_spec.rb
spec/support/coronavirus_feature_steps.rb

This makes the various factories of models that are under the
Coronavirus consistent in their naming by having a prefix of
`coronavirus_`. Prior to this commit there was only a prefix on the
`coronavirus_page` factory.

Rename factories of Coronavirus models for consistency

---

app/models/coronavirus/announcement.rb
app/models/coronavirus/live_stream.rb
app/models/coronavirus/sub_section.rb
app/models/coronavirus/timeline_entry.rb
db/migrate/20210205143416_rename_coronavirus_tables.rb
db/schema.rb

This makes these models consistent with `coronavirus_pages` in having a
`coronavirus_` prefix in the table name.
This migration must be applied at a quiet time for the application as
the deployment of it risks errors from when the migration has run until
a new instance of the app is running.
It's not ideal to deal with this risk of errors but the alternative is
far more painful - which would be creating new tables that are
backfilled and kept in sync until the tables are swapped. Given that
this application frequently goes many hours without a user request it
seems reasonable to take this risk.
⚠️ This repo is Continuously Deployed: make sure you [follow the …

Add coronavirus prefix to coronavirus database tables (⚠️  dangerous PR)

---

app/views/step_by_step_pages/index/_results.erb

Adds the new `no_top_border` attribute to calls to the [document list component](https://components.publishing.service.gov.uk/component-guide/document_list) on step by step pages to remove the visual top border element from component render within the step by step pages view.
This is to fix a visual discrepancy on the step by step list view caused by a recent design change to the document list component. [See this PR for more details including visual changes](https://github.com/alphagov/govuk_publishing_components/pull/1907).

Apply no border option for document list on stp by step pages

---

app/views/components/docs/markdown_editor.yml
spec/features/components_guide_spec.rb

This change fixes the components guide endpoint in collections publisher. There was a bug in the yaml file which stopped the guide from rendering, this has now been fixed and a small test added to make sure the components guide loads.

Fix components guide

---

app/controllers/coronavirus/sub_sections_controller.rb
spec/controllers/coronavirus/sub_sections_controller_spec.rb

In the previous configuration we had accidentally allowed the user to save changes to a sub-section even if there were errors with it. This wraps the sub-section changes in a transaction whilst we call on the draft updater, so they can be rolled back in the event that the draft updater finds errors.
There will be no visual changes for the user 
[Trello card](https://trello.com/c/p6Rq4Gj8/163-stop-saving-subsections-with-invalid-markdown-the-band-aid-method)

Subsection bug

---

app/assets/javascripts/admin_layout.js
app/assets/javascripts/components/reorderable-list.js
app/assets/stylesheets/components/_all.scss
app/assets/stylesheets/components/_reorderable-list.scss
app/controllers/coronavirus/reorder_announcements_controller.rb
app/controllers/coronavirus/reorder_sub_sections_controller.rb
app/controllers/coronavirus/reorder_timeline_entries_controller.rb
app/views/components/_reorderable_list.html.erb
app/views/components/docs/reorderable_list.yml
app/views/coronavirus/reorder_announcements/_reorder_list.html.erb
app/views/coronavirus/reorder_announcements/index.html.erb
app/views/coronavirus/reorder_sub_sections/_reorder_list.html.erb
app/views/coronavirus/reorder_sub_sections/index.html.erb
app/views/coronavirus/reorder_timeline_entries/_reorder_list.html.erb
app/views/coronavirus/reorder_timeline_entries/index.html.erb
package.json
spec/components/reorderable_list_spec.rb
spec/controllers/coronavirus/reorder_announcements_controller_spec.rb
spec/controllers/coronavirus/reorder_sub_sections_controller_spec.rb
spec/controllers/coronavirus/reorder_timeline_entries_controller_spec.rb
spec/javascripts/components/reorderable-list-spec.js
spec/support/coronavirus_feature_steps.rb
yarn.lock

A list of items that can be reordered
List items can be reordered by drag and drop or by using the up/down buttons. On small viewports the drag and drop feature is disabled to prevent being triggered when scrolling on touch devices.
This component uses SortableJS - a JavaScript library for drag and drop interactions. When JavaScript is disabled a set of inputs will be shown allowing users to provide an order index for each item.
This is used by publishing tools to allow reordering of lists such as steps in step by step, entries in timelines and order of visual presentation of attachments.
This is a port/extension of the work that @alex-ju has done on the content publisher app.
⚠️ This repo is Continuously Deployed: make sure you [follow the …

Add reorder-able lists component

---

app/views/coronavirus/pages/index.html.erb
config/locales/en.yml
spec/support/coronavirus_feature_steps.rb

Follows on from: https://github.com/alphagov/collections-publisher/pull/1275
Moves index page content to locale file and updates the feature tests to read index page content from the locale file. 
Also changes a field name to be consistent with the landing page.

Move index page content to locale file

---

app/views/coronavirus/pages/show.html.erb
config/locales/en.yml

The summary page allows more than just accordions (sub-sections) to be edited now

Remove "accordions" from summary page breadcrumb

---

app/controllers/coronavirus/live_stream_controller.rb
app/views/coronavirus/live_stream/index.html.erb
config/locales/en.yml
spec/support/coronavirus_feature_steps.rb

Moves live stream page content to locale file and updates the feature tests to read live stream page content from the locale file.

Move coronavirus livestream content to locale file

---

app/controllers/coronavirus/announcements_controller.rb
app/views/coronavirus/announcements/_form.html.erb
app/views/coronavirus/announcements/edit.html.erb
app/views/coronavirus/announcements/new.html.erb
app/views/coronavirus/pages/show/_announcements.html.erb
config/locales/en.yml
spec/support/coronavirus_feature_steps.rb

Moves controller and view content for announcements to a locale file

Move announcements content to locale file

---

app/controllers/coronavirus/pages_controller.rb
spec/controllers/coronavirus/pages_controller_spec.rb
spec/features/coronavirus_page_spec.rb
spec/support/coronavirus_feature_steps.rb

Follows on from: #1291
In preparation for moving the content from the `PagesController` to a locale file, the controller has been tidied up a little. This means removing some unused methods, and retrieving models from the database rather than building them in memory.
There's also a rather controversial final commit that removes the redirect to the index page and instead throws a 404. The bonus to this is that we won't have to try to figure out where to put the content for "slug unknown" error message later.

Tidy up `PagesController`

---

app/controllers/coronavirus/sub_sections_controller.rb
spec/controllers/coronavirus/sub_sections_controller_spec.rb

This fixes a bug whereby it was possible to save a new subsection with invalid content. It's also brought to light a lack of error handling that we have not only for the create and update methods.
We've been ignoring ActiveRecord validation errors and relying on the validation that we have in the presenters to show users their errors. We're checking the validity of sub_sections before we make any attempt to save them. This means that we're not at any risk of saving invalid subsections and that we are using errors as created by the model layer.
Trello - https://trello.com/c/p6Rq4Gj8/163-stop-saving-subsections-with-invalid-markdown-the-band-aid-method
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline …

Fix subsection bug for the create method.

---

app/controllers/coronavirus/timeline_entries_controller.rb
app/views/coronavirus/timeline_entries/_form.html.erb
app/views/coronavirus/timeline_entries/edit.html.erb
app/views/coronavirus/timeline_entries/new.html.erb
config/locales/en.yml
spec/support/coronavirus_feature_steps.rb

Moves controller and view content for timeline entries to a locale file

Move timeline entries content to locale file

---

app/controllers/coronavirus/sub_sections_controller.rb
app/views/coronavirus/sub_sections/_form.html.erb
app/views/coronavirus/sub_sections/edit.html.erb
app/views/coronavirus/sub_sections/new.html.erb
config/locales/en.yml

Moves controller and view content for sub-sections (accordions) to a locale file

Move sub-sections content to locale file

---

app/controllers/coronavirus/reorder_announcements_controller.rb
app/views/coronavirus/reorder_announcements/index.html.erb
config/locales/en.yml
spec/support/coronavirus_feature_steps.rb

Moves controller and view content for reordering announcements to a locale file

Move reorder announcements content to locale file

---

app/controllers/coronavirus/pages_controller.rb
config/locales/en.yml
spec/features/coronavirus_page_spec.rb
spec/support/coronavirus_feature_steps.rb

Moves `PagesController` content to locale file.
The feature tests have also been updated to highlight that the summary pages and the github changes content pull in their "published" messages from different places even though the content is the same at the moment.

Move PagesController content to locale file

---

app/controllers/coronavirus/reorder_timeline_entries_controller.rb
app/views/coronavirus/reorder_timeline_entries/index.html.erb
config/locales/en.yml
spec/support/coronavirus_feature_steps.rb

Restructures the reorder timeline entries content to match that of the content in the other controllers/views

Restructure reorder timeline entries content

---

app/presenters/coronavirus/sub_section_json_presenter.rb
spec/models/coronavirus/sub_section_spec.rb
spec/presenters/coronavirus/sub_section_json_presenter_spec.rb

As inclusion of featured links is handled at a model level this adds a
test to ensure that the model is validating featured links correctly.
It also removes old functionality that gave the json presenter
responsibility for featured link errors.

Tidy up featured link testing

---

app/controllers/coronavirus/reorder_sub_sections_controller.rb
app/views/coronavirus/reorder_sub_sections/index.html.erb
config/locales/en.yml
spec/support/coronavirus_feature_steps.rb

Moves reorder sub-sections content to locale file.

Move reorder subsections content to locale file

---

app/views/coronavirus/announcements/edit.html.erb
app/views/coronavirus/announcements/new.html.erb
app/views/coronavirus/reorder_announcements/index.html.erb
app/views/coronavirus/reorder_sub_sections/index.html.erb
app/views/coronavirus/reorder_timeline_entries/index.html.erb
app/views/coronavirus/shared/_breadcrumbs.html.erb
app/views/coronavirus/sub_sections/edit.html.erb
app/views/coronavirus/sub_sections/new.html.erb
app/views/coronavirus/timeline_entries/edit.html.erb
app/views/coronavirus/timeline_entries/new.html.erb
config/locales/en.yml

Moves breadcrumbs on coronavirus pages to a shared partial.

Move coronavirus breadcrumbs to partial

---

spec/support/coronavirus_feature_steps.rb

While the coronavirus controller and view content was being moved into a locale file, the test content was supposed to be updated as well. A couple of items were missed and are being corrected here.

Fetch coronavirus test content from locale file

---

app/services/yaml_fetcher.rb
spec/services/yaml_fetcher_spec.rb

Trello: https://trello.com/c/fIY7Oy1L
Remove `success?` method from YamlFetcher as this method is not being used.

Remove `success?` method from YamlFetcher

---

app/presenters/coronavirus/sub_section_json_presenter.rb
app/services/coronavirus/pages/content_builder.rb
spec/presenters/coronavirus/sub_section_json_presenter_spec.rb

Trello: https://trello.com/c/fIY7Oy1L
Raise an error in `SubSectionJsonPresenter` when a sub-section contains invalid markdown.
This is part of the work to apply a consistent approach to error handling for Coronavirus pages. 
Rather than storing errors in a list, we want to surface these errors back up to the controller so that when we start saving changes to the page in transactions, we can rely on the exceptions being thrown at different points in the code to force the database changes to be rolled back.

Raise error in sub section json presenter

---

app/controllers/coronavirus/announcements_controller.rb
app/controllers/coronavirus/github_changes_controller.rb
app/controllers/coronavirus/pages_controller.rb
app/controllers/coronavirus/reorder_announcements_controller.rb
app/controllers/coronavirus/reorder_sub_sections_controller.rb
app/controllers/coronavirus/reorder_timeline_entries_controller.rb
app/controllers/coronavirus/sub_sections_controller.rb
app/controllers/coronavirus/timeline_entries_controller.rb
app/services/coronavirus/pages/content_builder.rb
app/services/coronavirus/pages/draft_updater.rb
spec/controllers/coronavirus/announcements_controller_spec.rb
spec/controllers/coronavirus/timeline_entries_controller_spec.rb
spec/features/coronavirus_page_spec.rb
spec/services/coronavirus/pages/content_builder_spec.rb
spec/services/coronavirus/pages/draft_updater_spec.rb
spec/support/coronavirus_feature_steps.rb

Trello: https://trello.com/c/fIY7Oy1L
Add transactions to the controller methods. Transactions will automatically rollback if something inside them throws an exception. Previously all of the exceptions were being swallowed and instead we were returning a list of errors, and had to manually raise an `ActiveRecord::Rollback` exception to make the transaction rollback.
To that end `ContentBuilder` and parts of `DraftUpdater` have also been updated to start raising their own exceptions.

Raise exceptions and rollback failures in coronavirus pages

---

app/models/coronavirus/announcement.rb
db/migrate/20210325171427_change_coronavirus_announcements_path_to_url.rb
db/migrate/20210325171835_improve_coronavirus_announcements_schema.rb
db/schema.rb

Trello: https://trello.com/c/CRwjuyqN/278-allow-external-links-from-announcements
This PR does the database changes needed to prepare the Coronavirus::Announcements model for a change from accepting a path to accepting a URL. It also resolves some ambiguity in the DB schema about what can be accepted by setting key fields to no longer accept null.
This is a somewhat dangerous PR, as the migration involves column changes (particularly rename) it can cause the app to error if it is being used during deployment. Therefore I will plan to carefully deploy it while the app is not being used (this seemed easier than a backfill process given this app is only sporadically used during a working day)
I've opened this a small PR to reflect that it's a bit dangerous to deploy so it doesn't get …

Change coronavirus_announcements schema for path -> url change

---

spec/support/step_nav_steps.rb

This test is flaky. I'm not entirely sure why, but this is my best guess.
The html below shows the "Check for broken links" message if the following things
are true:
* The step by step has steps. - The test one does.
* Any of the steps contain links. - The first step creates contains links
* The links haven't been checked since the last time the draft was updated.
This last point is where I think the test sometimes fails. I think that if the link
report is created after `@step_by_step_page` is created, then this check will
"fail" and the message won't be shown.
```
<div class="govuk-grid-row">
<div class="govuk-grid-column-two-thirds">
<div id="inset-text-c6cd2f9b" class="gem-c-inset-text govuk-inset-text">
<h2 class="govuk-heading-m">To publish this step by step you need to</h2>
<ul …
```

Attempt to fix flaky feature test

---

app/controllers/coronavirus/announcements_controller.rb
app/models/coronavirus/announcement.rb
app/presenters/coronavirus/announcement_json_presenter.rb
app/services/coronavirus/pages/draft_discarder.rb
app/views/coronavirus/announcements/_form.html.erb
db/migrate/20210329141909_backport_coronavirus_announcements_published_on_field.rb
db/migrate/20210329143101_remove_published_at_from_coronavirus_announcements.rb
db/migrate/20210329150719_disallow_null_for_coronavirus_announcements_position.rb
db/schema.rb
spec/controllers/coronavirus/announcements_controller_spec.rb
spec/factories.rb
spec/models/coronavirus/announcement_spec.rb
spec/presenters/coronavirus/announcement_json_presenter_spec.rb
spec/presenters/coronavirus/page_presenter_spec.rb
spec/services/coronavirus/pages/content_builder_spec.rb
spec/support/coronavirus_feature_steps.rb

Trello: https://trello.com/c/CRwjuyqN/278-allow-external-links-from-announcements
As a bonus (or a nuisance) I did some follow-up work on https://github.com/alphagov/collections-publisher/pull/1335 to set the published_at field to be a date (and rename to published_on as per Rails convention) and remove the ability to set a null position. This finishes work started in https://github.com/alphagov/collections-publisher/pull/1333/commits/724f69f18db4507e4b3d2916467362e6a7d21be9
This change will cause the app to error if someone is using it while the app is deployed. Since this app is used infrequently I plan to just carefully deploy this change rather than do defensive migration work.
This PR is intentionally branched off https://github.com/alphagov/collections-publisher/pull/1335 until that …

[Dangerous deployment] Improve schema configuration for coronavirus_announcements fields

---

app/models/coronavirus/sub_section.rb
app/models/coronavirus/sub_section/structured_content.rb
app/presenters/coronavirus/sub_section_json_presenter.rb
app/services/coronavirus/pages/content_builder.rb
app/services/coronavirus/pages/draft_updater.rb
spec/controllers/coronavirus/sub_sections_controller_spec.rb
spec/models/coronavirus/sub_section/structured_content_spec.rb
spec/presenters/coronavirus/sub_section_json_presenter_spec.rb
spec/services/coronavirus/pages/content_builder_spec.rb
spec/services/coronavirus/pages/draft_updater_spec.rb

This attempts to remove validation that currently sits within the subsection json presenter. This is done by creating a structured content model within the subsection space that can create link objects and associated titles. The result of this is that the model layer has more information on what constitutes valid content.
We've been able to remove a lot of code from the json presenter and associated tests because the StructuredContent more closely resembles what's sent to the Publishing API and as such requires less logic.
Trello - https://trello.com/c/LwvWFlnk/160-move-subsection-presenter-validation-into-model-layer
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request …

Move subsection content validation to model

---

app/models/navigation_rule.rb
app/models/secondary_content_link.rb
spec/models/navigation_rule_spec.rb
spec/models/secondary_content_link_spec.rb

This adds support to detect smart answers published with the new `smart_answer` schema and continue to detect smart answers that are published as `transaction` pages. This is required as smart answers will be republished with the new content schema.

Add support for new `smart_answer` schema

---

app/controllers/coronavirus/sub_sections_controller.rb
app/models/coronavirus/sub_section.rb
app/presenters/coronavirus/sub_section_json_presenter.rb
app/services/coronavirus/pages/draft_discarder.rb
app/services/coronavirus/pages/sections_presenter.rb
app/services/coronavirus/pages/sub_section_processor.rb
app/views/coronavirus/sub_sections/_form.html.erb
config/locales/en.yml
db/migrate/20210325103947_rename_featured_link_to_action_link_url.rb
db/migrate/20210325112605_add_action_link_fields_to_coronavirus_sub_sections.rb
db/schema.rb
spec/fixtures/coronavirus_page_sections.json
spec/models/coronavirus/sub_section_spec.rb
spec/presenters/coronavirus/sub_section_json_presenter_spec.rb
spec/services/coronavirus/pages/draft_discarder_spec.rb
spec/services/coronavirus/pages/sections_presenter_spec.rb
spec/services/coronavirus/pages/sub_section_processor_spec.rb

[Trello](https://trello.com/c/B7f0bkef/257-mvp-create-new-input-fields-for-action-link-content-publishing-tool)
This updates an existing sub section field (from `featured_link` to `action_link_url`) and adds two new fields:
1. `action_link_content` - which will be used to contain the link text, and
2. `action_link_summary` - which will be used to hold the description of the page being linked to.  A content item for example.
Together these three fields (`action_link_url`, `action_link_content` and `action_link_summary`) constitute an `action link`.
In addition, we also update the existing JSON presenter that is used to store this data in the `publishing-api` and the various data structures that are used to re-create a draft edition of the content when a user discards an existing draft from …

Action link MVP

---

app/services/coronavirus/pages/content_builder.rb

The github_data method makes calls to GitHub to gather information held in yaml files. This was done so that non developers could update content. The output of this method was being modified quite opaquely to include data from timelines that is being held in the database rather than the yaml. This changes things so that the `timeline_data` method is called directly which makes it clearer that timeline data is being accessed from the database rather than the yaml.
Trello - https://trello.com/c/rMnlfIq6/335-get-hidden-search-terms-for-timeline-from-database

Stop using the github_data method to gather timeline information

---

app/presenters/coronavirus/sub_section_json_presenter.rb
spec/presenters/coronavirus/sub_section_json_presenter_spec.rb

Trello: https://trello.com/c/B6v2ONY0
Make `SubSectionJSONPresenter` methods private where possible, and rationalise and refactor SubSectionJSONPresenter tests.
Most of the methods are not used outside of the instance, so could be made private.

Tidy-up `SubSectionJSONPresenter` tests

---

app/assets/stylesheets/views/_coronavirus_manage_pages.scss
app/controllers/coronavirus/timeline_entries_controller.rb
app/models/coronavirus/timeline_entry.rb
app/services/coronavirus/pages/content_builder.rb
app/services/coronavirus/pages/draft_discarder.rb
app/views/coronavirus/pages/show/_timeline_entries.html.erb
app/views/coronavirus/reorder_timeline_entries/_reorder_list.html.erb
app/views/coronavirus/timeline_entries/_form.html.erb
config/locales/en.yml
db/migrate/20210702095110_add_national_applicability_to_coronavirus_timeline_entry.rb
db/schema.rb
spec/controllers/coronavirus/timeline_entries_controller_spec.rb
spec/factories.rb
spec/fixtures/coronavirus_page_sections.json
spec/models/coronavirus/timeline_entry_spec.rb
spec/services/coronavirus/pages/content_builder_spec.rb
spec/support/coronavirus_feature_steps.rb

Trello: https://trello.com/c/PSKxvsS3
Depends on: https://github.com/alphagov/collections/pull/2456
Add a field to allow content designers to specify which UK nations a timeline entry applies too. This is related to a change on the frontend of the landing page which will allow users to filter the timeline by nation.
This change isn't behind a feature flag because it's expected that https://github.com/alphagov/collections/pull/2456 will be reviewed and deployed first.

Add nation selection to coronavirus timeline entries

---

db/schema.rb

An update to rails means that there's changes to the db schema that
can only be seen when a migration is run. This means that these changes
will be in the schema rather than being drawn in with an upcoming
migration

Update db schema after rails upgrade

---

db/migrate/20211001131132_add_sub_heading_to_coronavirus_sub_section.rb
db/schema.rb

This is in order that we can retire the hubs and add the content therein to
the accordions on the landing page.
Trello - https://trello.com/c/0W3i2dN8/645-add-subheading-field-to-subsections-in-coronavirus-publishing-tool

Create migration to add sub heading to coronavirus subsection

---

app/services/coronavirus/pages/header_section_builder.rb
lib/tasks/coronavirus.rake
spec/fixtures/coronavirus_landing_page.yml
spec/services/coronavirus/pages/header_section_builder_spec.rb

Trello: https://trello.com/c/Atk2LuuG
Adds a rake task to sync the header section on the coronavirus landing
page with the entries in the YAML file.
Creating a rake task avoids the risk of copy and paste errors that could
occur if the section was updated manually.
This is a throwaway task that should only be run once and will be
removed after the header section has been deployed.
Usage:
```
bundle exec rake coronavirus:sync_header_section
```

Add task to sync coronavirus header with YAML

---

app/controllers/coronavirus/pages_controller.rb
app/views/coronavirus/pages/_form.html.erb
app/views/coronavirus/pages/edit_header.html.erb
app/views/coronavirus/pages/show.html.erb
app/views/coronavirus/pages/show/_header.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/coronavirus/pages_controller_spec.rb
spec/features/coronavirus_page_spec.rb
spec/support/coronavirus_feature_steps.rb

Trello: https://trello.com/c/hbvDJVBx
Adds a section that allows publishers to edit the header content on the coronavirus landing page.
The header section content was stored in a YAML file on GitHub. This meant that only content designers who are comfortable using GitHub or a developer could update this section. Moving this content into Collections Publisher with the rest of the landing page content opens up editing to content designers across GOV.UK.
The content on the new "Edit header" page has not been finalised and should be considered placeholder content.

Header section controller and view

---

app/models/coronavirus/page.rb
spec/models/coronavirus/page_spec.rb

Trello: https://trello.com/c/zSJj2DNL
Remove the 40 character validation on the `header_link_pre_wrap_text` and `header_link_post_wrap_text` fields made in commit: 42ea8044f9bc9f42eb0289415777b67a459ae58a
The validation was added after the initial iteration of the hint for the fields implied that 40 characters was an enforced limit. The hint text has since been updated to state that the 40 character limit is only a suggestion, so the 40 character validation has been removed.
Rails no longer has a [size limit on text and string fields] so we still need to add some validation to protect the database from accidental abuse. 255 has been picked as the limit because 1) it matches the validation of the `header_title` field and 2) as the recommended length of the content is 40 characters, it …

Remove 40 character limit for action link fields

---

app/services/coronavirus/pages/content_builder.rb
spec/services/coronavirus/pages/content_builder_spec.rb

Trello: https://trello.com/c/YZaACJRR
The header section is being made editable via collections-publisher rather than via the YAML file in Github. To avoid making changes in the rendering application, the format that the header section data is presented to  publishing-api has not changed.

Present header section in db to publishing-api

---

app/controllers/coronavirus/pages_controller.rb
app/services/coronavirus/pages/content_builder.rb
app/views/coronavirus/pages/show.html.erb
spec/controllers/coronavirus/pages_controller_spec.rb
spec/features/coronavirus_page_spec.rb
spec/services/coronavirus/pages/content_builder_spec.rb

[Trello](https://trello.com/c/9AV3j3sD/38-make-header-section-live)
- Last stage in the [deploy plan](https://trello.com/c/9AV3j3sD/38-make-header-section-live) for making the header section editable via collections publisher.
- This flag allowed us to reduce the amount of time to freeze content editing.
- Do not merge on approval. Ensure everything else on the plan has been ticked off.

Remove unreleased feature check

---

app/services/coronavirus/pages/content_builder.rb

The `announcements` and `sections` keys don't contain any content in GitHub so they were removed from the YAML in:
https://github.com/alphagov/govuk-coronavirus-content/pull/630
The validation here needs to be updated to match.
Fixes error:

Remove validation for unnecessary GitHub content

---

Jenkinsfile
config/database.yml

This changes the Jenkins CI configuration to use MySQL 8.
MySQL is [available at port `33068 `](https://docs.publishing.service.gov.uk/manual/test-and-build-a-project-on-jenkins-ci.html#specifying-which-database-to-use) on the CI server. By explicitly setting the `TEST_DATABASE_URL`, we're telling Rails to use that MySQL server.
Previously, Rails implicitly used the default MySQL port `3306` which is a MySQL 5.5 server.
Trello ticket: https://trello.com/c/btcm7JyB/

Upgrade CI to use MySQL8

---

config/locales/en.yml

Doing so will cause an error, because these formats automatically have their Done page links included since https://github.com/alphagov/collections-publisher/blob/f4321e88f6c358b5dd57f3b7a04f25992a108433/app/presenters/step_nav_presenter.rb#L105

Add instructions to avoid linking to Done pages

---

app/assets/stylesheets/views/_coronavirus_manage_pages.scss

Fix the layout of the summary list component on `/coronavirus/landing` by removing the custom styles that were being applied to the component in this context. These styles were setting widths that caused this component to break.
The layout still isn't perfect, but it's considerably more readable. We'll try to improve the component itself to fix the layout of the `Change/Delete` links in future.
We shouldn't have styles in applications that override component styles - this breaks component isolation and makes it harder to iterate components.
Before | After
------ | -------

Fix timeline page layout

---

app/views/coronavirus/pages/show/_announcements.html.erb
app/views/coronavirus/pages/show/_sub_sections.html.erb
app/views/coronavirus/pages/show/_timeline_entries.html.erb
config/locales/en.yml
spec/support/coronavirus_feature_steps.rb

Change edit link label text from "Change" to "Edit".
The word "Change" causes the action column to wrap around due to the component not being responsive. Previously we had css overrides but this was removed by PR #1539.
While we wait for the components to update the layouts, this change will help keep a nice consistent layout.

Update edit link text

---

db/migrate/20220331095756_add_mainstream_browse_type_to_tags.rb
db/schema.rb

Add mainstream_browse_type column to tags table.
This reflect changes in the content schema https://github.com/alphagov/govuk-content-schemas/pull/1087
This column will be used for:
- copying Mainstream Browse Pages into Topics [trello](https://trello.com/c/KGCUHfhi/876-copy-over-mainstream-browse-pages-into-specialist-topics)
- hiding Topics that used the be Mainstream Browse Pages [trello](https://trello.com/c/m13ffUVc/292-update-publishing-apps-that-know-of-specialist-topics-to-hide-new-synced-ones)
---

Add mainstream_browse_type column to tags table

---

app/services/coronavirus/pages/content_builder.rb
spec/fixtures/coronavirus_landing_page.yml
spec/fixtures/coronavirus_landing_page_with_announcements.yml
spec/fixtures/simple_coronavirus_page.yml

Remove `nhs_banner`
On [1st April - Remove NHS Box, Announcements, Timeline Entries, Statistics sections from landing page and move DA Links](https://trello.com/c/zxAAM52Y) we stopped rendering the NHS box on the landing page.
[Trello](https://trello.com/c/vn3rFVge/814-remove-nhs-box-from-yaml-file-and-as-required-for-publishing-in-collections-publisher)

Remove NHS box banner

---

app/assets/javascripts/analytics.js
app/assets/javascripts/application.js

Add Google analytics tracking back into the application layout.
During the migration we lost the automatic analytics tracking, this needs to be added back in.
Add this to the layout so that everything is tracked automatically.
https://trello.com/c/DQuvQmhd/372-add-tracking-back-in-for-collections-publisher

Add tracking back in for collections publisher

---

app/models/step_by_step_page.rb

This update the regex for unpublishing step by step to be more permissive. Previously url paths with multiple parts i.e. extra "/"s would be considered invalid. This also tidies up the code to return true or false, rather than the match number or nil.

Fix url validation regex for unpublishing step by steps

---

app/models/topic.rb
app/presenters/topic_presenter.rb
spec/presenters/topic_presenter_spec.rb

Following the content schema change in: https://github.com/alphagov/govuk-content-schemas/pull/1089
We want to reference the content_id of Mainstream browse page the topic
originated from as a part of unified topic system work.
Until the work is completed we will need to keep the Mainstream browse page and
the cloned Topic is sync. Since other attributes of the Mainstream browse page
such as title or slug can change, this adds a unique reference we can use to
identify the cloned Topic.
We decided not to store it in the Collections publisher database.
Adding this as a separate PR as it's needed by a few other pieced of work:
- This attribute will be populated when a new Topic is created and send to the
Publishing API.
- The presence of this attribute will be used to hide those Topic in the …

Add mainstream_browse_origin to TopicPresenter

---

app/views/layouts/design_system.html.erb

Remove beta banner in Collections Publisher
This is incorrect as the product is not beta and is not being rebuilt - this may be considered misleading to the user.
https://trello.com/c/aFpyXJdm/415-remove-beta-banner-in-collections-publisher

Remove Beta Banner from collections publisher

---

app/presenters/topic_presenter.rb
app/services/copy_mainstream_browse_pages_to_topics.rb
lib/tasks/browse_topics.rake
spec/lib/tasks/browse_topics_spec.rb
spec/services/copy_mainstream_browse_pages_to_topics_spec.rb

Link to Trello card: https://trello.com/c/KGCUHfhi/876-copy-over-mainstream-browse-pages-into-specialist-topics
Add a rake task to copy over Mainstream Browse Pages (MBP) into Topics.
The task is intended to run once.
Tested locally with a copy of production data. Completed in ~ 40 minutes
- At this point we don't copy over MBP's attributes which would require Topic content schema changes such as equivalent of `top_level_browse_pages`. We decided that those changes can be later once we identify what we need
- Only published MBP will be cloned
The product team decided that we will not copy over archived ones. I decided not to copy draft MBP as there is not much value in keeping those in sync. I think a MBP should be copied into a Topic when the MBP is published.
- We assume that there are …

Copy over Mainstream browse pages into Topics

---

app/controllers/list_items_controller.rb
app/controllers/lists_controller.rb
app/controllers/mainstream_browse_pages_controller.rb
app/controllers/topics_controller.rb
app/models/tag.rb
spec/controllers/list_items_controller_spec.rb
spec/features/managing_browse_pages_spec.rb

The new layout using GOV.UK Design System renders flash notices only if the
keys are "alert" or "notice". Any messages stored under other keys such as
"success" or "danger" were not displayed.
https://trello.com/b/iACGoJN3/govuk-explore-doing

Fix flash messages

---

Gemfile
Gemfile.lock
spec/notifiers/publishing_api_notifier_spec.rb
spec/presenters/archived_tag_presenter_spec.rb
spec/presenters/coronavirus/page_presenter_spec.rb
spec/presenters/mainstream_browse_page_presenter_spec.rb
spec/presenters/redirect_item_presenter_spec.rb
spec/presenters/root_browse_page_presenter_spec.rb
spec/presenters/root_topic_presenter_spec.rb
spec/presenters/step_nav_presenter_spec.rb
spec/presenters/tag_presenter_spec.rb
spec/presenters/topic_presenter_spec.rb
spec/support/govuk_content_schemas.rb

Trello: https://trello.com/c/b9PRFqgU
Replaces the govuk-content-schema-test-helpers gem with the govuk_schemas gem to validate content item schemas.
[govuk-content-schema-test-helpers] has been archived and there is a concern that it no longer receives any security updates. The advice in the govuk-content-schema-test-helpers repo is to replace it with the govuk_schemas gem.
[govuk-content-schema-test-helpers]: https://github.com/alphagov/govuk-content-schema-test-helpers

Replace archived govuk-content-schema-test-helpers gem 

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_curated_lists.scss
app/controllers/lists_controller.rb
app/models/list.rb
app/models/list_item.rb
app/views/lists/edit_list_items.html.erb
app/views/lists/show.html.erb
app/views/shared/tags/_curated_links_preview.html.erb
config/routes.rb
spec/controllers/lists_controller_spec.rb
spec/factories.rb
spec/features/curating_a_list_spec.rb
spec/models/list_spec.rb

This PR follows on from #1595 which built the functionality for adding, editing, reordering and deleting lists.
The focus of this PR is adding the ability for a user to add additional list items (links) to a list. The ability to reorder list items, move one to a different list and delete a list item will be added in follow up PRs
A new page that shows all the list items and available actions to add new items, reorder items, move an item to a different list and remove an item from a list. 
For now only the `Add links to list` link is wired in
Adds checkboxes for all the tagged documents which are associated with the mainstream browse page or topic that are not currently in the list
Per commit will definitely be easiest. Probs worth giving the designs/last pr a glance if you're not familiar …

Add list show page and edit list item functionality

---

app/assets/stylesheets/_curated_lists.scss
app/controllers/list_items_controller.rb
app/models/tag.rb
app/views/list_items/move.html.erb
app/views/lists/show.html.erb
app/views/shared/_list-links-preview.html.erb
config/routes.rb
spec/controllers/list_items_controller_spec.rb
spec/features/curating_a_list_spec.rb
spec/models/tag_spec.rb

https://github.com/alphagov/collections-publisher/pull/1595 - built the functionality for adding, editing, reordering and deleting lists
https://github.com/alphagov/collections-publisher/pull/1601 - added the list show page and ability to add new list items to a list.
https://github.com/alphagov/collections-publisher/pull/1609 - reorder list item functionality
https://github.com/alphagov/collections-publisher/pull/1610 - Deleting a list item 
The focus of this PR is adding the ability for a user to move a list item to another list.
Per commit will definitely be easiest. Probs worth giving the designs/last pr a glance if you're not familiar with the card.
Guidance on the publishing components used in the frontend can be found here …

Add move to different list functionality

---

Jenkinsfile

The environment variables set-up here were not having any impact because the govuk.buildProject method was called before them.
This means that we were running the full e2e test suite - not just collections publisher tests, and not using MySQL 8 in tests 🤦

Set environment variables before running tests

---

app/controllers/list_items_controller.rb
app/controllers/lists_controller.rb
spec/controllers/list_items_controller_spec.rb
spec/controllers/lists_controller_spec.rb

This adds additional content based on feedback from Design that the flash messages should be slightly more verbose and use consistent language.
The document with the requested changes can be found here https://docs.google.com/document/d/1FWW9oY6vD6WTJH5QJh2xqV2rc1onU9ajC63Bo2xUYno/edit
|Before|After|
|-----------|-----------|
|<img width="942" alt="image" src="https://user-images.githubusercontent.com/42515961/172374412-c2424198-b88b-4006-9899-af13ccd74d8e.png">|<img width="917" alt="image" src="https://user-images.githubusercontent.com/42515961/172372563-5e826cfd-ff64-40bb-90fa-f73b09ee88b7.png">|
|Before|After|
|-----------|-----------|
|<img width="981" alt="image" src="https://user-images.githubusercontent.com/42515961/172374487-5db31d08-0426-4052-a626-12b01f56474e.png">|<img …

Update content of flash messages for lists and list items

---

app/assets/stylesheets/_curated_lists.scss
app/views/list_items/confirm_destroy.html.erb
app/views/list_items/move.html.erb
app/views/lists/confirm_destroy.html.erb
app/views/lists/show.html.erb
app/views/shared/_list-links-preview.html.erb
app/views/shared/tags/_curated_links_preview.html.erb
app/views/shared/tags/_uncurated_links_preview.html.erb
spec/features/curating_a_list_spec.rb
spec/features/navigating_topics_spec.rb

Recently we've ported the Curate Links section of Collections Publisher over to use the GOVUK Design System. 
Nikin and me he a quick follow up session to run through the new implementation of curate lists and fix any issues with the implementation or styling.
Previously these were using font size 16, we've bumped them to 19
**Tag show page**
|Before|After|
|------------|------------| 
|<img width="753" alt="image" src="https://user-images.githubusercontent.com/42515961/171164968-4b0689de-a620-437d-ac5b-e5dc2ab1fb5b.png">|<img width="698" alt="image" src="https://user-images.githubusercontent.com/42515961/171164918-d26c4f7a-b189-4566-a55d-f30096c80872.png">|
**List show page**
|Before|After|
|------------|------------| 
|<img width="706" alt="image" …

Styling fixes for GOVUK Design System curate links implementation

---

app/helpers/error_items_helper.rb
app/views/lists/show.html.erb

While testing the new functionality, I have come across two bugs.
1. An empty array is passed as an error message on the move item page 
The error handling for the checkbox component is built slightly differently to the other components. Resultantly, an empty array is rendered as an error message for the checkbox component. This is due to there not being a presence check within the checkbox component within the text output.
This is easily mitigated on our end by ensuring that objects passed into the errors_for method return nil when errors are not present.
2. Lists where an item has been untagged on content tagger blow up 
At the moment, if someone untags a document on content tagger it causes an error to occur when you attempt to link to the document on content tagger on the list show …

Fix lists related bugs

---

app/lib/services.rb
app/models/topic.rb
app/services/email_alerts_unsubscriber.rb
app/services/tag_archiver.rb
app/views/topics/propose_archive.html.erb
spec/features/archiving_topic_tags_spec.rb
spec/models/topic_spec.rb
spec/services/email_alerts_unsubscriber_spec.rb
spec/services/tag_archiver_spec.rb
spec/support/email_alert_api_helpers.rb

When a Specialist topic is archived we need to unsubscribe users from email alerts for this topic and email them to inform them that this topic was archived and there won't be any updates.
This is currently done in a rake task in Email Alert API and requires:
- content designer to create a list of archived topics and redirects 
- developer to update and run the rake task
- Add Email Alert API as a service via gds-api-adapters
- Add generic EmailAlertsUnsubscriber service
- Unsubscribe users from emails when a specialist topic is archived
- Trigger sending emails to unsubscribed users with the body as per [doc](https://docs.google.com/document/d/1ixKUkQQV8OD856B4Bfy_ZxpQFrqM0GaLDumesPspWbo/edit)
- Add notice on archive specialist topic page about unsubscribing users
<kbd><img width="489" …

Automatically unsubscribe users from emails when a specialist topic is archived

---

app/controllers/mainstream_browse_pages_controller.rb
app/controllers/topics_controller.rb
app/models/mainstream_browse_page.rb
app/models/tag.rb
app/models/topic.rb
app/presenters/mainstream_browse_page_presenter.rb
app/presenters/root_browse_page_presenter.rb
app/presenters/root_topic_presenter.rb
app/services/draft_tag_remover.rb
app/services/tag_archiver.rb
app/views/mainstream_browse_pages/_create_update_form.html.erb
app/views/mainstream_browse_pages/show.html.erb
app/views/topics/_create_update_form.html.erb
app/views/topics/show.html.erb
db/migrate/20150622073727_add_redirects_for_topics_namespace.rb
db/migrate/20150625151822_add_browse_redirects.rb
db/migrate/20150713124417_import_router_data_browse_redirects.rb
db/migrate/20150714140302_import_router_data_topic_redirects.rb
spec/features/archiving_topic_tags_spec.rb
spec/models/mainstream_browse_page_spec.rb
spec/models/tag_spec.rb
spec/models/topic_spec.rb
spec/services/draft_tag_remover_spec.rb
spec/services/tag_archiver_spec.rb

We will be archiving a lot of specialist topics as part of our epic to retire the specialist topic tree. It is currently only possible to archive level two specialist topics in Collections Publisher UI. We need the UI to support archiving level one specialist topics, as it would make the workflow for retiring the specialist topic tree easier.
- Rename methods (see the first commit for details). Related cards:
- [Write glossary of information architecture related terminology](https://trello.com/c/UgR7LtOm/767-write-glossary-of-information-architecture-related-terminology-for-team-alignment)
- [Update copy in publishing apps](https://trello.com/c/V4XDiKNe/888-%F0%9F%8F%94epic-update-copy-in-publishing-apps-based-on-jenns-doc)
- Allow Level 1 Specialist topics to be archived
- 'Archive...' …

Allow Level 1 Specialist topics to be archived

---

app/views/shared/_list-children-pages.html.erb
app/views/topics/archived_topic.html.erb
spec/features/archiving_topic_tags_spec.rb

It is possible to archive level 1 specialist topics https://github.com/alphagov/collections-publisher/pull/1650.  We should also show the subtopics (children) and link to them in the archived topic view.
However it’s not possible to edit archived subtopics so we shouldn’t be showing this as an option. The users should still be able to view the archived subtopic and test the redirects.
* Add subtopics table to the archived topic page
<kbd><img width="610" alt="Screenshot 2022-08-09 at 06 54 41" src="https://user-images.githubusercontent.com/38078064/183576538-3b392d34-8fd3-4459-9437-c9b6ebe0feff.png"></kbd>
* Because it's not possible to archive a topic with active children (published or draft) in the UI, this subtopic table will only include archived subtopics.
* There is something not …

Show subtopics on archived specialist topic pages 

---

app/views/shared/tags/_curated_links_preview.html.erb

Links in the 'Unused links' section ([example](https://collections-publisher.integration.publishing.service.gov.uk/mainstream-browse-pages/895d337a-fa68-4c83-ab79-1c08016afe87)) were incorrect, resulting in 404 Not Found errors.
Link `href`s included `"lookup"` when they shouldn't have.
URL path before:
```
/taggings/lookupe0c82f84-6713-4d37-96b8-d545d75e41f3
```
After:
```
/taggings/e0c82f84-6713-4d37-96b8-d545d75e41f3
```

Fix broken link for "Unused links" section

---

app/models/mainstream_browse_page.rb
app/models/tag.rb
app/models/topic.rb
app/services/draft_tag_remover.rb
app/views/mainstream_browse_pages/show.html.erb
app/views/topics/show.html.erb
spec/features/archiving_topic_tags_spec.rb
spec/models/mainstream_browse_page_spec.rb
spec/models/topic_spec.rb
spec/services/draft_tag_remover_spec.rb

Find and view - Navigation and presentation team will be archiving a lot of specialist topics as part of our epic to retire the specialist topic tree. We did work to allow Level 1 Specialist topics to be archived.
For completeness and consistency, we should also allow draft level 1 Specialist topics to be removed in the UI.
There is currently a draft level 1 topic in production titled "To delete". 
<kbd><img width="761" alt="Screenshot 2022-08-09 at 11 24 03" src="https://user-images.githubusercontent.com/38078064/183626600-cb5ed061-a24d-46d8-90cf-d809f8513156.png"></kbd>
[Trello](https://trello.com/c/trPPWKvB/1185-allow-draft-level-1-specialist-topics-to-be-removed-m)
---
⚠️ This repo is Continuously Deployed: make sure you [follow the …

Allow draft Level 1 Specialist topics to be removed 

---

config/sidekiq.yml

All of our logs need to go to stdout/stderr when running on k8s.
As of Sidekiq 6.0, the logfile directive and -L option are being removed and logs will always go to stdout anyway:
https://github.com/mperham/sidekiq/wiki/Logging#log-redirection
This is essentially the same change as https://github.com/alphagov/publisher/commit/5547a1a

Have Sidekiq log to stdout by default

---

spec/support/publishing_api_helpers.rb

Trello card: https://trello.com/c/o1PTrZUs/797-stop-using-deprecated-plek-method

Change deprecated Plek.current to Plek.new

---

db/migrate/20221109124352_remove_mainstream_browse_type_from_tags.rb
db/schema.rb

Reverts https://github.com/alphagov/collections-publisher/pull/1561 
We are no longer going to merge Mainstream browse pages into Specialist topics so it's not needed
[Trello](https://trello.com/c/4CjEsirD/117-remove-code-related-to-topic-merging)

Remove mainstream_browse_type column from tags table

---

app/presenters/groups_presenter.rb
spec/controllers/list_items_controller_spec.rb
spec/controllers/lists_controller_spec.rb
spec/features/cuarating_lists_spec.rb
spec/features/curating_a_list_spec.rb
spec/presenters/groups_presenter_spec.rb
spec/presenters/tag_presenter_spec.rb
spec/services/list_publisher_spec.rb

When a content item is tagged to curated Mainstream browse or Specialist topic (parent class Tag) and this content item’s slug changes the link disappears from the topic page. This is because the curated lists/groups are based on base paths. 
The “contents” slugs don’t get updated as a part of dependency resolution in Publishing API.
Use content_ids to present curated lists (aka groups) instead of base_paths, as they are less volatile.
The “contents” key will be removed after the migration.
- https://github.com/alphagov/publishing-api/pull/2201
---

Use content ids to present curated lists (aka groups)

---

Dockerfile
config/application.rb

This will allow for adding precompiled assets into `/public/assets/collections-publisher` folder when defining the ENV `ASSETS_PREFIX=collections-publisher`
if ENV value is not present it will default to /public/assets/ folder

Adding ability to add ASSETS_PREFIX ENV value.

---

app/models/tag.rb
app/services/list_republisher.rb
db/migrate/20150622073727_add_redirects_for_topics_namespace.rb
db/migrate/20150625151822_add_browse_redirects.rb
db/migrate/20150713124417_import_router_data_browse_redirects.rb
db/migrate/20150714140302_import_router_data_topic_redirects.rb
lib/tasks/publishing_api.rake
spec/lib/tasks/publishing_api_spec.rb
spec/services/list_republisher_spec.rb

The existing `send_published_tags` task does not represent "groups" which are used to render curated lists. 
https://github.com/alphagov/collections-publisher/blob/main/app/presenters/tag_presenter.rb#L79-L84
We need to republish tags with curated lists / groups to migrate from using "contents" to "content_ids".
Code inspired by [ListPublisher](https://github.com/alphagov/collections-publisher/blob/main/app/services/list_publisher.rb) and TagRepublisher.

Add rake task to republish tags with curated lists

---

app/presenters/groups_presenter.rb
spec/controllers/list_items_controller_spec.rb
spec/controllers/lists_controller_spec.rb
spec/features/cuarating_lists_spec.rb
spec/features/curating_a_list_spec.rb
spec/presenters/groups_presenter_spec.rb
spec/presenters/tag_presenter_spec.rb
spec/services/list_publisher_spec.rb
spec/services/list_republisher_spec.rb

It's been replaced by content_ids in https://github.com/alphagov/collections-publisher/pull/1749
Depends on:
- https://github.com/alphagov/publishing-api/pull/2233

Remove contents from GroupsPresenter

---

Gemfile
Gemfile.lock

This app doesn't directly use this gem and it has just a dependency of rubocop-govuk.
Removing this from a direct dependency resolves a wtf and means we won't have direct dependabot for this dependency unless there is a security issue.

Remove parser from being a direct dependency

---

.github/workflows/ci.yml

This application depends on the Content Schemas. Making the tests reusable allows Publishing API to run the tests when the Content Schemas are updated.

Make ruby tests a reusable workflow

---

.dockerignore
Dockerfile
Gemfile
Gemfile.lock
config/application.rb
config/boot.rb

- Use bootsnap to reduce startup resource usage spike.
- Include the app name in `assets.prefix` so that assets can coexist nicely with other apps' assets on S3.
- Parameterise Ruby version.
- Make better use of WORKDIR.
- Use env vars from the base image where appropriate, instead of hardcoding paths.
- Remove unnecessary use of `bundle exec`.
- Add .dockerignore.
Tested: app boots successfully with `docker run`.

Dockerfile cleanup + enable bootsnap.

---

app/services/tag_archiver.rb
spec/services/tag_archiver_spec.rb

When a specialist topic is archived from the collections publisher UI, do not send an email if the page is being redirected to a document collection.
When we archive and redirect a specialist topic, we automatically unsubscribe all existing subscribers to the specialist topic, and email them a notification.
Soon we will begin the process of converting some specialist topics into document collections. The workflow for this will be:
1. From Whitehall, publish a new document collection using the content of the specialist topic.
2. From collections publisher (this application), archive and redirect the specialist topic to the new document collection page.
Because the content of these pages is so similar, we will be migrating the subscribers from the topic over to the new document collection …

Don't email subscribers of retired topics if successor is a document collection

---

app/controllers/topics_controller.rb
app/forms/topic_archival_form.rb
app/views/topics/propose_archive.html.erb
spec/features/archiving_topic_tags_spec.rb
spec/forms/topic_archival_form_spec.rb

We are soon retiring the entire specialist topic tree. We will be archiving and redirecting to non-topic pages only from now on.
---------
------
https://trello.com/c/bQBWoeXI/1708-remove-specialist-topic-redirect-field-from-collections-publisher

Update to specialist topic archive UI

---

app/services/tag_archiver.rb
spec/services/tag_archiver_spec.rb

Reverts alphagov/collections-publisher#1838
See trello card: https://trello.com/c/Z90FAnOG/1829-automate-bulk-unsubscribe-of-email-subscribers-when-a-specialist-topic-is-archived-and-redirected-to-a-document-collection
This code was a temporary hack which can now be reverted as we have capacity to implement the full solution.

Revert "Don't email subscribers of retired topics if successor is a document collection"

---

Gemfile.lock

This will allow us to access support for email alert api's `bulk_migrate` endpoint, which will be used as part of automatically migrating email subscriptions when retiring specialist topics.
[Trello](https://trello.com/c/8FdQqZPb/1715-update-collections-publishers-tag-archiver-service-to-handle-existing-email-subscriptions-when-specialist-topics-are-archived-l)

Bump version of gds api adapters

---

lib/tasks/publishing_api.rake
spec/lib/tasks/publishing_api_spec.rb

A specialist topic was archived and redirected to the wrong page. This task allows us to update it. 
See commit message for implementation details
https://trello.com/c/ClsVzfXo/1867-change-redirect-of-1-archived-specialist-topic-page

Temporary rake task to update the redirect for an archived specialist topic

---

lib/tasks/publishing_api.rake
spec/lib/tasks/publishing_api_spec.rb

This task has now been run on production and can be removed. If we want to support this functionality more permanently, we should improve the validation on the redirect content item.
https://trello.com/c/UUhob9oc/1870-remove-temporary-rake-task-in-email-alert-api-and-collections-publisher
Reverts alphagov/collections-publisher#1902

Revert "Temporary rake task to update the redirect for an archived specialist topic"

---

app/services/email_alerts_updater.rb
app/services/tag_archiver.rb
spec/services/tag_archiver_spec.rb

In https://github.com/alphagov/collections-publisher/pull/1848 we updated the UI in this application so that it's no longer possible to redirect specialist topics to specialist topics, only to redirect to content_items. This is because we are soon retiring the entire specialist topic tree.
The tag archiver specs were not updated to reflect this change, and still tested the topic -> topic redirect behaviour.
This PR:
- Updates the specs
- Removes the unnecessary type check in the email alert updater class
- Injects the email_alerts_updater class to simplify the tests
Trello: https://trello.com/c/siCRG1zk/1978-extend-the-collections-publisher-tag-archiver-service-to-handle-document-collections-which-have-a-taxonomytopicemailoverride-fie
⚠️ This repo is Continuously Deployed: make sure you …

Update tag archiver

---

lib/tasks/publishing_api.rake
spec/lib/tasks/publishing_api_spec.rb

Reverts alphagov/collections-publisher#1903
A specialist topic has been archived and redirected to the wrong page, and we once again need to update the redirect!

Reinstate rake task to update the redirect for an archived specialist topic

---

app/forms/topic_archival_form.rb
app/services/email_alert_api/subscriber_list_updater.rb
config/exceptional_bulk_migrations.yml
config/locales/en.yml
spec/services/email_alert_api/subscriber_list_updater_spec.rb

Includes the setting for the foreign entertainer tax rules bulk migration exception
Update collections publisher with a special case to make sure email notifications are handled correctly.
HMRC want to archive this specialist topic page [https://www.gov.uk/topic/personal-tax/foreign-entertainer-rules](https://www.gov.uk/topic/personal-tax/foreign-entertainer-rules "smartCard-inline")
and redirect it to an existing document collection (which is also tagged to the specialist topic) [https://www.gov.uk/government/collections/foreign-entertainers-forms](https://www.gov.uk/government/collections/foreign-entertainers-fo …

Email bulk migration exceptions

---

lib/tasks/publishing_api.rake

Once all Level one and level two specialist topics have been redirected, we can redirect the root page to [Services and Information](https://www.gov.uk/browse)
https://trello.com/c/QrOJukDq/2373-retire-final-root-specialist-topic-page-s

Redirect the root specialist topic page to /browse

---

lib/tasks/publishing_api.rake

This rake task to retire the root specialist topic page has been run on production and can now be removed.
Reverts alphagov/collections-publisher#2082

Revert "Redirect the root specialist topic page to /browse"

---

app/assets/config/manifest.js
app/assets/javascripts/application.js
app/assets/javascripts/domain-config.js
app/views/layouts/design_system.html.erb

Use the `load-analytics' script of govuk_publishing_components to add GA4 analytics to collections-publisher. Includes extra configuration to set the correct domains for GA4 to initialise and code to automatically accept all cookies to make tracking work.
UA is being deprecated, we need to switch our apps to use GA4 instead.
[Relevant Trello Card](https://trello.com/c/U1GlVZRF/196-implement-page-view-tracking-in-ga4-for-mpe-owned-publishing-apps)

Add GA4 analytics

---

app/controllers/secondary_content_links_controller.rb

Resolves https://github.com/alphagov/collections-publisher/security/code-scanning/2 (not an actual security issue though).

Don't use String::gsub where we mean String::strip.

---

app/views/step_by_step_pages/schedule_datetime.html.erb

This label was mistakenly copied from the Date one.
| Before | After |
|--------|-----|
| ![before](https://github.com/alphagov/collections-publisher/assets/5111927/5bfb3389-84a5-4793-a6fc-a5aa99022a8d) | ![after](https://github.com/alphagov/collections-publisher/assets/5111927/f866316d-c845-443c-8beb-5fc839b43117) |
Zendesk ticket: https://govuk.zendesk.com/agent/tickets/5825085

Fix label ('Date' -> 'Time')

---

Gemfile.lock
app/assets/config/manifest.js
app/assets/javascripts/application.js
app/assets/javascripts/es6-components.js
app/assets/stylesheets/application.scss
app/helpers/status_helper.rb
app/views/layouts/design_system.html.erb
app/views/mainstream_browse_pages/_create_update_form.html.erb
app/views/shared/_children-list.html.erb
spec/features/managing_browse_pages_spec.rb

[Trello](https://trello.com/c/HYqXLv8w/347-upgrade-govukpublishingcomponents-gem-dependency-v5-of-govuk-frontend-collections-publisher)
This work updates Collections Publisher to V5 of the Design System. The only visual changes this makes are shown below. All other issues identified when testing (see [here](https://trello.com/c/3KcURoRn)) are now resolved.
Visual changes: 
- Tags now appear with the first letter capitalised rather than all lower case
- The font size of the list of subtopics is increased from 14px to 16px. The Design System is moving away from 14px text. 
|Updated|Current|
|-|-|
|![Screenshot 2024-07-22 at 15 45 45](https://github.com/user-attachments/assets/9acb0e19-a27f-439b-a05e-285020ecb97a)|![Screenshot 2024-07-22 at 15 45 …

Upgrade govuk publishing components gov.uk frontend v5

---

config/locales/en.yml

Link for content patterns guidance seems to be broken and this [was highlighted](https://gds.slack.com/archives/C051S690LGL/p1723554496733949) by Gavan Curley <gavan.curley@digital.cabinet-office.gov.uk>.
Have updated the link to point to the one shared.

Update broken link for content patterns guidance

---

app/views/components/_markdown_editor.html.erb

The old Google Analytics, Universal Analytics (UA), has stopped working after 1st July 2024.
This PR removes any reference or use the old Analytics code.
[Trello](https://trello.com/c/dCfon29Y/343-remove-remaining-ua-code-from-collections-publisher)

Remove old google tag code

---

.github/workflows/copy-pr-template-to-dependabot-prs.yml
.github/workflows/rspec.yml

Some GitHub actions that were being referenced were quite old—update to use the latest version.
This resolved failing "actionlint" Actions.

Update github actions

---

app/assets/stylesheets/application.scss

Add tag import, as I merged the gem release without adding this so the CSS for the tag is missing on the live site currently.

Add tag import
