alphagov/collections-publisher

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
- spec/support/authentication.rb
- spec/support/capybara.rb
See individual commits for details.
> Tidy some of the test setup

- db/migrate/20150608145958_remove_unused_topic_record.rb
- db/schema.rb
All content from this subtopic has been moved to other pages. This
migration removes the Topic associated with the slug
immigration-operational-guidance/european-casework-instructions
cc @alext @rboulton 
Pivotal Tracker: https://www.pivotaltracker.com/story/show/91699292
> Migration to remove unused subtopic

- app/presenters/mainstream_browse_page_presenter.rb
Rename MainstreamBrowsePagePresenter  method
> Rename top_level_browse_page_id to active_top_level_browse_page_id

- app/presenters/topic_presenter.rb
- spec/presenters/topic_presenter_spec.rb
Part of: https://trello.com/c/ySxyNh02/169-remove-collections-api-app
Previous PR: https://github.com/alphagov/govuk-content-schemas/pull/84
> Include subtopic parent in data sent to content-store

- lib/tasks/publishing_api.rake
Sending to the publishing-api occasionally times out (especially in
preview).  Add a retry here to avoid aborting mid-job if possible.
I've tested this on my dev VM by adding
```ruby
if rand > 0.8
sleep 10
end
```
to the content-store update action.
> Retry on timeout in publishing_api rake tasks

- spec/presenters/root_browse_page_presenter_spec.rb
This commit refactors the spec for RootBrowsePagePresenter. It copies the setup (factory creation) into the example blocks, making it clear what things in the setup being tested. It makes the tests independently readable.
Originally part of a PR to add actual functionality that's not necessary anymore.
> Small refactor of RootBrowsePagePresenter spec

- app/notifiers/rummager_notifier.rb
- spec/notifiers/rummager_notifier_spec.rb
This will enable us to avoid the mess here:
https://github.com/alphagov/rummager/blob/5ac805b/lib/registry.rb#L93-L107
> Send topic slug to rummager.

- db/migrate/20150710133820_replace_topic.rb
- db/schema.rb
Redirecting /topic/environmental-management/climate-change-energy to new
/topic/climate-change-energy topic.
https://trello.com/c/hlaQdfwQ
> Migration to remove and redirect a topic

- lib/tasks/compare.rake
Generate CSVs of the differences in the list of items tagged with a tag
as reported by rummager and contentapi
> Task to compare tags in rummager and contentapi

- app/views/topics/_redirects.html.erb
- app/views/topics/propose_archive.html.erb
Some fixups for https://github.com/alphagov/collections-publisher/pull/138.
Trello: https://trello.com/c/ybdnGMhl/274-remove-empty-sub-topic-researching-in-prisons
> Fix table heading and page header for archival

- Gemfile
- Gemfile.lock
> Use pessimistic locking for govuk_admin_template

- db/migrate/20160205141721_remove_newest_redirects_table.rb
- db/migrate/20160205144140_remove_related_tag_id_from_redirect_items.rb
- db/migrate/20160205144906_remove_redirects_table.rb
- db/schema.rb
Removes table redirects
Removes related_tag_id column from redirect_items
Removes newest_redirects table
> Tidy up: Removes unused tables and column

- app/views/taxons/index.html.erb
Convenient to look at the api representation with a single click.
> Add a working hyperlink to the taxon index

- app/presenters/tag_presenter.rb
- spec/notifiers/rummager_notifier_spec.rb
This will make it possible to search for anything rendered or publishing by a certain app from search.
https://trello.com/c/iMotNdUv
> Add publishing_app & rendering_app to rummager payload

- Dockerfile
- config/database.yml
- db/seeds.rb
As part of a project expanding on the existing alphagov/publishing-e2e-tests we are adding a basic Dockerfile for use from that repository.
> Add Dockerfile

- lib/tasks/publishing_api.rake
We have updated content for our search consumers.  This has been provided by our content designers so should OK.
> Update metadescriptions on tasklists

- lib/tasks/publishing_api.rake
These tasks have been run on production and staging already.
@deborahchua @andysellick
> Add rake tasks for unpublishing task lists

- app/helpers/application_helper.rb
- config/initializers/gds-sso.rb
- spec/features/navigating_browse_pages_spec.rb
This depends on a Plek update https://github.com/alphagov/collections-publisher/pull/307
> Handle external urls

- app/assets/stylesheets/steps.scss
- app/controllers/step_by_step_pages_controller.rb
- app/controllers/steps_controller.rb
- app/models/step_by_step_page.rb
- app/views/shared/steps/_form_notice.html.erb
- app/views/shared/steps/_markdown_help.html.erb
- app/views/shared/steps/_step_breadcrumb.html.erb
- app/views/step_by_step_pages/_form.html.erb
- app/views/step_by_step_pages/edit.html.erb
- app/views/step_by_step_pages/index.html.erb
- app/views/step_by_step_pages/new.html.erb
- app/views/step_by_step_pages/show.html.erb
- app/views/steps/_form.html.erb
- app/views/steps/edit.html.erb
- app/views/steps/new.html.erb
- config/routes.rb
- spec/factories.rb
- spec/features/managing_step_by_step_pages_spec.rb
- spec/models/step_by_step_page_spec.rb
- spec/support/navigation_steps.rb
https://trello.com/c/I7BkEdQz/522-build-pages-for-step-by-step-in-collections-publisher
> Build step by step pages

- Jenkinsfile
- app/controllers/steps_controller.rb
This allows us to find security vulnerabilities.
[Trello Card](https://trello.com/c/JyrOAef3/363-fix-sql-injection-vulnerabilities-in-govuk-applications)
> Enable Brakeman

- .rubocop.yml
- Gemfile
- Rakefile
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/curated_lists.scss
- app/assets/stylesheets/forms.scss
- app/assets/stylesheets/steps.scss
- app/assets/stylesheets/template.scss
- app/assets/stylesheets/topics.scss
- app/assets/stylesheets/views/mainstream_browse_pages.scss
- app/controllers/mainstream_browse_pages_controller.rb
- app/presenters/tag_presenter.rb
- app/services/tag_republisher.rb
- app/views/lists/_all_list_items.html.erb
- app/views/lists/_new_list.html.erb
- config/environments/production.rb
- config/routes.rb
- lib/tasks/lint.rake
- spec/features/navigating_browse_pages_spec.rb
- spec/models/tagged_documents_spec.rb
- spec/notifiers/publishing_api_notifier_spec.rb
- spec/presenters/archived_tag_presenter_spec.rb
- spec/presenters/root_browse_page_presenter_spec.rb
- spec/presenters/root_topic_presenter_spec.rb
> Add linting

- lib/special_route_publisher.rb
- lib/tasks/publishing_api.rake
We have updated the URL and description following user research.
> Edit campaign route and description

- lib/special_route_publisher.rb
> Update citizen readiness title

- app/models/step_by_step_page.rb
- spec/models/step_by_step_page_spec.rb
Trello: https://trello.com/c/oX0nn9NG
This check will allow us to determine which status to display to users
and to determine if the step by step should still be published at the
scheduled time
> Add check to see if step by step is scheduled

- Dockerfile
- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
Add the publishing component gem to collections publisher.
> Add GOVUK publishing components to collections publisher

- app/views/step_by_step_pages/index.html.erb
- spec/models/step_by_step_page_spec.rb
Trello: https://trello.com/c/xX526kEN
> Allow step by steps to be filtered by "scheduled"

- Gemfile
- Gemfile.lock
- Rakefile
- spec/javascripts/components/steps-spec.js
- spec/javascripts/fixtures/overview-table.html
- spec/javascripts/helpers/jasmine-jquery.js
- spec/javascripts/support/jasmine.yml
- spec/javascripts/support/jasmine_helper.rb
Sets up Jasmine test task (`rake jasmine:ci`) and writes tests for the step by step navigation publisher overview, covering:
- Searching by title
- Searching by slug
- Filtering by status filter
https://trello.com/c/DsQ3GRq0/79-add-js-test-for-search-filtering-on-step-by-step-index-l
> Adds JavaScript tests for Step by Step overview page

- spec/models/step_by_step_page_spec.rb
- spec/presenters/step_by_step_page_presenter_spec.rb
Removes a rogue "binding.pry" and makes one of the tests more consistent
> Random clean up

- docs/arch/adr-3-store-status.md
Trello: https://trello.com/c/0H0pphSZ
Related to: PR #713 
👉 [Rendered version](https://github.com/alphagov/collections-publisher/blob/a67248a890bef16a951d77392b94cebeb8116377/docs/arch/adr-3-store-status.md)
> Add ADR for storing step by step status

- app/views/step_by_step_pages/schedule_datetime.html.erb
- config/routes.rb
Remove publish-or-delete route and relict link to it
[Trello card](https://trello.com/c/CXwhB5tD/76-simplify-tests-after-ui-changes?menu=filter&filter=label:Frontend%20Development)
> Remove publish-or-delete route and relict link to it

- app/views/shared/steps/_markdown_help.html.erb
- config/locales/en.yml
> Fix formatting guidance

- app/views/step_by_step_pages/show/_required_actions.html.erb
- spec/features/managing_step_by_step_pages_spec.rb
- spec/features/step_by_step_actions_spec.rb
- spec/support/step_nav_steps.rb
**Reviewer: **
<kbd>
</kbd>
**Review requestor: **
<kbd>
</kbd>
> Complete feature tests for hiding Publish/Schedule & fix inset prompt

- app/views/step_by_step_pages/show/_actions.erb
- spec/support/step_nav_steps.rb
[Trello card](https://trello.com/c/4e9qloaP)
> Open preview links in a new tab

- app/presenters/step_by_step_page_presenter.rb
- spec/features/managing_step_by_step_pages_spec.rb
This will make the label consistent across the app.
[Trello card](https://trello.com/c/5jVgQzvZ)
> Use "Meta description" label on summary page

- config/locales/en.yml
Reduces length of guidance on the editor
> Reduces length of guidance on the editor

- config/locales/en.yml
> content update

- app/lib/services.rb
- spec/controllers/step_by_step_pages_controller_spec.rb
- spec/features/archiving_mainstream_browse_page_tags_spec.rb
- spec/features/archiving_topic_tags_spec.rb
- spec/features/create_step_by_step_spec.rb
- spec/features/filter_step_by_steps_spec.rb
- spec/features/managing_step_by_step_pages_spec.rb
- spec/features/managing_steps_spec.rb
- spec/forms/mainstream_browse_page_archival_form_spec.rb
- spec/forms/topic_archival_form_spec.rb
- spec/models/link_report_spec.rb
- spec/models/step_spec.rb
- spec/support/link_checker.rb
- spec/support/publishing_api_helpers.rb
https://trello.com/c/EcitEsfK/1297-audit-dependabot-for-collections-publisher
> Fix GDS API deprecation warnings

- app/views/coronavirus/index.html.erb
Makes it easier for users to follow the process by splitting everything up into steps
> Makes the interface more user friendly

- lib/tasks/publishing_api.rake
Need to run this before fixing the todo in https://github.com/alphagov/collections/pull/1643
https://trello.com/b/ZpHjvMR2/govuk-corona-product-doing
> Update path to be business-support

- app/presenters/sub_section_json_presenter.rb
- app/services/pattern_maker.rb
- spec/presenters/sub_section_json_presenter_spec.rb
- spec/services/pattern_maker_spec.rb
Create a presenter `SubSectionJsonPresenter` that takes a SubSection instance and generates a hash (for conversion to JSON) that can be used to publish the data within the sub section.
The presenter uses `PatternMaker` to allow human readable instructions to be converted into Regular Expressions.
Example usage:
```ruby
2.6.6 :006 > s = SubSection.new(title: 'This title', content: "## A Title\n(foo)[path/to/foo]\n(bar)[path/to/bar]")
=> #<SubSection id: nil, title: "This title", content: "## A Title\n(foo)[path/to/foo]\n(bar)[path/to/bar]", coronavirus_page_id: nil, created_at: nil, updated_at: nil> 
2.6.6 :007 > p = SubSectionJsonPresenter.new(s)
=> #<SubSectionJsonPresenter:0x0000563743762a70 @sub_section=#<SubSection id: nil, title: "This title", content: "## A …
```
> 377 coronavirus publishing tool update draft content item (parsing and JSON build)

- app/controllers/coronavirus_pages_controller.rb
- app/views/coronavirus_pages/_actions.html.erb
- spec/features/coronavirus_page_spec.rb
- spec/support/coronavirus_feature_steps.rb
pair programming effort with @reggieb 
- wire up publish button
- wire up preview button
- feature tests
trello: https://trello.com/c/WesaBXx3/358-story-2-publish-accordions-from-collections-publisher
> Coronavirus page publishing tool: Publish coronavirus sections content

- app/controllers/reorder_sub_sections_controller.rb
- app/views/coronavirus_pages/_sub_sections_summary_list.html.erb
> Coronavirus publishing tool: link to reorder

- app/services/coronavirus_pages/content_builder.rb
- spec/services/coronavirus_pages/content_builder_spec.rb
- spec/support/coronavirus_feature_steps.rb
https://trello.com/c/IKsdjb01/380-coronavirus-publishing-tool-rename-sectionscontent-sections
> Coronavirus publishing tool: Rename to live key

- lib/special_route_publisher.rb
- Adds new route for the DIT landing page, `/eubusiness`.
- Removes `/prepare-eu-exit` as that page is now redirected to `/transition`
trello: https://trello.com/c/BWoZhE3E/369-build-dit-campaign-page
> Update special routes

- app/controllers/step_by_step_pages_controller.rb
- spec/services/datetime_parser_spec.rb
These are the necessary changes for Ruby 2.7.1
I've left the Ruby version as 2.6.6 since there is a script to update all the apps' Ruby versions at once.
> Upgrade to Ruby 2.7.1

- .gitignore
- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
> Add SimpleCov to monitor code coverage

- spec/services/coronavirus_pages/content_builder_spec.rb
Trello: https://trello.com/c/1YohbtSc
These test should have been added as part of: https://github.com/alphagov/collections-publisher/pull/1215
> Add missing tests for livestream data

- spec/support/coronavirus_feature_steps.rb
Trello: https://trello.com/c/W4nJDLBi
- Changes one test to check what's on the page.
- Cleans up the syntax of an expectation.
> Tweak timeline entries feature tests

- app/views/coronavirus/pages/index.html.erb
- config/locales/en.yml
> Update edit link text to include header section

- docs/arch/adr-04-merging-mainstream-to-specialist-topics.md
Documents decisions we've made on work for merging of Topics.
[Trello](https://trello.com/c/74zggnUA/874-write-up-architectural-decision-records-for-topics-merging)
> Add ADR for merging Mainstream and Specialist

- app/views/mainstream_browse_pages/index.html.erb
> Fix mainstream browse page pluralisation

- .dockerignore
- Dockerfile
- config/puma.rb
Updated Dockerfile:
Multistage build dockerfile using self managed Base image.
Replaced Foreman with Puma.
https://trello.com/c/4idzCwO7/712-package-collections-publisher-for-migration
> Update dockerfile to meet replatforming standards

- db/migrate/20230120143600_remove_topic_for_page.rb
- db/schema.rb
https://govuk.zendesk.com/agent/tickets/5184763
> Manually remove topics for MainstreamBrowsePage

- Gemfile
- Gemfile.lock
- config/environments/production.rb
https://trello.com/c/8VXSZTtR/601-replace-use-of-uglifier-with-terser-in-collections-publisher
> Replaces uglifier with terser

- .govuk_dependabot_merger.yml
https://trello.com/c/4pIItxp9/602-start-using-the-dependency-auto-merger
> Adds config to support auto merging govuk component dependencies

- .govuk_dependabot_merger.yml
> Adds stylelint-config-gds to dependabot merger config

- .github/workflows/actionlint.yml
This adds GH Action lint checking to Collections Publisher.
> Add GH Action Linting check
